# 4. Run PyNNLF SA BESS Experiments

This notebook is the manual launch point for the SA BESS PyNNLF experiment. It does not run automatically when opened. Run the cells when you are ready to start or resume the long model batch.

## 1. Setup

Resolve the publication project and the local PyNNLF source tree. The local `src` path is inserted before importing PyNNLF so the notebook uses this repository version, not an older installed package.

In [1]:
from pathlib import Path
import sys

def find_publication_project(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'scripts' / 'run_sa_bess_batch.py').exists() and (candidate / 'specs' / 'sa_bess_batch.yaml').exists():
            return candidate
    raise FileNotFoundError('Could not find publication/journal_article_1 from the current working directory.')

def find_repo_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'pyproject.toml').exists() and (candidate / 'src' / 'pynnlf').exists():
            return candidate
    raise FileNotFoundError('Could not find the PyNNLF repo root.')

PROJECT_DIR = find_publication_project(Path.cwd().resolve())
REPO_ROOT = find_repo_root(PROJECT_DIR)
sys.path.insert(0, str(REPO_ROOT / 'src'))
sys.path.insert(0, str(PROJECT_DIR / 'scripts'))

print(f'Publication project: {PROJECT_DIR}')
print(f'PyNNLF repo root: {REPO_ROOT}')

Publication project: C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1
PyNNLF repo root: C:\Users\z5404477\Documents\PyNNLF

## 2. Validate Input Datasets

Confirm the three SA BESS datasets are ready for PyNNLF. These checks are quick and do not train any models.

In [2]:
import pandas as pd

dataset_files = [
    'ds16_sa_bess_underlying_load_30min.csv',
    'ds17_sa_bess_net_load_with_pv_30min.csv',
    'ds18_sa_bess_net_load_with_pv_battery_30min.csv',
]

for filename in dataset_files:
    path = PROJECT_DIR / 'data' / filename
    df = pd.read_csv(path, parse_dates=['datetime'])
    assert list(df.columns) == ['datetime', 'netload_kW'], filename
    assert len(df) == 17_520, filename
    assert df.isna().sum().sum() == 0, filename
    assert df['datetime'].diff().dropna().nunique() == 1, filename
    assert df['datetime'].diff().dropna().iloc[0] == pd.Timedelta(minutes=30), filename
    print(f'{filename}: OK | {df.datetime.min()} to {df.datetime.max()} | rows={len(df):,}')

ds16_sa_bess_underlying_load_30min.csv: OK | 2024-02-26 00:00:00 to 2025-02-24 23:30:00 | rows=17,520
ds17_sa_bess_net_load_with_pv_30min.csv: OK | 2024-02-26 00:00:00 to 2025-02-24 23:30:00 | rows=17,520
ds18_sa_bess_net_load_with_pv_battery_30min.csv: OK | 2024-02-26 00:00:00 to 2025-02-24 23:30:00 | rows=17,520

## 3. Run Or Resume The Full Batch

This is the long-running step. The runner is resumable: completed dataset/model/hyperparameter combinations are skipped on later runs. Plots are disabled by the runner to keep output size down.

In [3]:
from run_sa_bess_batch import main as run_sa_bess_batch

run_sa_bess_batch()

[skip 1/36] ds16 m17 hp1
[skip 2/36] ds16 m8 hp1
[skip 3/36] ds16 m6 hp1
[skip 4/36] ds16 m10 hp1
[skip 5/36] ds16 m7 hp1
[skip 6/36] ds16 m1 hp1
[skip 7/36] ds16 m3 hp1
[skip 8/36] ds16 m9 hp3
[run 9/36] ds16 m13 hp2
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Epoch [1/100]
Epoch [1/100] and batch [1/3]
Epoch [1/100] and batch [2/3]
Epoch [1/100] and batch [3/3]
Epoch [1/100], Loss: 3080390.2500, time taken: 8.59 seconds
Epoch [2/100]
Epoch [2/100] and batch [1/3]
Epoch [2/100] and batch [2/3]
Epoch [2/100] and batch [3/3]
Epoch [2/100], Loss: 2852560.7500, time taken: 8.73 seconds
Epoch [3/100]
Epoch [3/100] and batch [1/3]
Epoch [3/100] and batch [2/3]
Epoch [3/100] and batch [3/3]
Epoch [3/100], Loss: 2635199.0000, time taken: 8.12 seconds
Epoch [4/100]
Epoch [4/100] and batch [1/3]
Epoch [4/100] and batch [2/3]
Epoch [4/100] and batch [3/3]
Epoch [4/100], Loss: 2433459.0000, time taken: 6.14 seconds
Epoch [5/100]
Epoch [5/100] and batch [1/3]
Epoch [5/100] and batch [2/3]
Epoch [5/100] and batch [3/3]
Epoch [5/100], Loss: 2235697.0000, time taken: 7.88 seconds
Epoch [6/100]
Epoch [6/100] and batch [1/3]
Epoch [6/100] and batch [2/3]
Epoch [6/100] and batch [3/3]
Epoch [6/100], Loss: 2045831.6250, time taken: 14.30 seconds
Epoch [7/100]
Epoch [7/100] and batch [1/3]
Epoch [7/100] and batch [2/3]
Epoch [7/100] and batch [3/3]
Epoch [7/100], Loss: 1871314.1250, time taken: 9.09 seconds
Epoch [8/100]
Epoch [8/100] and batch [1/3]
Epoch [8/100] and batch [2/3]
Epoch [8/100] and batch [3/3]
Epoch [8/100], Loss: 1702006.2500, time taken: 6.92 seconds
Epoch [9/100]
Epoch [9/100] and batch [1/3]
Epoch [9/100] and batch [2/3]
Epoch [9/100] and batch [3/3]
Epoch [9/100], Loss: 1544459.8750, time taken: 7.27 seconds
Epoch [10/100]
Epoch [10/100] and batch [1/3]
Epoch [10/100] and batch [2/3]
Epoch [10/100] and batch [3/3]
Epoch [10/100], Loss: 1402311.8750, time taken: 7.67 seconds
Epoch [11/100]
Epoch [11/100] and batch [1/3]
Epoch [11/100] and batch [2/3]
Epoch [11/100] and batch [3/3]
Epoch [11/100], Loss: 1264310.7500, time taken: 8.13 seconds
Epoch [12/100]
Epoch [12/100] and batch [1/3]
Epoch [12/100] and batch [2/3]
Epoch [12/100] and batch [3/3]
Epoch [12/100], Loss: 1141885.7500, time taken: 9.48 seconds
Epoch [13/100]
Epoch [13/100] and batch [1/3]
Epoch [13/100] and batch [2/3]
Epoch [13/100] and batch [3/3]
Epoch [13/100], Loss: 1023645.6250, time taken: 9.73 seconds
Epoch [14/100]
Epoch [14/100] and batch [1/3]
Epoch [14/100] and batch [2/3]
Epoch [14/100] and batch [3/3]
Epoch [14/100], Loss: 917588.5000, time taken: 10.01 seconds
Epoch [15/100]
Epoch [15/100] and batch [1/3]
Epoch [15/100] and batch [2/3]
Epoch [15/100] and batch [3/3]
Epoch [15/100], Loss: 818184.4375, time taken: 9.69 seconds
Epoch [16/100]
Epoch [16/100] and batch [1/3]
Epoch [16/100] and batch [2/3]
Epoch [16/100] and batch [3/3]
Epoch [16/100], Loss: 727555.0000, time taken: 10.01 seconds
Epoch [17/100]
Epoch [17/100] and batch [1/3]
Epoch [17/100] and batch [2/3]
Epoch [17/100] and batch [3/3]
Epoch [17/100], Loss: 644761.6875, time taken: 9.89 seconds
Epoch [18/100]
Epoch [18/100] and batch [1/3]
Epoch [18/100] and batch [2/3]
Epoch [18/100] and batch [3/3]
Epoch [18/100], Loss: 573385.1250, time taken: 8.93 seconds
Epoch [19/100]
Epoch [19/100] and batch [1/3]
Epoch [19/100] and batch [2/3]
Epoch [19/100] and batch [3/3]
Epoch [19/100], Loss: 504967.5312, time taken: 8.72 seconds
Epoch [20/100]
Epoch [20/100] and batch [1/3]
Epoch [20/100] and batch [2/3]
Epoch [20/100] and batch [3/3]
Epoch [20/100], Loss: 443699.2812, time taken: 9.23 seconds
Epoch [21/100]
Epoch [21/100] and batch [1/3]
Epoch [21/100] and batch [2/3]
Epoch [21/100] and batch [3/3]
Epoch [21/100], Loss: 387701.1562, time taken: 9.82 seconds
Epoch [22/100]
Epoch [22/100] and batch [1/3]
Epoch [22/100] and batch [2/3]
Epoch [22/100] and batch [3/3]
Epoch [22/100], Loss: 339506.7500, time taken: 9.22 seconds
Epoch [23/100]
Epoch [23/100] and batch [1/3]
Epoch [23/100] and batch [2/3]
Epoch [23/100] and batch [3/3]
Epoch [23/100], Loss: 295117.6250, time taken: 8.70 seconds
Epoch [24/100]
Epoch [24/100] and batch [1/3]
Epoch [24/100] and batch [2/3]
Epoch [24/100] and batch [3/3]
Epoch [24/100], Loss: 255845.2969, time taken: 9.40 seconds
Epoch [25/100]
Epoch [25/100] and batch [1/3]
Epoch [25/100] and batch [2/3]
Epoch [25/100] and batch [3/3]
Epoch [25/100], Loss: 221017.2812, time taken: 9.32 seconds
Epoch [26/100]
Epoch [26/100] and batch [1/3]
Epoch [26/100] and batch [2/3]
Epoch [26/100] and batch [3/3]
Epoch [26/100], Loss: 191587.5156, time taken: 9.91 seconds
Epoch [27/100]
Epoch [27/100] and batch [1/3]
Epoch [27/100] and batch [2/3]
Epoch [27/100] and batch [3/3]
Epoch [27/100], Loss: 165301.8438, time taken: 10.62 seconds
Epoch [28/100]
Epoch [28/100] and batch [1/3]
Epoch [28/100] and batch [2/3]
Epoch [28/100] and batch [3/3]
Epoch [28/100], Loss: 141362.9688, time taken: 10.05 seconds
Epoch [29/100]
Epoch [29/100] and batch [1/3]
Epoch [29/100] and batch [2/3]
Epoch [29/100] and batch [3/3]
Epoch [29/100], Loss: 120193.5078, time taken: 10.05 seconds
Epoch [30/100]
Epoch [30/100] and batch [1/3]
Epoch [30/100] and batch [2/3]
Epoch [30/100] and batch [3/3]
Epoch [30/100], Loss: 103259.0234, time taken: 10.07 seconds
Epoch [31/100]
Epoch [31/100] and batch [1/3]
Epoch [31/100] and batch [2/3]
Epoch [31/100] and batch [3/3]
Epoch [31/100], Loss: 88017.3516, time taken: 11.01 seconds
Epoch [32/100]
Epoch [32/100] and batch [1/3]
Epoch [32/100] and batch [2/3]
Epoch [32/100] and batch [3/3]
Epoch [32/100], Loss: 73154.4531, time taken: 12.32 seconds
Epoch [33/100]
Epoch [33/100] and batch [1/3]
Epoch [33/100] and batch [2/3]
Epoch [33/100] and batch [3/3]
Epoch [33/100], Loss: 62559.4766, time taken: 11.60 seconds
Epoch [34/100]
Epoch [34/100] and batch [1/3]
Epoch [34/100] and batch [2/3]
Epoch [34/100] and batch [3/3]
Epoch [34/100], Loss: 53675.5039, time taken: 11.00 seconds
Epoch [35/100]
Epoch [35/100] and batch [1/3]
Epoch [35/100] and batch [2/3]
Epoch [35/100] and batch [3/3]
Epoch [35/100], Loss: 44314.7734, time taken: 11.27 seconds
Epoch [36/100]
Epoch [36/100] and batch [1/3]
Epoch [36/100] and batch [2/3]
Epoch [36/100] and batch [3/3]
Epoch [36/100], Loss: 37297.5039, time taken: 11.06 seconds
Epoch [37/100]
Epoch [37/100] and batch [1/3]
Epoch [37/100] and batch [2/3]
Epoch [37/100] and batch [3/3]
Epoch [37/100], Loss: 31533.2207, time taken: 11.10 seconds
Epoch [38/100]
Epoch [38/100] and batch [1/3]
Epoch [38/100] and batch [2/3]
Epoch [38/100] and batch [3/3]
Epoch [38/100], Loss: 26340.9004, time taken: 11.53 seconds
Epoch [39/100]
Epoch [39/100] and batch [1/3]
Epoch [39/100] and batch [2/3]
Epoch [39/100] and batch [3/3]
Epoch [39/100], Loss: 22277.0410, time taken: 11.54 seconds
Epoch [40/100]
Epoch [40/100] and batch [1/3]
Epoch [40/100] and batch [2/3]
Epoch [40/100] and batch [3/3]
Epoch [40/100], Loss: 18652.3730, time taken: 11.48 seconds
Epoch [41/100]
Epoch [41/100] and batch [1/3]
Epoch [41/100] and batch [2/3]
Epoch [41/100] and batch [3/3]
Epoch [41/100], Loss: 15565.3027, time taken: 11.31 seconds
Epoch [42/100]
Epoch [42/100] and batch [1/3]
Epoch [42/100] and batch [2/3]
Epoch [42/100] and batch [3/3]
Epoch [42/100], Loss: 13195.1689, time taken: 10.98 seconds
Epoch [43/100]
Epoch [43/100] and batch [1/3]
Epoch [43/100] and batch [2/3]
Epoch [43/100] and batch [3/3]
Epoch [43/100], Loss: 11262.5459, time taken: 11.70 seconds
Epoch [44/100]
Epoch [44/100] and batch [1/3]
Epoch [44/100] and batch [2/3]
Epoch [44/100] and batch [3/3]
Epoch [44/100], Loss: 10013.3252, time taken: 11.53 seconds
Epoch [45/100]
Epoch [45/100] and batch [1/3]
Epoch [45/100] and batch [2/3]
Epoch [45/100] and batch [3/3]
Epoch [45/100], Loss: 8128.2788, time taken: 11.70 seconds
Epoch [46/100]
Epoch [46/100] and batch [1/3]
Epoch [46/100] and batch [2/3]
Epoch [46/100] and batch [3/3]
Epoch [46/100], Loss: 7397.9375, time taken: 11.70 seconds
Epoch [47/100]
Epoch [47/100] and batch [1/3]
Epoch [47/100] and batch [2/3]
Epoch [47/100] and batch [3/3]
Epoch [47/100], Loss: 6413.3882, time taken: 11.85 seconds
Epoch [48/100]
Epoch [48/100] and batch [1/3]
Epoch [48/100] and batch [2/3]
Epoch [48/100] and batch [3/3]
Epoch [48/100], Loss: 5717.5151, time taken: 11.82 seconds
Epoch [49/100]
Epoch [49/100] and batch [1/3]
Epoch [49/100] and batch [2/3]
Epoch [49/100] and batch [3/3]
Epoch [49/100], Loss: 5306.4761, time taken: 10.91 seconds
Epoch [50/100]
Epoch [50/100] and batch [1/3]
Epoch [50/100] and batch [2/3]
Epoch [50/100] and batch [3/3]
Epoch [50/100], Loss: 4895.5400, time taken: 11.94 seconds
Epoch [51/100]
Epoch [51/100] and batch [1/3]
Epoch [51/100] and batch [2/3]
Epoch [51/100] and batch [3/3]
Epoch [51/100], Loss: 4451.8833, time taken: 15.91 seconds
Epoch [52/100]
Epoch [52/100] and batch [1/3]
Epoch [52/100] and batch [2/3]
Epoch [52/100] and batch [3/3]
Epoch [52/100], Loss: 4207.3579, time taken: 17.31 seconds
Epoch [53/100]
Epoch [53/100] and batch [1/3]
Epoch [53/100] and batch [2/3]
Epoch [53/100] and batch [3/3]
Epoch [53/100], Loss: 4181.4258, time taken: 15.84 seconds
Epoch [54/100]
Epoch [54/100] and batch [1/3]
Epoch [54/100] and batch [2/3]
Epoch [54/100] and batch [3/3]
Epoch [54/100], Loss: 3923.3838, time taken: 13.80 seconds
Epoch [55/100]
Epoch [55/100] and batch [1/3]
Epoch [55/100] and batch [2/3]
Epoch [55/100] and batch [3/3]
Epoch [55/100], Loss: 3816.6455, time taken: 14.29 seconds
Epoch [56/100]
Epoch [56/100] and batch [1/3]
Epoch [56/100] and batch [2/3]
Epoch [56/100] and batch [3/3]
Epoch [56/100], Loss: 3709.4692, time taken: 11.34 seconds
Epoch [57/100]
Epoch [57/100] and batch [1/3]
Epoch [57/100] and batch [2/3]
Epoch [57/100] and batch [3/3]
Epoch [57/100], Loss: 3612.8557, time taken: 10.25 seconds
Epoch [58/100]
Epoch [58/100] and batch [1/3]
Epoch [58/100] and batch [2/3]
Epoch [58/100] and batch [3/3]
Epoch [58/100], Loss: 3657.3281, time taken: 8.27 seconds
Epoch [59/100]
Epoch [59/100] and batch [1/3]
Epoch [59/100] and batch [2/3]
Epoch [59/100] and batch [3/3]
Epoch [59/100], Loss: 3487.8184, time taken: 8.13 seconds
Epoch [60/100]
Epoch [60/100] and batch [1/3]
Epoch [60/100] and batch [2/3]
Epoch [60/100] and batch [3/3]
Epoch [60/100], Loss: 3499.4233, time taken: 8.76 seconds
Epoch [61/100]
Epoch [61/100] and batch [1/3]
Epoch [61/100] and batch [2/3]
Epoch [61/100] and batch [3/3]
Epoch [61/100], Loss: 3455.8914, time taken: 9.64 seconds
Epoch [62/100]
Epoch [62/100] and batch [1/3]
Epoch [62/100] and batch [2/3]
Epoch [62/100] and batch [3/3]
Epoch [62/100], Loss: 3531.7354, time taken: 9.40 seconds
Epoch [63/100]
Epoch [63/100] and batch [1/3]
Epoch [63/100] and batch [2/3]
Epoch [63/100] and batch [3/3]
Epoch [63/100], Loss: 3467.2876, time taken: 8.63 seconds
Epoch [64/100]
Epoch [64/100] and batch [1/3]
Epoch [64/100] and batch [2/3]
Epoch [64/100] and batch [3/3]
Epoch [64/100], Loss: 3523.5356, time taken: 8.72 seconds
Epoch [65/100]
Epoch [65/100] and batch [1/3]
Epoch [65/100] and batch [2/3]
Epoch [65/100] and batch [3/3]
Epoch [65/100], Loss: 3585.8271, time taken: 8.82 seconds
Epoch [66/100]
Epoch [66/100] and batch [1/3]
Epoch [66/100] and batch [2/3]
Epoch [66/100] and batch [3/3]
Epoch [66/100], Loss: 3457.1045, time taken: 8.29 seconds
Epoch [67/100]
Epoch [67/100] and batch [1/3]
Epoch [67/100] and batch [2/3]
Epoch [67/100] and batch [3/3]
Epoch [67/100], Loss: 3490.3010, time taken: 12.48 seconds
Epoch [68/100]
Epoch [68/100] and batch [1/3]
Epoch [68/100] and batch [2/3]
Epoch [68/100] and batch [3/3]
Epoch [68/100], Loss: 3561.5237, time taken: 15.37 seconds
Epoch [69/100]
Epoch [69/100] and batch [1/3]
Epoch [69/100] and batch [2/3]
Epoch [69/100] and batch [3/3]
Epoch [69/100], Loss: 3409.2566, time taken: 13.63 seconds
Epoch [70/100]
Epoch [70/100] and batch [1/3]
Epoch [70/100] and batch [2/3]
Epoch [70/100] and batch [3/3]
Epoch [70/100], Loss: 3474.3962, time taken: 12.37 seconds
Epoch [71/100]
Epoch [71/100] and batch [1/3]
Epoch [71/100] and batch [2/3]
Epoch [71/100] and batch [3/3]
Epoch [71/100], Loss: 3512.0066, time taken: 11.25 seconds
Epoch [72/100]
Epoch [72/100] and batch [1/3]
Epoch [72/100] and batch [2/3]
Epoch [72/100] and batch [3/3]
Epoch [72/100], Loss: 3565.5369, time taken: 11.80 seconds
Epoch [73/100]
Epoch [73/100] and batch [1/3]
Epoch [73/100] and batch [2/3]
Epoch [73/100] and batch [3/3]
Epoch [73/100], Loss: 3472.3604, time taken: 12.08 seconds
Epoch [74/100]
Epoch [74/100] and batch [1/3]
Epoch [74/100] and batch [2/3]
Epoch [74/100] and batch [3/3]
Epoch [74/100], Loss: 3451.5718, time taken: 11.62 seconds
Epoch [75/100]
Epoch [75/100] and batch [1/3]
Epoch [75/100] and batch [2/3]
Epoch [75/100] and batch [3/3]
Epoch [75/100], Loss: 3432.2798, time taken: 9.49 seconds
Epoch [76/100]
Epoch [76/100] and batch [1/3]
Epoch [76/100] and batch [2/3]
Epoch [76/100] and batch [3/3]
Epoch [76/100], Loss: 3530.8145, time taken: 7.90 seconds
Epoch [77/100]
Epoch [77/100] and batch [1/3]
Epoch [77/100] and batch [2/3]
Epoch [77/100] and batch [3/3]
Epoch [77/100], Loss: 3426.5681, time taken: 8.38 seconds
Epoch [78/100]
Epoch [78/100] and batch [1/3]
Epoch [78/100] and batch [2/3]
Epoch [78/100] and batch [3/3]
Epoch [78/100], Loss: 3478.4299, time taken: 8.00 seconds
Epoch [79/100]
Epoch [79/100] and batch [1/3]
Epoch [79/100] and batch [2/3]
Epoch [79/100] and batch [3/3]
Epoch [79/100], Loss: 3493.1409, time taken: 7.92 seconds
Epoch [80/100]
Epoch [80/100] and batch [1/3]
Epoch [80/100] and batch [2/3]
Epoch [80/100] and batch [3/3]
Epoch [80/100], Loss: 3434.2781, time taken: 9.07 seconds
Epoch [81/100]
Epoch [81/100] and batch [1/3]
Epoch [81/100] and batch [2/3]
Epoch [81/100] and batch [3/3]
Epoch [81/100], Loss: 3482.6777, time taken: 9.45 seconds
Epoch [82/100]
Epoch [82/100] and batch [1/3]
Epoch [82/100] and batch [2/3]
Epoch [82/100] and batch [3/3]
Epoch [82/100], Loss: 3441.1450, time taken: 14.34 seconds
Epoch [83/100]
Epoch [83/100] and batch [1/3]
Epoch [83/100] and batch [2/3]
Epoch [83/100] and batch [3/3]
Epoch [83/100], Loss: 3380.6829, time taken: 22.81 seconds
Epoch [84/100]
Epoch [84/100] and batch [1/3]
Epoch [84/100] and batch [2/3]
Epoch [84/100] and batch [3/3]
Epoch [84/100], Loss: 3471.7122, time taken: 17.75 seconds
Epoch [85/100]
Epoch [85/100] and batch [1/3]
Epoch [85/100] and batch [2/3]
Epoch [85/100] and batch [3/3]
Epoch [85/100], Loss: 3471.0317, time taken: 16.23 seconds
Epoch [86/100]
Epoch [86/100] and batch [1/3]
Epoch [86/100] and batch [2/3]
Epoch [86/100] and batch [3/3]
Epoch [86/100], Loss: 3413.3569, time taken: 15.24 seconds
Epoch [87/100]
Epoch [87/100] and batch [1/3]
Epoch [87/100] and batch [2/3]
Epoch [87/100] and batch [3/3]
Epoch [87/100], Loss: 3484.0095, time taken: 15.32 seconds
Epoch [88/100]
Epoch [88/100] and batch [1/3]
Epoch [88/100] and batch [2/3]
Epoch [88/100] and batch [3/3]
Epoch [88/100], Loss: 3513.1709, time taken: 15.15 seconds
Epoch [89/100]
Epoch [89/100] and batch [1/3]
Epoch [89/100] and batch [2/3]
Epoch [89/100] and batch [3/3]
Epoch [89/100], Loss: 3521.3179, time taken: 16.08 seconds
Epoch [90/100]
Epoch [90/100] and batch [1/3]
Epoch [90/100] and batch [2/3]
Epoch [90/100] and batch [3/3]
Epoch [90/100], Loss: 3574.3630, time taken: 15.13 seconds
Epoch [91/100]
Epoch [91/100] and batch [1/3]
Epoch [91/100] and batch [2/3]
Epoch [91/100] and batch [3/3]
Epoch [91/100], Loss: 3475.9780, time taken: 14.63 seconds
Epoch [92/100]
Epoch [92/100] and batch [1/3]
Epoch [92/100] and batch [2/3]
Epoch [92/100] and batch [3/3]
Epoch [92/100], Loss: 3456.7808, time taken: 15.94 seconds
Epoch [93/100]
Epoch [93/100] and batch [1/3]
Epoch [93/100] and batch [2/3]
Epoch [93/100] and batch [3/3]
Epoch [93/100], Loss: 3426.7180, time taken: 15.33 seconds
Epoch [94/100]
Epoch [94/100] and batch [1/3]
Epoch [94/100] and batch [2/3]
Epoch [94/100] and batch [3/3]
Epoch [94/100], Loss: 3383.5991, time taken: 14.53 seconds
Epoch [95/100]
Epoch [95/100] and batch [1/3]
Epoch [95/100] and batch [2/3]
Epoch [95/100] and batch [3/3]
Epoch [95/100], Loss: 3520.3611, time taken: 14.75 seconds
Epoch [96/100]
Epoch [96/100] and batch [1/3]
Epoch [96/100] and batch [2/3]
Epoch [96/100] and batch [3/3]
Epoch [96/100], Loss: 3441.5698, time taken: 14.73 seconds
Epoch [97/100]
Epoch [97/100] and batch [1/3]
Epoch [97/100] and batch [2/3]
Epoch [97/100] and batch [3/3]
Epoch [97/100], Loss: 3529.8884, time taken: 14.69 seconds
Epoch [98/100]
Epoch [98/100] and batch [1/3]
Epoch [98/100] and batch [2/3]
Epoch [98/100] and batch [3/3]
Epoch [98/100], Loss: 3444.0684, time taken: 14.12 seconds
Epoch [99/100]
Epoch [99/100] and batch [1/3]
Epoch [99/100] and batch [2/3]
Epoch [99/100] and batch [3/3]
Epoch [99/100], Loss: 3464.0139, time taken: 13.99 seconds
Epoch [100/100]
Epoch [100/100] and batch [1/3]
Epoch [100/100] and batch [2/3]
Epoch [100/100] and batch [3/3]
Epoch [100/100], Loss: 3456.3062, time taken: 14.23 seconds

Processing CV 2 / 10....
Epoch [1/100]
Epoch [1/100] and batch [1/3]
Epoch [1/100] and batch [2/3]
Epoch [1/100] and batch [3/3]
Epoch [1/100], Loss: 3087245.7500, time taken: 11.83 seconds
Epoch [2/100]
Epoch [2/100] and batch [1/3]
Epoch [2/100] and batch [2/3]
Epoch [2/100] and batch [3/3]
Epoch [2/100], Loss: 2859595.2500, time taken: 11.25 seconds
Epoch [3/100]
Epoch [3/100] and batch [1/3]
Epoch [3/100] and batch [2/3]
Epoch [3/100] and batch [3/3]
Epoch [3/100], Loss: 2641404.7500, time taken: 11.71 seconds
Epoch [4/100]
Epoch [4/100] and batch [1/3]
Epoch [4/100] and batch [2/3]
Epoch [4/100] and batch [3/3]
Epoch [4/100], Loss: 2439552.0000, time taken: 11.95 seconds
Epoch [5/100]
Epoch [5/100] and batch [1/3]
Epoch [5/100] and batch [2/3]
Epoch [5/100] and batch [3/3]
Epoch [5/100], Loss: 2241464.7500, time taken: 12.32 seconds
Epoch [6/100]
Epoch [6/100] and batch [1/3]
Epoch [6/100] and batch [2/3]
Epoch [6/100] and batch [3/3]
Epoch [6/100], Loss: 2051440.3750, time taken: 12.15 seconds
Epoch [7/100]
Epoch [7/100] and batch [1/3]
Epoch [7/100] and batch [2/3]
Epoch [7/100] and batch [3/3]
Epoch [7/100], Loss: 1876923.8750, time taken: 11.69 seconds
Epoch [8/100]
Epoch [8/100] and batch [1/3]
Epoch [8/100] and batch [2/3]
Epoch [8/100] and batch [3/3]
Epoch [8/100], Loss: 1707889.7500, time taken: 11.81 seconds
Epoch [9/100]
Epoch [9/100] and batch [1/3]
Epoch [9/100] and batch [2/3]
Epoch [9/100] and batch [3/3]
Epoch [9/100], Loss: 1549825.0000, time taken: 11.97 seconds
Epoch [10/100]
Epoch [10/100] and batch [1/3]
Epoch [10/100] and batch [2/3]
Epoch [10/100] and batch [3/3]
Epoch [10/100], Loss: 1407687.8750, time taken: 11.92 seconds
Epoch [11/100]
Epoch [11/100] and batch [1/3]
Epoch [11/100] and batch [2/3]
Epoch [11/100] and batch [3/3]
Epoch [11/100], Loss: 1268158.7500, time taken: 12.78 seconds
Epoch [12/100]
Epoch [12/100] and batch [1/3]
Epoch [12/100] and batch [2/3]
Epoch [12/100] and batch [3/3]
Epoch [12/100], Loss: 1146352.0000, time taken: 11.87 seconds
Epoch [13/100]
Epoch [13/100] and batch [1/3]
Epoch [13/100] and batch [2/3]
Epoch [13/100] and batch [3/3]
Epoch [13/100], Loss: 1028030.4375, time taken: 12.37 seconds
Epoch [14/100]
Epoch [14/100] and batch [1/3]
Epoch [14/100] and batch [2/3]
Epoch [14/100] and batch [3/3]
Epoch [14/100], Loss: 920565.6250, time taken: 12.73 seconds
Epoch [15/100]
Epoch [15/100] and batch [1/3]
Epoch [15/100] and batch [2/3]
Epoch [15/100] and batch [3/3]
Epoch [15/100], Loss: 822003.2500, time taken: 12.55 seconds
Epoch [16/100]
Epoch [16/100] and batch [1/3]
Epoch [16/100] and batch [2/3]
Epoch [16/100] and batch [3/3]
Epoch [16/100], Loss: 730102.4375, time taken: 12.77 seconds
Epoch [17/100]
Epoch [17/100] and batch [1/3]
Epoch [17/100] and batch [2/3]
Epoch [17/100] and batch [3/3]
Epoch [17/100], Loss: 647799.0625, time taken: 11.81 seconds
Epoch [18/100]
Epoch [18/100] and batch [1/3]

Importing plotly failed. Interactive plots will not work.

Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....

19:02:09 - cmdstanpy - INFO - Chain [1] start processing
19:02:10 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:02:12 - cmdstanpy - INFO - Chain [1] start processing
19:02:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

19:02:15 - cmdstanpy - INFO - Chain [1] start processing
19:02:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

19:02:16 - cmdstanpy - INFO - Chain [1] start processing
19:02:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:02:17 - cmdstanpy - INFO - Chain [1] start processing
19:02:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:02:18 - cmdstanpy - INFO - Chain [1] start processing
19:02:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

19:02:19 - cmdstanpy - INFO - Chain [1] start processing
19:02:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

19:02:20 - cmdstanpy - INFO - Chain [1] start processing
19:02:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:02:21 - cmdstanpy - INFO - Chain [1] start processing
19:02:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

19:02:23 - cmdstanpy - INFO - Chain [1] start processing
19:02:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

19:02:24 - cmdstanpy - INFO - Chain [1] start processing
19:02:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:02:25 - cmdstanpy - INFO - Chain [1] start processing
19:02:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:02:26 - cmdstanpy - INFO - Chain [1] start processing
19:02:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

19:02:27 - cmdstanpy - INFO - Chain [1] start processing
19:02:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

19:02:28 - cmdstanpy - INFO - Chain [1] start processing
19:02:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

19:02:29 - cmdstanpy - INFO - Chain [1] start processing
19:02:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:02:31 - cmdstanpy - INFO - Chain [1] start processing
19:02:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

19:02:31 - cmdstanpy - INFO - Chain [1] start processing
19:02:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:02:32 - cmdstanpy - INFO - Chain [1] start processing
19:02:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

19:02:34 - cmdstanpy - INFO - Chain [1] start processing
19:02:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:02:35 - cmdstanpy - INFO - Chain [1] start processing
19:02:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

19:02:37 - cmdstanpy - INFO - Chain [1] start processing
19:02:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

19:02:38 - cmdstanpy - INFO - Chain [1] start processing
19:02:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

19:02:39 - cmdstanpy - INFO - Chain [1] start processing
19:02:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

19:02:40 - cmdstanpy - INFO - Chain [1] start processing
19:02:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:02:41 - cmdstanpy - INFO - Chain [1] start processing
19:02:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

19:02:42 - cmdstanpy - INFO - Chain [1] start processing
19:02:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:02:42 - cmdstanpy - INFO - Chain [1] start processing
19:02:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:02:43 - cmdstanpy - INFO - Chain [1] start processing
19:02:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

19:02:44 - cmdstanpy - INFO - Chain [1] start processing
19:02:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

19:02:45 - cmdstanpy - INFO - Chain [1] start processing
19:02:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:02:46 - cmdstanpy - INFO - Chain [1] start processing
19:02:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:02:47 - cmdstanpy - INFO - Chain [1] start processing
19:02:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:02:48 - cmdstanpy - INFO - Chain [1] start processing
19:02:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:02:49 - cmdstanpy - INFO - Chain [1] start processing
19:02:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

19:02:50 - cmdstanpy - INFO - Chain [1] start processing
19:02:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

19:02:51 - cmdstanpy - INFO - Chain [1] start processing
19:02:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

19:02:52 - cmdstanpy - INFO - Chain [1] start processing
19:02:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:02:54 - cmdstanpy - INFO - Chain [1] start processing
19:02:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

19:02:55 - cmdstanpy - INFO - Chain [1] start processing
19:02:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

19:02:55 - cmdstanpy - INFO - Chain [1] start processing
19:02:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

19:02:57 - cmdstanpy - INFO - Chain [1] start processing
19:02:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

19:02:58 - cmdstanpy - INFO - Chain [1] start processing
19:02:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

19:02:58 - cmdstanpy - INFO - Chain [1] start processing
19:02:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:03:00 - cmdstanpy - INFO - Chain [1] start processing
19:03:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:03:01 - cmdstanpy - INFO - Chain [1] start processing
19:03:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:03:02 - cmdstanpy - INFO - Chain [1] start processing
19:03:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:03:04 - cmdstanpy - INFO - Chain [1] start processing
19:03:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:03:05 - cmdstanpy - INFO - Chain [1] start processing
19:03:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:03:06 - cmdstanpy - INFO - Chain [1] start processing
19:03:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:03:07 - cmdstanpy - INFO - Chain [1] start processing
19:03:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:03:08 - cmdstanpy - INFO - Chain [1] start processing
19:03:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

19:03:09 - cmdstanpy - INFO - Chain [1] start processing
19:03:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

19:03:10 - cmdstanpy - INFO - Chain [1] start processing
19:03:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:03:11 - cmdstanpy - INFO - Chain [1] start processing
19:03:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

19:03:12 - cmdstanpy - INFO - Chain [1] start processing
19:03:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:03:14 - cmdstanpy - INFO - Chain [1] start processing
19:03:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:03:14 - cmdstanpy - INFO - Chain [1] start processing
19:03:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:03:15 - cmdstanpy - INFO - Chain [1] start processing
19:03:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:03:17 - cmdstanpy - INFO - Chain [1] start processing
19:03:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

19:03:18 - cmdstanpy - INFO - Chain [1] start processing
19:03:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:03:20 - cmdstanpy - INFO - Chain [1] start processing
19:03:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:03:21 - cmdstanpy - INFO - Chain [1] start processing
19:03:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:03:22 - cmdstanpy - INFO - Chain [1] start processing
19:03:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:03:23 - cmdstanpy - INFO - Chain [1] start processing
19:03:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

19:03:24 - cmdstanpy - INFO - Chain [1] start processing
19:03:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:03:26 - cmdstanpy - INFO - Chain [1] start processing
19:03:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:03:27 - cmdstanpy - INFO - Chain [1] start processing
19:03:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:03:28 - cmdstanpy - INFO - Chain [1] start processing
19:03:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:03:29 - cmdstanpy - INFO - Chain [1] start processing
19:03:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:03:31 - cmdstanpy - INFO - Chain [1] start processing
19:03:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:03:32 - cmdstanpy - INFO - Chain [1] start processing
19:03:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:03:34 - cmdstanpy - INFO - Chain [1] start processing
19:03:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

19:03:35 - cmdstanpy - INFO - Chain [1] start processing
19:03:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:03:37 - cmdstanpy - INFO - Chain [1] start processing
19:03:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:03:38 - cmdstanpy - INFO - Chain [1] start processing
19:03:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:03:39 - cmdstanpy - INFO - Chain [1] start processing
19:03:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:03:40 - cmdstanpy - INFO - Chain [1] start processing
19:03:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:03:41 - cmdstanpy - INFO - Chain [1] start processing
19:03:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:03:42 - cmdstanpy - INFO - Chain [1] start processing
19:03:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:03:43 - cmdstanpy - INFO - Chain [1] start processing
19:03:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:03:44 - cmdstanpy - INFO - Chain [1] start processing
19:03:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:03:46 - cmdstanpy - INFO - Chain [1] start processing
19:03:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

19:03:47 - cmdstanpy - INFO - Chain [1] start processing
19:03:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:03:48 - cmdstanpy - INFO - Chain [1] start processing
19:03:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:03:49 - cmdstanpy - INFO - Chain [1] start processing
19:03:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:03:51 - cmdstanpy - INFO - Chain [1] start processing
19:03:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:03:52 - cmdstanpy - INFO - Chain [1] start processing
19:03:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:03:53 - cmdstanpy - INFO - Chain [1] start processing
19:03:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:03:54 - cmdstanpy - INFO - Chain [1] start processing
19:03:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:03:56 - cmdstanpy - INFO - Chain [1] start processing
19:03:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:03:57 - cmdstanpy - INFO - Chain [1] start processing
19:03:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:03:58 - cmdstanpy - INFO - Chain [1] start processing
19:03:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:03:59 - cmdstanpy - INFO - Chain [1] start processing
19:04:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:04:00 - cmdstanpy - INFO - Chain [1] start processing
19:04:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:04:01 - cmdstanpy - INFO - Chain [1] start processing
19:04:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:04:02 - cmdstanpy - INFO - Chain [1] start processing
19:04:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:04:03 - cmdstanpy - INFO - Chain [1] start processing
19:04:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:04:04 - cmdstanpy - INFO - Chain [1] start processing
19:04:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:04:06 - cmdstanpy - INFO - Chain [1] start processing
19:04:06 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 2 / 10....

19:04:07 - cmdstanpy - INFO - Chain [1] start processing
19:04:08 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:04:10 - cmdstanpy - INFO - Chain [1] start processing
19:04:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

19:04:13 - cmdstanpy - INFO - Chain [1] start processing
19:04:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

19:04:14 - cmdstanpy - INFO - Chain [1] start processing
19:04:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:04:15 - cmdstanpy - INFO - Chain [1] start processing
19:04:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:04:16 - cmdstanpy - INFO - Chain [1] start processing
19:04:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

19:04:17 - cmdstanpy - INFO - Chain [1] start processing
19:04:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

19:04:18 - cmdstanpy - INFO - Chain [1] start processing
19:04:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:04:19 - cmdstanpy - INFO - Chain [1] start processing
19:04:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

19:04:20 - cmdstanpy - INFO - Chain [1] start processing
19:04:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

19:04:21 - cmdstanpy - INFO - Chain [1] start processing
19:04:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:04:22 - cmdstanpy - INFO - Chain [1] start processing
19:04:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:04:23 - cmdstanpy - INFO - Chain [1] start processing
19:04:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

19:04:24 - cmdstanpy - INFO - Chain [1] start processing
19:04:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

19:04:25 - cmdstanpy - INFO - Chain [1] start processing
19:04:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

19:04:26 - cmdstanpy - INFO - Chain [1] start processing
19:04:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:04:27 - cmdstanpy - INFO - Chain [1] start processing
19:04:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

19:04:28 - cmdstanpy - INFO - Chain [1] start processing
19:04:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:04:29 - cmdstanpy - INFO - Chain [1] start processing
19:04:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

19:04:30 - cmdstanpy - INFO - Chain [1] start processing
19:04:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:04:31 - cmdstanpy - INFO - Chain [1] start processing
19:04:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

19:04:32 - cmdstanpy - INFO - Chain [1] start processing
19:04:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

19:04:34 - cmdstanpy - INFO - Chain [1] start processing
19:04:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

19:04:35 - cmdstanpy - INFO - Chain [1] start processing
19:04:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

19:04:36 - cmdstanpy - INFO - Chain [1] start processing
19:04:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:04:37 - cmdstanpy - INFO - Chain [1] start processing
19:04:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

19:04:38 - cmdstanpy - INFO - Chain [1] start processing
19:04:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:04:39 - cmdstanpy - INFO - Chain [1] start processing
19:04:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:04:40 - cmdstanpy - INFO - Chain [1] start processing
19:04:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

19:04:41 - cmdstanpy - INFO - Chain [1] start processing
19:04:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

19:04:42 - cmdstanpy - INFO - Chain [1] start processing
19:04:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:04:43 - cmdstanpy - INFO - Chain [1] start processing
19:04:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:04:45 - cmdstanpy - INFO - Chain [1] start processing
19:04:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:04:46 - cmdstanpy - INFO - Chain [1] start processing
19:04:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:04:47 - cmdstanpy - INFO - Chain [1] start processing
19:04:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

19:04:48 - cmdstanpy - INFO - Chain [1] start processing
19:04:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

19:04:49 - cmdstanpy - INFO - Chain [1] start processing
19:04:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

19:04:50 - cmdstanpy - INFO - Chain [1] start processing
19:04:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:04:51 - cmdstanpy - INFO - Chain [1] start processing
19:04:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

19:04:52 - cmdstanpy - INFO - Chain [1] start processing
19:04:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

19:04:53 - cmdstanpy - INFO - Chain [1] start processing
19:04:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

19:04:54 - cmdstanpy - INFO - Chain [1] start processing
19:04:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

19:04:55 - cmdstanpy - INFO - Chain [1] start processing
19:04:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

19:04:56 - cmdstanpy - INFO - Chain [1] start processing
19:04:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:04:57 - cmdstanpy - INFO - Chain [1] start processing
19:04:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:04:58 - cmdstanpy - INFO - Chain [1] start processing
19:04:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:04:59 - cmdstanpy - INFO - Chain [1] start processing
19:05:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:05:01 - cmdstanpy - INFO - Chain [1] start processing
19:05:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:05:02 - cmdstanpy - INFO - Chain [1] start processing
19:05:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:05:04 - cmdstanpy - INFO - Chain [1] start processing
19:05:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:05:05 - cmdstanpy - INFO - Chain [1] start processing
19:05:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:05:05 - cmdstanpy - INFO - Chain [1] start processing
19:05:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

19:05:06 - cmdstanpy - INFO - Chain [1] start processing
19:05:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

19:05:07 - cmdstanpy - INFO - Chain [1] start processing
19:05:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:05:09 - cmdstanpy - INFO - Chain [1] start processing
19:05:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

19:05:10 - cmdstanpy - INFO - Chain [1] start processing
19:05:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:05:12 - cmdstanpy - INFO - Chain [1] start processing
19:05:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:05:13 - cmdstanpy - INFO - Chain [1] start processing
19:05:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:05:14 - cmdstanpy - INFO - Chain [1] start processing
19:05:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:05:15 - cmdstanpy - INFO - Chain [1] start processing
19:05:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

19:05:16 - cmdstanpy - INFO - Chain [1] start processing
19:05:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:05:17 - cmdstanpy - INFO - Chain [1] start processing
19:05:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:05:18 - cmdstanpy - INFO - Chain [1] start processing
19:05:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:05:19 - cmdstanpy - INFO - Chain [1] start processing
19:05:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:05:21 - cmdstanpy - INFO - Chain [1] start processing
19:05:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

19:05:21 - cmdstanpy - INFO - Chain [1] start processing
19:05:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:05:22 - cmdstanpy - INFO - Chain [1] start processing
19:05:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:05:24 - cmdstanpy - INFO - Chain [1] start processing
19:05:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:05:25 - cmdstanpy - INFO - Chain [1] start processing
19:05:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:05:26 - cmdstanpy - INFO - Chain [1] start processing
19:05:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:05:27 - cmdstanpy - INFO - Chain [1] start processing
19:05:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:05:28 - cmdstanpy - INFO - Chain [1] start processing
19:05:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:05:30 - cmdstanpy - INFO - Chain [1] start processing
19:05:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

19:05:31 - cmdstanpy - INFO - Chain [1] start processing
19:05:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:05:32 - cmdstanpy - INFO - Chain [1] start processing
19:05:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:05:33 - cmdstanpy - INFO - Chain [1] start processing
19:05:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:05:35 - cmdstanpy - INFO - Chain [1] start processing
19:05:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:05:36 - cmdstanpy - INFO - Chain [1] start processing
19:05:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:05:37 - cmdstanpy - INFO - Chain [1] start processing
19:05:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:05:38 - cmdstanpy - INFO - Chain [1] start processing
19:05:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:05:39 - cmdstanpy - INFO - Chain [1] start processing
19:05:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:05:40 - cmdstanpy - INFO - Chain [1] start processing
19:05:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:05:41 - cmdstanpy - INFO - Chain [1] start processing
19:05:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

19:05:42 - cmdstanpy - INFO - Chain [1] start processing
19:05:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:05:42 - cmdstanpy - INFO - Chain [1] start processing
19:05:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:05:44 - cmdstanpy - INFO - Chain [1] start processing
19:05:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:05:45 - cmdstanpy - INFO - Chain [1] start processing
19:05:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:05:46 - cmdstanpy - INFO - Chain [1] start processing
19:05:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:05:46 - cmdstanpy - INFO - Chain [1] start processing
19:05:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:05:47 - cmdstanpy - INFO - Chain [1] start processing
19:05:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:05:48 - cmdstanpy - INFO - Chain [1] start processing
19:05:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:05:49 - cmdstanpy - INFO - Chain [1] start processing
19:05:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:05:50 - cmdstanpy - INFO - Chain [1] start processing
19:05:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:05:51 - cmdstanpy - INFO - Chain [1] start processing
19:05:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:05:52 - cmdstanpy - INFO - Chain [1] start processing
19:05:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:05:54 - cmdstanpy - INFO - Chain [1] start processing
19:05:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:05:54 - cmdstanpy - INFO - Chain [1] start processing
19:05:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:05:56 - cmdstanpy - INFO - Chain [1] start processing
19:05:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:05:57 - cmdstanpy - INFO - Chain [1] start processing
19:05:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:05:58 - cmdstanpy - INFO - Chain [1] start processing
19:05:58 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 3 / 10....

19:05:59 - cmdstanpy - INFO - Chain [1] start processing
19:06:00 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:06:01 - cmdstanpy - INFO - Chain [1] start processing
19:06:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

19:06:03 - cmdstanpy - INFO - Chain [1] start processing
19:06:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

19:06:05 - cmdstanpy - INFO - Chain [1] start processing
19:06:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:06:06 - cmdstanpy - INFO - Chain [1] start processing
19:06:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:06:06 - cmdstanpy - INFO - Chain [1] start processing
19:06:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

19:06:08 - cmdstanpy - INFO - Chain [1] start processing
19:06:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

19:06:09 - cmdstanpy - INFO - Chain [1] start processing
19:06:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:06:10 - cmdstanpy - INFO - Chain [1] start processing
19:06:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

19:06:10 - cmdstanpy - INFO - Chain [1] start processing
19:06:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

19:06:11 - cmdstanpy - INFO - Chain [1] start processing
19:06:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:06:12 - cmdstanpy - INFO - Chain [1] start processing
19:06:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:06:13 - cmdstanpy - INFO - Chain [1] start processing
19:06:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

19:06:14 - cmdstanpy - INFO - Chain [1] start processing
19:06:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

19:06:15 - cmdstanpy - INFO - Chain [1] start processing
19:06:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

19:06:16 - cmdstanpy - INFO - Chain [1] start processing
19:06:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:06:17 - cmdstanpy - INFO - Chain [1] start processing
19:06:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

19:06:18 - cmdstanpy - INFO - Chain [1] start processing
19:06:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:06:20 - cmdstanpy - INFO - Chain [1] start processing
19:06:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

19:06:20 - cmdstanpy - INFO - Chain [1] start processing
19:06:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:06:21 - cmdstanpy - INFO - Chain [1] start processing
19:06:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

19:06:23 - cmdstanpy - INFO - Chain [1] start processing
19:06:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

19:06:24 - cmdstanpy - INFO - Chain [1] start processing
19:06:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

19:06:25 - cmdstanpy - INFO - Chain [1] start processing
19:06:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

19:06:26 - cmdstanpy - INFO - Chain [1] start processing
19:06:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:06:27 - cmdstanpy - INFO - Chain [1] start processing
19:06:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

19:06:28 - cmdstanpy - INFO - Chain [1] start processing
19:06:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:06:29 - cmdstanpy - INFO - Chain [1] start processing
19:06:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:06:30 - cmdstanpy - INFO - Chain [1] start processing
19:06:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

19:06:31 - cmdstanpy - INFO - Chain [1] start processing
19:06:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

19:06:32 - cmdstanpy - INFO - Chain [1] start processing
19:06:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:06:33 - cmdstanpy - INFO - Chain [1] start processing
19:06:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:06:34 - cmdstanpy - INFO - Chain [1] start processing
19:06:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:06:35 - cmdstanpy - INFO - Chain [1] start processing
19:06:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:06:36 - cmdstanpy - INFO - Chain [1] start processing
19:06:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

19:06:37 - cmdstanpy - INFO - Chain [1] start processing
19:06:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

19:06:38 - cmdstanpy - INFO - Chain [1] start processing
19:06:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

19:06:38 - cmdstanpy - INFO - Chain [1] start processing
19:06:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:06:39 - cmdstanpy - INFO - Chain [1] start processing
19:06:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

19:06:40 - cmdstanpy - INFO - Chain [1] start processing
19:06:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

19:06:41 - cmdstanpy - INFO - Chain [1] start processing
19:06:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

19:06:42 - cmdstanpy - INFO - Chain [1] start processing
19:06:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

19:06:44 - cmdstanpy - INFO - Chain [1] start processing
19:06:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

19:06:44 - cmdstanpy - INFO - Chain [1] start processing
19:06:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:06:45 - cmdstanpy - INFO - Chain [1] start processing
19:06:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:06:46 - cmdstanpy - INFO - Chain [1] start processing
19:06:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:06:48 - cmdstanpy - INFO - Chain [1] start processing
19:06:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:06:49 - cmdstanpy - INFO - Chain [1] start processing
19:06:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:06:50 - cmdstanpy - INFO - Chain [1] start processing
19:06:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:06:51 - cmdstanpy - INFO - Chain [1] start processing
19:06:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:06:52 - cmdstanpy - INFO - Chain [1] start processing
19:06:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:06:53 - cmdstanpy - INFO - Chain [1] start processing
19:06:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

19:06:54 - cmdstanpy - INFO - Chain [1] start processing
19:06:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

19:06:56 - cmdstanpy - INFO - Chain [1] start processing
19:06:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:06:57 - cmdstanpy - INFO - Chain [1] start processing
19:06:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

19:06:58 - cmdstanpy - INFO - Chain [1] start processing
19:06:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:06:59 - cmdstanpy - INFO - Chain [1] start processing
19:07:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:07:00 - cmdstanpy - INFO - Chain [1] start processing
19:07:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:07:01 - cmdstanpy - INFO - Chain [1] start processing
19:07:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:07:02 - cmdstanpy - INFO - Chain [1] start processing
19:07:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

19:07:03 - cmdstanpy - INFO - Chain [1] start processing
19:07:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:07:04 - cmdstanpy - INFO - Chain [1] start processing
19:07:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:07:05 - cmdstanpy - INFO - Chain [1] start processing
19:07:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:07:06 - cmdstanpy - INFO - Chain [1] start processing
19:07:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:07:07 - cmdstanpy - INFO - Chain [1] start processing
19:07:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

19:07:08 - cmdstanpy - INFO - Chain [1] start processing
19:07:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:07:09 - cmdstanpy - INFO - Chain [1] start processing
19:07:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:07:10 - cmdstanpy - INFO - Chain [1] start processing
19:07:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:07:10 - cmdstanpy - INFO - Chain [1] start processing
19:07:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:07:12 - cmdstanpy - INFO - Chain [1] start processing
19:07:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:07:13 - cmdstanpy - INFO - Chain [1] start processing
19:07:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:07:14 - cmdstanpy - INFO - Chain [1] start processing
19:07:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:07:15 - cmdstanpy - INFO - Chain [1] start processing
19:07:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

19:07:15 - cmdstanpy - INFO - Chain [1] start processing
19:07:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:07:16 - cmdstanpy - INFO - Chain [1] start processing
19:07:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:07:17 - cmdstanpy - INFO - Chain [1] start processing
19:07:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:07:18 - cmdstanpy - INFO - Chain [1] start processing
19:07:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:07:19 - cmdstanpy - INFO - Chain [1] start processing
19:07:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:07:20 - cmdstanpy - INFO - Chain [1] start processing
19:07:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:07:21 - cmdstanpy - INFO - Chain [1] start processing
19:07:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:07:21 - cmdstanpy - INFO - Chain [1] start processing
19:07:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:07:22 - cmdstanpy - INFO - Chain [1] start processing
19:07:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:07:23 - cmdstanpy - INFO - Chain [1] start processing
19:07:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

19:07:25 - cmdstanpy - INFO - Chain [1] start processing
19:07:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:07:26 - cmdstanpy - INFO - Chain [1] start processing
19:07:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:07:26 - cmdstanpy - INFO - Chain [1] start processing
19:07:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:07:28 - cmdstanpy - INFO - Chain [1] start processing
19:07:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:07:29 - cmdstanpy - INFO - Chain [1] start processing
19:07:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:07:30 - cmdstanpy - INFO - Chain [1] start processing
19:07:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:07:31 - cmdstanpy - INFO - Chain [1] start processing
19:07:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:07:32 - cmdstanpy - INFO - Chain [1] start processing
19:07:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:07:33 - cmdstanpy - INFO - Chain [1] start processing
19:07:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:07:34 - cmdstanpy - INFO - Chain [1] start processing
19:07:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:07:35 - cmdstanpy - INFO - Chain [1] start processing
19:07:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:07:37 - cmdstanpy - INFO - Chain [1] start processing
19:07:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:07:38 - cmdstanpy - INFO - Chain [1] start processing
19:07:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:07:39 - cmdstanpy - INFO - Chain [1] start processing
19:07:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:07:41 - cmdstanpy - INFO - Chain [1] start processing
19:07:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:07:41 - cmdstanpy - INFO - Chain [1] start processing
19:07:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:07:42 - cmdstanpy - INFO - Chain [1] start processing
19:07:42 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 4 / 10....

19:07:43 - cmdstanpy - INFO - Chain [1] start processing
19:07:43 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:07:45 - cmdstanpy - INFO - Chain [1] start processing
19:07:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

19:07:46 - cmdstanpy - INFO - Chain [1] start processing
19:07:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

19:07:47 - cmdstanpy - INFO - Chain [1] start processing
19:07:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:07:48 - cmdstanpy - INFO - Chain [1] start processing
19:07:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:07:48 - cmdstanpy - INFO - Chain [1] start processing
19:07:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

19:07:49 - cmdstanpy - INFO - Chain [1] start processing
19:07:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

19:07:50 - cmdstanpy - INFO - Chain [1] start processing
19:07:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:07:51 - cmdstanpy - INFO - Chain [1] start processing
19:07:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

19:07:51 - cmdstanpy - INFO - Chain [1] start processing
19:07:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

19:07:52 - cmdstanpy - INFO - Chain [1] start processing
19:07:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:07:53 - cmdstanpy - INFO - Chain [1] start processing
19:07:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:07:54 - cmdstanpy - INFO - Chain [1] start processing
19:07:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

19:07:54 - cmdstanpy - INFO - Chain [1] start processing
19:07:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

19:07:55 - cmdstanpy - INFO - Chain [1] start processing
19:07:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

19:07:56 - cmdstanpy - INFO - Chain [1] start processing
19:07:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:07:57 - cmdstanpy - INFO - Chain [1] start processing
19:07:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

19:07:57 - cmdstanpy - INFO - Chain [1] start processing
19:07:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:07:58 - cmdstanpy - INFO - Chain [1] start processing
19:07:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

19:07:58 - cmdstanpy - INFO - Chain [1] start processing
19:07:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:07:59 - cmdstanpy - INFO - Chain [1] start processing
19:07:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

19:08:00 - cmdstanpy - INFO - Chain [1] start processing
19:08:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

19:08:01 - cmdstanpy - INFO - Chain [1] start processing
19:08:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

19:08:01 - cmdstanpy - INFO - Chain [1] start processing
19:08:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

19:08:02 - cmdstanpy - INFO - Chain [1] start processing
19:08:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:08:03 - cmdstanpy - INFO - Chain [1] start processing
19:08:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

19:08:04 - cmdstanpy - INFO - Chain [1] start processing
19:08:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:08:05 - cmdstanpy - INFO - Chain [1] start processing
19:08:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:08:05 - cmdstanpy - INFO - Chain [1] start processing
19:08:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

19:08:06 - cmdstanpy - INFO - Chain [1] start processing
19:08:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

19:08:07 - cmdstanpy - INFO - Chain [1] start processing
19:08:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:08:08 - cmdstanpy - INFO - Chain [1] start processing
19:08:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:08:09 - cmdstanpy - INFO - Chain [1] start processing
19:08:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:08:10 - cmdstanpy - INFO - Chain [1] start processing
19:08:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:08:10 - cmdstanpy - INFO - Chain [1] start processing
19:08:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

19:08:11 - cmdstanpy - INFO - Chain [1] start processing
19:08:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

19:08:12 - cmdstanpy - INFO - Chain [1] start processing
19:08:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

19:08:12 - cmdstanpy - INFO - Chain [1] start processing
19:08:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:08:13 - cmdstanpy - INFO - Chain [1] start processing
19:08:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

19:08:14 - cmdstanpy - INFO - Chain [1] start processing
19:08:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

19:08:15 - cmdstanpy - INFO - Chain [1] start processing
19:08:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

19:08:15 - cmdstanpy - INFO - Chain [1] start processing
19:08:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

19:08:16 - cmdstanpy - INFO - Chain [1] start processing
19:08:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

19:08:17 - cmdstanpy - INFO - Chain [1] start processing
19:08:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:08:17 - cmdstanpy - INFO - Chain [1] start processing
19:08:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:08:18 - cmdstanpy - INFO - Chain [1] start processing
19:08:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:08:19 - cmdstanpy - INFO - Chain [1] start processing
19:08:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:08:20 - cmdstanpy - INFO - Chain [1] start processing
19:08:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:08:20 - cmdstanpy - INFO - Chain [1] start processing
19:08:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:08:21 - cmdstanpy - INFO - Chain [1] start processing
19:08:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:08:22 - cmdstanpy - INFO - Chain [1] start processing
19:08:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:08:23 - cmdstanpy - INFO - Chain [1] start processing
19:08:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

19:08:24 - cmdstanpy - INFO - Chain [1] start processing
19:08:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

19:08:25 - cmdstanpy - INFO - Chain [1] start processing
19:08:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:08:25 - cmdstanpy - INFO - Chain [1] start processing
19:08:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

19:08:26 - cmdstanpy - INFO - Chain [1] start processing
19:08:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:08:27 - cmdstanpy - INFO - Chain [1] start processing
19:08:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:08:28 - cmdstanpy - INFO - Chain [1] start processing
19:08:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:08:29 - cmdstanpy - INFO - Chain [1] start processing
19:08:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:08:30 - cmdstanpy - INFO - Chain [1] start processing
19:08:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

19:08:30 - cmdstanpy - INFO - Chain [1] start processing
19:08:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:08:31 - cmdstanpy - INFO - Chain [1] start processing
19:08:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:08:32 - cmdstanpy - INFO - Chain [1] start processing
19:08:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:08:33 - cmdstanpy - INFO - Chain [1] start processing
19:08:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:08:33 - cmdstanpy - INFO - Chain [1] start processing
19:08:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

19:08:34 - cmdstanpy - INFO - Chain [1] start processing
19:08:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:08:35 - cmdstanpy - INFO - Chain [1] start processing
19:08:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:08:36 - cmdstanpy - INFO - Chain [1] start processing
19:08:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:08:37 - cmdstanpy - INFO - Chain [1] start processing
19:08:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:08:37 - cmdstanpy - INFO - Chain [1] start processing
19:08:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:08:38 - cmdstanpy - INFO - Chain [1] start processing
19:08:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:08:39 - cmdstanpy - INFO - Chain [1] start processing
19:08:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:08:40 - cmdstanpy - INFO - Chain [1] start processing
19:08:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

19:08:41 - cmdstanpy - INFO - Chain [1] start processing
19:08:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:08:42 - cmdstanpy - INFO - Chain [1] start processing
19:08:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:08:42 - cmdstanpy - INFO - Chain [1] start processing
19:08:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:08:43 - cmdstanpy - INFO - Chain [1] start processing
19:08:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:08:43 - cmdstanpy - INFO - Chain [1] start processing
19:08:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:08:44 - cmdstanpy - INFO - Chain [1] start processing
19:08:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:08:45 - cmdstanpy - INFO - Chain [1] start processing
19:08:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:08:46 - cmdstanpy - INFO - Chain [1] start processing
19:08:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:08:46 - cmdstanpy - INFO - Chain [1] start processing
19:08:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:08:47 - cmdstanpy - INFO - Chain [1] start processing
19:08:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

19:08:48 - cmdstanpy - INFO - Chain [1] start processing
19:08:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:08:50 - cmdstanpy - INFO - Chain [1] start processing
19:08:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:08:51 - cmdstanpy - INFO - Chain [1] start processing
19:08:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:08:52 - cmdstanpy - INFO - Chain [1] start processing
19:08:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:08:52 - cmdstanpy - INFO - Chain [1] start processing
19:08:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:08:53 - cmdstanpy - INFO - Chain [1] start processing
19:08:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:08:54 - cmdstanpy - INFO - Chain [1] start processing
19:08:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:08:55 - cmdstanpy - INFO - Chain [1] start processing
19:08:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:08:56 - cmdstanpy - INFO - Chain [1] start processing
19:08:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:08:58 - cmdstanpy - INFO - Chain [1] start processing
19:08:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:08:59 - cmdstanpy - INFO - Chain [1] start processing
19:08:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:09:00 - cmdstanpy - INFO - Chain [1] start processing
19:09:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:09:01 - cmdstanpy - INFO - Chain [1] start processing
19:09:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:09:02 - cmdstanpy - INFO - Chain [1] start processing
19:09:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:09:03 - cmdstanpy - INFO - Chain [1] start processing
19:09:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:09:04 - cmdstanpy - INFO - Chain [1] start processing
19:09:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:09:05 - cmdstanpy - INFO - Chain [1] start processing
19:09:06 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 5 / 10....

19:09:06 - cmdstanpy - INFO - Chain [1] start processing
19:09:07 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:09:08 - cmdstanpy - INFO - Chain [1] start processing
19:09:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

19:09:09 - cmdstanpy - INFO - Chain [1] start processing
19:09:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

19:09:10 - cmdstanpy - INFO - Chain [1] start processing
19:09:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:09:10 - cmdstanpy - INFO - Chain [1] start processing
19:09:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:09:11 - cmdstanpy - INFO - Chain [1] start processing
19:09:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

19:09:11 - cmdstanpy - INFO - Chain [1] start processing
19:09:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

19:09:12 - cmdstanpy - INFO - Chain [1] start processing
19:09:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:09:12 - cmdstanpy - INFO - Chain [1] start processing
19:09:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

19:09:13 - cmdstanpy - INFO - Chain [1] start processing
19:09:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

19:09:14 - cmdstanpy - INFO - Chain [1] start processing
19:09:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:09:14 - cmdstanpy - INFO - Chain [1] start processing
19:09:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:09:15 - cmdstanpy - INFO - Chain [1] start processing
19:09:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

19:09:16 - cmdstanpy - INFO - Chain [1] start processing
19:09:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

19:09:16 - cmdstanpy - INFO - Chain [1] start processing
19:09:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

19:09:17 - cmdstanpy - INFO - Chain [1] start processing
19:09:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:09:17 - cmdstanpy - INFO - Chain [1] start processing
19:09:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

19:09:18 - cmdstanpy - INFO - Chain [1] start processing
19:09:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:09:18 - cmdstanpy - INFO - Chain [1] start processing
19:09:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

19:09:19 - cmdstanpy - INFO - Chain [1] start processing
19:09:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:09:19 - cmdstanpy - INFO - Chain [1] start processing
19:09:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

19:09:20 - cmdstanpy - INFO - Chain [1] start processing
19:09:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

19:09:21 - cmdstanpy - INFO - Chain [1] start processing
19:09:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

19:09:21 - cmdstanpy - INFO - Chain [1] start processing
19:09:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

19:09:22 - cmdstanpy - INFO - Chain [1] start processing
19:09:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:09:22 - cmdstanpy - INFO - Chain [1] start processing
19:09:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

19:09:23 - cmdstanpy - INFO - Chain [1] start processing
19:09:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:09:24 - cmdstanpy - INFO - Chain [1] start processing
19:09:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:09:24 - cmdstanpy - INFO - Chain [1] start processing
19:09:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

19:09:25 - cmdstanpy - INFO - Chain [1] start processing
19:09:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

19:09:26 - cmdstanpy - INFO - Chain [1] start processing
19:09:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:09:26 - cmdstanpy - INFO - Chain [1] start processing
19:09:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:09:27 - cmdstanpy - INFO - Chain [1] start processing
19:09:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:09:28 - cmdstanpy - INFO - Chain [1] start processing
19:09:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:09:28 - cmdstanpy - INFO - Chain [1] start processing
19:09:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

19:09:29 - cmdstanpy - INFO - Chain [1] start processing
19:09:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

19:09:29 - cmdstanpy - INFO - Chain [1] start processing
19:09:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

19:09:30 - cmdstanpy - INFO - Chain [1] start processing
19:09:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:09:31 - cmdstanpy - INFO - Chain [1] start processing
19:09:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

19:09:31 - cmdstanpy - INFO - Chain [1] start processing
19:09:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

19:09:32 - cmdstanpy - INFO - Chain [1] start processing
19:09:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

19:09:33 - cmdstanpy - INFO - Chain [1] start processing
19:09:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

19:09:34 - cmdstanpy - INFO - Chain [1] start processing
19:09:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

19:09:34 - cmdstanpy - INFO - Chain [1] start processing
19:09:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:09:35 - cmdstanpy - INFO - Chain [1] start processing
19:09:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:09:35 - cmdstanpy - INFO - Chain [1] start processing
19:09:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:09:36 - cmdstanpy - INFO - Chain [1] start processing
19:09:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:09:37 - cmdstanpy - INFO - Chain [1] start processing
19:09:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:09:38 - cmdstanpy - INFO - Chain [1] start processing
19:09:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:09:39 - cmdstanpy - INFO - Chain [1] start processing
19:09:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:09:39 - cmdstanpy - INFO - Chain [1] start processing
19:09:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:09:40 - cmdstanpy - INFO - Chain [1] start processing
19:09:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

19:09:41 - cmdstanpy - INFO - Chain [1] start processing
19:09:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

19:09:42 - cmdstanpy - INFO - Chain [1] start processing
19:09:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:09:42 - cmdstanpy - INFO - Chain [1] start processing
19:09:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

19:09:43 - cmdstanpy - INFO - Chain [1] start processing
19:09:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:09:43 - cmdstanpy - INFO - Chain [1] start processing
19:09:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:09:44 - cmdstanpy - INFO - Chain [1] start processing
19:09:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:09:45 - cmdstanpy - INFO - Chain [1] start processing
19:09:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:09:46 - cmdstanpy - INFO - Chain [1] start processing
19:09:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

19:09:46 - cmdstanpy - INFO - Chain [1] start processing
19:09:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:09:47 - cmdstanpy - INFO - Chain [1] start processing
19:09:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:09:47 - cmdstanpy - INFO - Chain [1] start processing
19:09:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:09:48 - cmdstanpy - INFO - Chain [1] start processing
19:09:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:09:49 - cmdstanpy - INFO - Chain [1] start processing
19:09:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

19:09:49 - cmdstanpy - INFO - Chain [1] start processing
19:09:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:09:50 - cmdstanpy - INFO - Chain [1] start processing
19:09:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:09:50 - cmdstanpy - INFO - Chain [1] start processing
19:09:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:09:51 - cmdstanpy - INFO - Chain [1] start processing
19:09:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:09:52 - cmdstanpy - INFO - Chain [1] start processing
19:09:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:09:53 - cmdstanpy - INFO - Chain [1] start processing
19:09:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:09:54 - cmdstanpy - INFO - Chain [1] start processing
19:09:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:09:55 - cmdstanpy - INFO - Chain [1] start processing
19:09:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

19:09:55 - cmdstanpy - INFO - Chain [1] start processing
19:09:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:09:56 - cmdstanpy - INFO - Chain [1] start processing
19:09:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:09:57 - cmdstanpy - INFO - Chain [1] start processing
19:09:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:09:57 - cmdstanpy - INFO - Chain [1] start processing
19:09:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:09:58 - cmdstanpy - INFO - Chain [1] start processing
19:09:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:09:59 - cmdstanpy - INFO - Chain [1] start processing
19:09:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:10:00 - cmdstanpy - INFO - Chain [1] start processing
19:10:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:10:00 - cmdstanpy - INFO - Chain [1] start processing
19:10:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:10:01 - cmdstanpy - INFO - Chain [1] start processing
19:10:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:10:01 - cmdstanpy - INFO - Chain [1] start processing
19:10:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

19:10:02 - cmdstanpy - INFO - Chain [1] start processing
19:10:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:10:03 - cmdstanpy - INFO - Chain [1] start processing
19:10:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:10:04 - cmdstanpy - INFO - Chain [1] start processing
19:10:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:10:05 - cmdstanpy - INFO - Chain [1] start processing
19:10:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:10:05 - cmdstanpy - INFO - Chain [1] start processing
19:10:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:10:07 - cmdstanpy - INFO - Chain [1] start processing
19:10:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:10:07 - cmdstanpy - INFO - Chain [1] start processing
19:10:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:10:08 - cmdstanpy - INFO - Chain [1] start processing
19:10:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:10:09 - cmdstanpy - INFO - Chain [1] start processing
19:10:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:10:10 - cmdstanpy - INFO - Chain [1] start processing
19:10:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:10:11 - cmdstanpy - INFO - Chain [1] start processing
19:10:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:10:12 - cmdstanpy - INFO - Chain [1] start processing
19:10:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:10:12 - cmdstanpy - INFO - Chain [1] start processing
19:10:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:10:13 - cmdstanpy - INFO - Chain [1] start processing
19:10:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:10:14 - cmdstanpy - INFO - Chain [1] start processing
19:10:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:10:14 - cmdstanpy - INFO - Chain [1] start processing
19:10:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:10:16 - cmdstanpy - INFO - Chain [1] start processing
19:10:16 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 6 / 10....

19:10:16 - cmdstanpy - INFO - Chain [1] start processing
19:10:17 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:10:18 - cmdstanpy - INFO - Chain [1] start processing
19:10:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

19:10:19 - cmdstanpy - INFO - Chain [1] start processing
19:10:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

19:10:19 - cmdstanpy - INFO - Chain [1] start processing
19:10:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:10:20 - cmdstanpy - INFO - Chain [1] start processing
19:10:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:10:20 - cmdstanpy - INFO - Chain [1] start processing
19:10:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

19:10:21 - cmdstanpy - INFO - Chain [1] start processing
19:10:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

19:10:21 - cmdstanpy - INFO - Chain [1] start processing
19:10:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:10:22 - cmdstanpy - INFO - Chain [1] start processing
19:10:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

19:10:22 - cmdstanpy - INFO - Chain [1] start processing
19:10:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

19:10:23 - cmdstanpy - INFO - Chain [1] start processing
19:10:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:10:23 - cmdstanpy - INFO - Chain [1] start processing
19:10:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:10:24 - cmdstanpy - INFO - Chain [1] start processing
19:10:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

19:10:24 - cmdstanpy - INFO - Chain [1] start processing
19:10:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

19:10:25 - cmdstanpy - INFO - Chain [1] start processing
19:10:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

19:10:25 - cmdstanpy - INFO - Chain [1] start processing
19:10:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:10:26 - cmdstanpy - INFO - Chain [1] start processing
19:10:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

19:10:26 - cmdstanpy - INFO - Chain [1] start processing
19:10:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:10:27 - cmdstanpy - INFO - Chain [1] start processing
19:10:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

19:10:27 - cmdstanpy - INFO - Chain [1] start processing
19:10:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:10:28 - cmdstanpy - INFO - Chain [1] start processing
19:10:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

19:10:29 - cmdstanpy - INFO - Chain [1] start processing
19:10:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

19:10:29 - cmdstanpy - INFO - Chain [1] start processing
19:10:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

19:10:30 - cmdstanpy - INFO - Chain [1] start processing
19:10:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

19:10:30 - cmdstanpy - INFO - Chain [1] start processing
19:10:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:10:31 - cmdstanpy - INFO - Chain [1] start processing
19:10:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

19:10:31 - cmdstanpy - INFO - Chain [1] start processing
19:10:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:10:32 - cmdstanpy - INFO - Chain [1] start processing
19:10:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:10:32 - cmdstanpy - INFO - Chain [1] start processing
19:10:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

19:10:33 - cmdstanpy - INFO - Chain [1] start processing
19:10:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

19:10:33 - cmdstanpy - INFO - Chain [1] start processing
19:10:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:10:34 - cmdstanpy - INFO - Chain [1] start processing
19:10:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:10:34 - cmdstanpy - INFO - Chain [1] start processing
19:10:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:10:35 - cmdstanpy - INFO - Chain [1] start processing
19:10:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:10:35 - cmdstanpy - INFO - Chain [1] start processing
19:10:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

19:10:36 - cmdstanpy - INFO - Chain [1] start processing
19:10:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

19:10:37 - cmdstanpy - INFO - Chain [1] start processing
19:10:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

19:10:37 - cmdstanpy - INFO - Chain [1] start processing
19:10:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:10:38 - cmdstanpy - INFO - Chain [1] start processing
19:10:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

19:10:38 - cmdstanpy - INFO - Chain [1] start processing
19:10:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

19:10:39 - cmdstanpy - INFO - Chain [1] start processing
19:10:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

19:10:39 - cmdstanpy - INFO - Chain [1] start processing
19:10:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

19:10:40 - cmdstanpy - INFO - Chain [1] start processing
19:10:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

19:10:40 - cmdstanpy - INFO - Chain [1] start processing
19:10:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:10:41 - cmdstanpy - INFO - Chain [1] start processing
19:10:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:10:42 - cmdstanpy - INFO - Chain [1] start processing
19:10:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:10:42 - cmdstanpy - INFO - Chain [1] start processing
19:10:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:10:43 - cmdstanpy - INFO - Chain [1] start processing
19:10:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:10:44 - cmdstanpy - INFO - Chain [1] start processing
19:10:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:10:44 - cmdstanpy - INFO - Chain [1] start processing
19:10:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:10:45 - cmdstanpy - INFO - Chain [1] start processing
19:10:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:10:45 - cmdstanpy - INFO - Chain [1] start processing
19:10:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

19:10:46 - cmdstanpy - INFO - Chain [1] start processing
19:10:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

19:10:46 - cmdstanpy - INFO - Chain [1] start processing
19:10:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:10:47 - cmdstanpy - INFO - Chain [1] start processing
19:10:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

19:10:48 - cmdstanpy - INFO - Chain [1] start processing
19:10:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:10:48 - cmdstanpy - INFO - Chain [1] start processing
19:10:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:10:49 - cmdstanpy - INFO - Chain [1] start processing
19:10:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:10:49 - cmdstanpy - INFO - Chain [1] start processing
19:10:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:10:50 - cmdstanpy - INFO - Chain [1] start processing
19:10:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

19:10:50 - cmdstanpy - INFO - Chain [1] start processing
19:10:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:10:51 - cmdstanpy - INFO - Chain [1] start processing
19:10:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:10:52 - cmdstanpy - INFO - Chain [1] start processing
19:10:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:10:52 - cmdstanpy - INFO - Chain [1] start processing
19:10:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:10:53 - cmdstanpy - INFO - Chain [1] start processing
19:10:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

19:10:53 - cmdstanpy - INFO - Chain [1] start processing
19:10:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:10:54 - cmdstanpy - INFO - Chain [1] start processing
19:10:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:10:55 - cmdstanpy - INFO - Chain [1] start processing
19:10:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:10:55 - cmdstanpy - INFO - Chain [1] start processing
19:10:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:10:56 - cmdstanpy - INFO - Chain [1] start processing
19:10:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:10:56 - cmdstanpy - INFO - Chain [1] start processing
19:10:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:10:57 - cmdstanpy - INFO - Chain [1] start processing
19:10:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:10:57 - cmdstanpy - INFO - Chain [1] start processing
19:10:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

19:10:58 - cmdstanpy - INFO - Chain [1] start processing
19:10:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:10:58 - cmdstanpy - INFO - Chain [1] start processing
19:10:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:10:59 - cmdstanpy - INFO - Chain [1] start processing
19:10:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:11:00 - cmdstanpy - INFO - Chain [1] start processing
19:11:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:11:00 - cmdstanpy - INFO - Chain [1] start processing
19:11:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:11:01 - cmdstanpy - INFO - Chain [1] start processing
19:11:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:11:01 - cmdstanpy - INFO - Chain [1] start processing
19:11:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:11:02 - cmdstanpy - INFO - Chain [1] start processing
19:11:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:11:02 - cmdstanpy - INFO - Chain [1] start processing
19:11:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:11:03 - cmdstanpy - INFO - Chain [1] start processing
19:11:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

19:11:04 - cmdstanpy - INFO - Chain [1] start processing
19:11:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:11:04 - cmdstanpy - INFO - Chain [1] start processing
19:11:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:11:05 - cmdstanpy - INFO - Chain [1] start processing
19:11:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:11:05 - cmdstanpy - INFO - Chain [1] start processing
19:11:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:11:06 - cmdstanpy - INFO - Chain [1] start processing
19:11:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:11:07 - cmdstanpy - INFO - Chain [1] start processing
19:11:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:11:07 - cmdstanpy - INFO - Chain [1] start processing
19:11:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:11:08 - cmdstanpy - INFO - Chain [1] start processing
19:11:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:11:08 - cmdstanpy - INFO - Chain [1] start processing
19:11:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:11:09 - cmdstanpy - INFO - Chain [1] start processing
19:11:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:11:10 - cmdstanpy - INFO - Chain [1] start processing
19:11:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:11:10 - cmdstanpy - INFO - Chain [1] start processing
19:11:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:11:11 - cmdstanpy - INFO - Chain [1] start processing
19:11:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:11:11 - cmdstanpy - INFO - Chain [1] start processing
19:11:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:11:12 - cmdstanpy - INFO - Chain [1] start processing
19:11:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:11:13 - cmdstanpy - INFO - Chain [1] start processing
19:11:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:11:13 - cmdstanpy - INFO - Chain [1] start processing
19:11:13 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 7 / 10....

19:11:14 - cmdstanpy - INFO - Chain [1] start processing
19:11:15 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:11:16 - cmdstanpy - INFO - Chain [1] start processing
19:11:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

19:11:16 - cmdstanpy - INFO - Chain [1] start processing
19:11:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

19:11:17 - cmdstanpy - INFO - Chain [1] start processing
19:11:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:11:17 - cmdstanpy - INFO - Chain [1] start processing
19:11:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:11:17 - cmdstanpy - INFO - Chain [1] start processing
19:11:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

19:11:18 - cmdstanpy - INFO - Chain [1] start processing
19:11:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

19:11:18 - cmdstanpy - INFO - Chain [1] start processing
19:11:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:11:19 - cmdstanpy - INFO - Chain [1] start processing
19:11:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

19:11:19 - cmdstanpy - INFO - Chain [1] start processing
19:11:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

19:11:19 - cmdstanpy - INFO - Chain [1] start processing
19:11:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:11:20 - cmdstanpy - INFO - Chain [1] start processing
19:11:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:11:20 - cmdstanpy - INFO - Chain [1] start processing
19:11:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

19:11:21 - cmdstanpy - INFO - Chain [1] start processing
19:11:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

19:11:21 - cmdstanpy - INFO - Chain [1] start processing
19:11:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

19:11:21 - cmdstanpy - INFO - Chain [1] start processing
19:11:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:11:22 - cmdstanpy - INFO - Chain [1] start processing
19:11:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

19:11:22 - cmdstanpy - INFO - Chain [1] start processing
19:11:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:11:23 - cmdstanpy - INFO - Chain [1] start processing
19:11:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

19:11:23 - cmdstanpy - INFO - Chain [1] start processing
19:11:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:11:24 - cmdstanpy - INFO - Chain [1] start processing
19:11:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

19:11:24 - cmdstanpy - INFO - Chain [1] start processing
19:11:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

19:11:24 - cmdstanpy - INFO - Chain [1] start processing
19:11:25 - cmdstanpy - INFO - Chain [1] done processing
19:11:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  24  out of  100

19:11:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

19:11:25 - cmdstanpy - INFO - Chain [1] start processing
19:11:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:11:26 - cmdstanpy - INFO - Chain [1] start processing
19:11:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

19:11:26 - cmdstanpy - INFO - Chain [1] start processing
19:11:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:11:26 - cmdstanpy - INFO - Chain [1] start processing
19:11:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:11:27 - cmdstanpy - INFO - Chain [1] start processing
19:11:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

19:11:27 - cmdstanpy - INFO - Chain [1] start processing
19:11:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

19:11:28 - cmdstanpy - INFO - Chain [1] start processing
19:11:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:11:28 - cmdstanpy - INFO - Chain [1] start processing
19:11:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:11:29 - cmdstanpy - INFO - Chain [1] start processing
19:11:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:11:29 - cmdstanpy - INFO - Chain [1] start processing
19:11:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:11:30 - cmdstanpy - INFO - Chain [1] start processing
19:11:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

19:11:30 - cmdstanpy - INFO - Chain [1] start processing
19:11:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

19:11:30 - cmdstanpy - INFO - Chain [1] start processing
19:11:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

19:11:31 - cmdstanpy - INFO - Chain [1] start processing
19:11:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:11:31 - cmdstanpy - INFO - Chain [1] start processing
19:11:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

19:11:32 - cmdstanpy - INFO - Chain [1] start processing
19:11:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

19:11:32 - cmdstanpy - INFO - Chain [1] start processing
19:11:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

19:11:33 - cmdstanpy - INFO - Chain [1] start processing
19:11:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

19:11:33 - cmdstanpy - INFO - Chain [1] start processing
19:11:33 - cmdstanpy - INFO - Chain [1] done processing
19:11:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  44  out of  100

19:11:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:11:34 - cmdstanpy - INFO - Chain [1] start processing
19:11:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:11:34 - cmdstanpy - INFO - Chain [1] start processing
19:11:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:11:35 - cmdstanpy - INFO - Chain [1] start processing
19:11:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:11:35 - cmdstanpy - INFO - Chain [1] start processing
19:11:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:11:35 - cmdstanpy - INFO - Chain [1] start processing
19:11:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:11:36 - cmdstanpy - INFO - Chain [1] start processing
19:11:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:11:36 - cmdstanpy - INFO - Chain [1] start processing
19:11:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:11:37 - cmdstanpy - INFO - Chain [1] start processing
19:11:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

19:11:37 - cmdstanpy - INFO - Chain [1] start processing
19:11:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

19:11:38 - cmdstanpy - INFO - Chain [1] start processing
19:11:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:11:38 - cmdstanpy - INFO - Chain [1] start processing
19:11:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

19:11:39 - cmdstanpy - INFO - Chain [1] start processing
19:11:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:11:39 - cmdstanpy - INFO - Chain [1] start processing
19:11:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:11:40 - cmdstanpy - INFO - Chain [1] start processing
19:11:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:11:40 - cmdstanpy - INFO - Chain [1] start processing
19:11:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:11:41 - cmdstanpy - INFO - Chain [1] start processing
19:11:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

19:11:41 - cmdstanpy - INFO - Chain [1] start processing
19:11:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:11:41 - cmdstanpy - INFO - Chain [1] start processing
19:11:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:11:42 - cmdstanpy - INFO - Chain [1] start processing
19:11:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:11:42 - cmdstanpy - INFO - Chain [1] start processing
19:11:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:11:43 - cmdstanpy - INFO - Chain [1] start processing
19:11:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

19:11:43 - cmdstanpy - INFO - Chain [1] start processing
19:11:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:11:44 - cmdstanpy - INFO - Chain [1] start processing
19:11:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:11:44 - cmdstanpy - INFO - Chain [1] start processing
19:11:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:11:45 - cmdstanpy - INFO - Chain [1] start processing
19:11:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:11:45 - cmdstanpy - INFO - Chain [1] start processing
19:11:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:11:46 - cmdstanpy - INFO - Chain [1] start processing
19:11:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:11:46 - cmdstanpy - INFO - Chain [1] start processing
19:11:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:11:47 - cmdstanpy - INFO - Chain [1] start processing
19:11:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

19:11:47 - cmdstanpy - INFO - Chain [1] start processing
19:11:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:11:47 - cmdstanpy - INFO - Chain [1] start processing
19:11:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:11:48 - cmdstanpy - INFO - Chain [1] start processing
19:11:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:11:48 - cmdstanpy - INFO - Chain [1] start processing
19:11:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:11:49 - cmdstanpy - INFO - Chain [1] start processing
19:11:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:11:49 - cmdstanpy - INFO - Chain [1] start processing
19:11:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:11:50 - cmdstanpy - INFO - Chain [1] start processing
19:11:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:11:50 - cmdstanpy - INFO - Chain [1] start processing
19:11:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:11:51 - cmdstanpy - INFO - Chain [1] start processing
19:11:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:11:51 - cmdstanpy - INFO - Chain [1] start processing
19:11:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

19:11:52 - cmdstanpy - INFO - Chain [1] start processing
19:11:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:11:52 - cmdstanpy - INFO - Chain [1] start processing
19:11:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:11:53 - cmdstanpy - INFO - Chain [1] start processing
19:11:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:11:53 - cmdstanpy - INFO - Chain [1] start processing
19:11:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:11:54 - cmdstanpy - INFO - Chain [1] start processing
19:11:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:11:54 - cmdstanpy - INFO - Chain [1] start processing
19:11:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:11:55 - cmdstanpy - INFO - Chain [1] start processing
19:11:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:11:55 - cmdstanpy - INFO - Chain [1] start processing
19:11:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:11:56 - cmdstanpy - INFO - Chain [1] start processing
19:11:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:11:56 - cmdstanpy - INFO - Chain [1] start processing
19:11:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:11:57 - cmdstanpy - INFO - Chain [1] start processing
19:11:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:11:57 - cmdstanpy - INFO - Chain [1] start processing
19:11:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:11:57 - cmdstanpy - INFO - Chain [1] start processing
19:11:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:11:58 - cmdstanpy - INFO - Chain [1] start processing
19:11:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:11:59 - cmdstanpy - INFO - Chain [1] start processing
19:11:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:11:59 - cmdstanpy - INFO - Chain [1] start processing
19:11:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:12:00 - cmdstanpy - INFO - Chain [1] start processing
19:12:00 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 8 / 10....

19:12:00 - cmdstanpy - INFO - Chain [1] start processing
19:12:01 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

19:12:01 - cmdstanpy - INFO - Chain [1] start processing
19:12:01 - cmdstanpy - INFO - Chain [1] done processing
19:12:02 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  3  out of  100

19:12:02 - cmdstanpy - INFO - Chain [1] done processing
19:12:02 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  4  out of  100

19:12:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

19:12:02 - cmdstanpy - INFO - Chain [1] start processing
19:12:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

19:12:03 - cmdstanpy - INFO - Chain [1] start processing
19:12:03 - cmdstanpy - INFO - Chain [1] done processing
19:12:03 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  7  out of  100

19:12:03 - cmdstanpy - INFO - Chain [1] done processing
19:12:03 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  8  out of  100

19:12:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

19:12:04 - cmdstanpy - INFO - Chain [1] start processing
19:12:04 - cmdstanpy - INFO - Chain [1] done processing
19:12:04 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  10  out of  100

19:12:04 - cmdstanpy - INFO - Chain [1] done processing
19:12:04 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  11  out of  100

19:12:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

19:12:05 - cmdstanpy - INFO - Chain [1] start processing
19:12:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

19:12:05 - cmdstanpy - INFO - Chain [1] start processing
19:12:05 - cmdstanpy - INFO - Chain [1] done processing
19:12:06 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  14  out of  100

19:12:06 - cmdstanpy - INFO - Chain [1] done processing
19:12:06 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  15  out of  100

19:12:06 - cmdstanpy - INFO - Chain [1] done processing
19:12:06 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  16  out of  100

19:12:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

19:12:07 - cmdstanpy - INFO - Chain [1] start processing
19:12:07 - cmdstanpy - INFO - Chain [1] done processing
19:12:07 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  18  out of  100

19:12:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

19:12:07 - cmdstanpy - INFO - Chain [1] start processing
19:12:08 - cmdstanpy - INFO - Chain [1] done processing
19:12:08 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  20  out of  100

19:12:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

19:12:08 - cmdstanpy - INFO - Chain [1] start processing
19:12:08 - cmdstanpy - INFO - Chain [1] done processing
19:12:09 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  22  out of  100

19:12:09 - cmdstanpy - INFO - Chain [1] done processing
19:12:09 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  23  out of  100

19:12:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

19:12:09 - cmdstanpy - INFO - Chain [1] start processing
19:12:09 - cmdstanpy - INFO - Chain [1] done processing
19:12:10 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  25  out of  100

19:12:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

19:12:10 - cmdstanpy - INFO - Chain [1] start processing
19:12:10 - cmdstanpy - INFO - Chain [1] done processing
19:12:10 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  27  out of  100

19:12:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

19:12:11 - cmdstanpy - INFO - Chain [1] start processing
19:12:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

19:12:11 - cmdstanpy - INFO - Chain [1] start processing
19:12:11 - cmdstanpy - INFO - Chain [1] done processing
19:12:12 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  30  out of  100

19:12:12 - cmdstanpy - INFO - Chain [1] done processing
19:12:12 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  31  out of  100

19:12:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

19:12:12 - cmdstanpy - INFO - Chain [1] start processing
19:12:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

19:12:13 - cmdstanpy - INFO - Chain [1] start processing
19:12:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

19:12:13 - cmdstanpy - INFO - Chain [1] start processing
19:12:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

19:12:14 - cmdstanpy - INFO - Chain [1] start processing
19:12:14 - cmdstanpy - INFO - Chain [1] done processing
19:12:14 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  36  out of  100

19:12:14 - cmdstanpy - INFO - Chain [1] done processing
19:12:14 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  37  out of  100

19:12:14 - cmdstanpy - INFO - Chain [1] done processing
19:12:14 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  38  out of  100

19:12:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

19:12:15 - cmdstanpy - INFO - Chain [1] start processing
19:12:15 - cmdstanpy - INFO - Chain [1] done processing
19:12:15 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  40  out of  100

19:12:15 - cmdstanpy - INFO - Chain [1] done processing
19:12:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  41  out of  100

19:12:16 - cmdstanpy - INFO - Chain [1] done processing
19:12:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  42  out of  100

19:12:16 - cmdstanpy - INFO - Chain [1] done processing
19:12:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  43  out of  100

19:12:16 - cmdstanpy - INFO - Chain [1] done processing
19:12:17 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  44  out of  100

19:12:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

19:12:17 - cmdstanpy - INFO - Chain [1] start processing
19:12:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

19:12:17 - cmdstanpy - INFO - Chain [1] start processing
19:12:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:12:18 - cmdstanpy - INFO - Chain [1] start processing
19:12:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

19:12:18 - cmdstanpy - INFO - Chain [1] start processing
19:12:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

19:12:19 - cmdstanpy - INFO - Chain [1] start processing
19:12:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

19:12:19 - cmdstanpy - INFO - Chain [1] start processing
19:12:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

19:12:19 - cmdstanpy - INFO - Chain [1] start processing
19:12:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

19:12:20 - cmdstanpy - INFO - Chain [1] start processing
19:12:20 - cmdstanpy - INFO - Chain [1] done processing
19:12:20 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  53  out of  100

19:12:20 - cmdstanpy - INFO - Chain [1] done processing
19:12:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  54  out of  100

19:12:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

19:12:21 - cmdstanpy - INFO - Chain [1] start processing
19:12:21 - cmdstanpy - INFO - Chain [1] done processing
19:12:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  56  out of  100

19:12:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

19:12:22 - cmdstanpy - INFO - Chain [1] start processing
19:12:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

19:12:22 - cmdstanpy - INFO - Chain [1] start processing
19:12:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

19:12:23 - cmdstanpy - INFO - Chain [1] start processing
19:12:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

19:12:23 - cmdstanpy - INFO - Chain [1] start processing
19:12:23 - cmdstanpy - INFO - Chain [1] done processing
19:12:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  61  out of  100

19:12:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

19:12:24 - cmdstanpy - INFO - Chain [1] start processing
19:12:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

19:12:24 - cmdstanpy - INFO - Chain [1] start processing
19:12:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:12:25 - cmdstanpy - INFO - Chain [1] start processing
19:12:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

19:12:25 - cmdstanpy - INFO - Chain [1] start processing
19:12:25 - cmdstanpy - INFO - Chain [1] done processing
19:12:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  66  out of  100

19:12:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

19:12:26 - cmdstanpy - INFO - Chain [1] start processing
19:12:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

19:12:26 - cmdstanpy - INFO - Chain [1] start processing
19:12:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

19:12:27 - cmdstanpy - INFO - Chain [1] start processing
19:12:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

19:12:27 - cmdstanpy - INFO - Chain [1] start processing
19:12:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

19:12:28 - cmdstanpy - INFO - Chain [1] start processing
19:12:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

19:12:28 - cmdstanpy - INFO - Chain [1] start processing
19:12:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

19:12:28 - cmdstanpy - INFO - Chain [1] start processing
19:12:29 - cmdstanpy - INFO - Chain [1] done processing
19:12:29 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  74  out of  100

19:12:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

19:12:29 - cmdstanpy - INFO - Chain [1] start processing
19:12:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:12:30 - cmdstanpy - INFO - Chain [1] start processing
19:12:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

19:12:30 - cmdstanpy - INFO - Chain [1] start processing
19:12:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

19:12:31 - cmdstanpy - INFO - Chain [1] start processing
19:12:31 - cmdstanpy - INFO - Chain [1] done processing
19:12:31 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  79  out of  100

19:12:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

19:12:32 - cmdstanpy - INFO - Chain [1] start processing
19:12:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:12:32 - cmdstanpy - INFO - Chain [1] start processing
19:12:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

19:12:32 - cmdstanpy - INFO - Chain [1] start processing
19:12:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

19:12:33 - cmdstanpy - INFO - Chain [1] start processing
19:12:33 - cmdstanpy - INFO - Chain [1] done processing
19:12:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  84  out of  100

19:12:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

19:12:34 - cmdstanpy - INFO - Chain [1] start processing
19:12:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

19:12:34 - cmdstanpy - INFO - Chain [1] start processing
19:12:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:12:35 - cmdstanpy - INFO - Chain [1] start processing
19:12:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

19:12:35 - cmdstanpy - INFO - Chain [1] start processing
19:12:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

19:12:35 - cmdstanpy - INFO - Chain [1] start processing
19:12:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

19:12:36 - cmdstanpy - INFO - Chain [1] start processing
19:12:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

19:12:36 - cmdstanpy - INFO - Chain [1] start processing
19:12:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

19:12:37 - cmdstanpy - INFO - Chain [1] start processing
19:12:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

19:12:37 - cmdstanpy - INFO - Chain [1] start processing
19:12:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

19:12:38 - cmdstanpy - INFO - Chain [1] start processing
19:12:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:12:38 - cmdstanpy - INFO - Chain [1] start processing
19:12:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

19:12:39 - cmdstanpy - INFO - Chain [1] start processing
19:12:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:12:39 - cmdstanpy - INFO - Chain [1] start processing
19:12:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

19:12:39 - cmdstanpy - INFO - Chain [1] start processing
19:12:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:12:40 - cmdstanpy - INFO - Chain [1] start processing
19:12:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

19:12:40 - cmdstanpy - INFO - Chain [1] start processing
19:12:40 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 9 / 10....

19:12:41 - cmdstanpy - INFO - Chain [1] start processing
19:12:41 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)
19:12:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  1  out of  100
Processing i =  2  out of  100

19:12:41 - cmdstanpy - INFO - Chain [1] done processing
19:12:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  3  out of  100

19:12:42 - cmdstanpy - INFO - Chain [1] done processing
19:12:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  4  out of  100

19:12:42 - cmdstanpy - INFO - Chain [1] done processing
19:12:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  5  out of  100

19:12:42 - cmdstanpy - INFO - Chain [1] done processing
19:12:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  6  out of  100

19:12:42 - cmdstanpy - INFO - Chain [1] done processing
19:12:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  7  out of  100

19:12:43 - cmdstanpy - INFO - Chain [1] done processing
19:12:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  8  out of  100

19:12:43 - cmdstanpy - INFO - Chain [1] done processing
19:12:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  9  out of  100

19:12:43 - cmdstanpy - INFO - Chain [1] done processing
19:12:44 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  10  out of  100

19:12:44 - cmdstanpy - INFO - Chain [1] done processing
19:12:44 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  11  out of  100

19:12:44 - cmdstanpy - INFO - Chain [1] done processing
19:12:44 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  12  out of  100

19:12:44 - cmdstanpy - INFO - Chain [1] done processing
19:12:44 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  13  out of  100

19:12:45 - cmdstanpy - INFO - Chain [1] done processing
19:12:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  14  out of  100

19:12:45 - cmdstanpy - INFO - Chain [1] done processing
19:12:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  15  out of  100

19:12:45 - cmdstanpy - INFO - Chain [1] done processing
19:12:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  16  out of  100

19:12:45 - cmdstanpy - INFO - Chain [1] done processing
19:12:46 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  17  out of  100

19:12:46 - cmdstanpy - INFO - Chain [1] done processing
19:12:46 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  18  out of  100

19:12:46 - cmdstanpy - INFO - Chain [1] done processing
19:12:46 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  19  out of  100

19:12:46 - cmdstanpy - INFO - Chain [1] done processing
19:12:46 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  20  out of  100

19:12:47 - cmdstanpy - INFO - Chain [1] done processing
19:12:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  21  out of  100

19:12:47 - cmdstanpy - INFO - Chain [1] done processing
19:12:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  22  out of  100

19:12:47 - cmdstanpy - INFO - Chain [1] done processing
19:12:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  23  out of  100

19:12:47 - cmdstanpy - INFO - Chain [1] done processing
19:12:48 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  24  out of  100

19:12:48 - cmdstanpy - INFO - Chain [1] done processing
19:12:48 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  25  out of  100

19:12:48 - cmdstanpy - INFO - Chain [1] done processing
19:12:48 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  26  out of  100

19:12:48 - cmdstanpy - INFO - Chain [1] done processing
19:12:48 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  27  out of  100

19:12:49 - cmdstanpy - INFO - Chain [1] done processing
19:12:49 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  28  out of  100

19:12:49 - cmdstanpy - INFO - Chain [1] done processing
19:12:49 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  29  out of  100

19:12:49 - cmdstanpy - INFO - Chain [1] done processing
19:12:49 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  30  out of  100

19:12:50 - cmdstanpy - INFO - Chain [1] done processing
19:12:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  31  out of  100

19:12:50 - cmdstanpy - INFO - Chain [1] done processing
19:12:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  32  out of  100

19:12:50 - cmdstanpy - INFO - Chain [1] done processing
19:12:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  33  out of  100

19:12:51 - cmdstanpy - INFO - Chain [1] done processing
19:12:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  34  out of  100

19:12:51 - cmdstanpy - INFO - Chain [1] done processing
19:12:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  35  out of  100

19:12:51 - cmdstanpy - INFO - Chain [1] done processing
19:12:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  36  out of  100

19:12:51 - cmdstanpy - INFO - Chain [1] done processing
19:12:52 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  37  out of  100

19:12:52 - cmdstanpy - INFO - Chain [1] done processing
19:12:52 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  38  out of  100

19:12:52 - cmdstanpy - INFO - Chain [1] done processing
19:12:52 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  39  out of  100

19:12:52 - cmdstanpy - INFO - Chain [1] done processing
19:12:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  40  out of  100

19:12:53 - cmdstanpy - INFO - Chain [1] done processing
19:12:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  41  out of  100

19:12:53 - cmdstanpy - INFO - Chain [1] done processing
19:12:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  42  out of  100

19:12:53 - cmdstanpy - INFO - Chain [1] done processing
19:12:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  43  out of  100

19:12:54 - cmdstanpy - INFO - Chain [1] done processing
19:12:54 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  44  out of  100

19:12:54 - cmdstanpy - INFO - Chain [1] done processing
19:12:54 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  45  out of  100

19:12:54 - cmdstanpy - INFO - Chain [1] done processing
19:12:54 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  46  out of  100

19:12:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

19:12:55 - cmdstanpy - INFO - Chain [1] start processing
19:12:55 - cmdstanpy - INFO - Chain [1] done processing
19:12:55 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  48  out of  100

19:12:55 - cmdstanpy - INFO - Chain [1] done processing
19:12:55 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  49  out of  100

19:12:55 - cmdstanpy - INFO - Chain [1] done processing
19:12:56 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  50  out of  100

19:12:56 - cmdstanpy - INFO - Chain [1] done processing
19:12:56 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  51  out of  100

19:12:56 - cmdstanpy - INFO - Chain [1] done processing
19:12:56 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  52  out of  100

19:12:56 - cmdstanpy - INFO - Chain [1] done processing
19:12:56 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  53  out of  100

19:12:57 - cmdstanpy - INFO - Chain [1] done processing
19:12:57 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  54  out of  100

19:12:57 - cmdstanpy - INFO - Chain [1] done processing
19:12:57 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  55  out of  100

19:12:57 - cmdstanpy - INFO - Chain [1] done processing
19:12:57 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  56  out of  100

19:12:58 - cmdstanpy - INFO - Chain [1] done processing
19:12:58 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  57  out of  100

19:12:58 - cmdstanpy - INFO - Chain [1] done processing
19:12:58 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  58  out of  100

19:12:58 - cmdstanpy - INFO - Chain [1] done processing
19:12:58 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  59  out of  100

19:12:59 - cmdstanpy - INFO - Chain [1] done processing
19:12:59 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  60  out of  100

19:12:59 - cmdstanpy - INFO - Chain [1] done processing
19:12:59 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  61  out of  100

19:12:59 - cmdstanpy - INFO - Chain [1] done processing
19:12:59 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  62  out of  100

19:13:00 - cmdstanpy - INFO - Chain [1] done processing
19:13:00 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  63  out of  100

19:13:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

19:13:00 - cmdstanpy - INFO - Chain [1] start processing
19:13:00 - cmdstanpy - INFO - Chain [1] done processing
19:13:00 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  65  out of  100

19:13:01 - cmdstanpy - INFO - Chain [1] done processing
19:13:01 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  66  out of  100

19:13:01 - cmdstanpy - INFO - Chain [1] done processing
19:13:01 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  67  out of  100

19:13:01 - cmdstanpy - INFO - Chain [1] done processing
19:13:01 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  68  out of  100

19:13:01 - cmdstanpy - INFO - Chain [1] done processing
19:13:02 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  69  out of  100

19:13:02 - cmdstanpy - INFO - Chain [1] done processing
19:13:02 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  70  out of  100

19:13:02 - cmdstanpy - INFO - Chain [1] done processing
19:13:02 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  71  out of  100

19:13:03 - cmdstanpy - INFO - Chain [1] done processing
19:13:03 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  72  out of  100

19:13:03 - cmdstanpy - INFO - Chain [1] done processing
19:13:03 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  73  out of  100

19:13:03 - cmdstanpy - INFO - Chain [1] done processing
19:13:03 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  74  out of  100

19:13:04 - cmdstanpy - INFO - Chain [1] done processing
19:13:04 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  75  out of  100

19:13:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

19:13:04 - cmdstanpy - INFO - Chain [1] start processing
19:13:04 - cmdstanpy - INFO - Chain [1] done processing
19:13:04 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  77  out of  100

19:13:04 - cmdstanpy - INFO - Chain [1] done processing
19:13:05 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  78  out of  100

19:13:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

19:13:05 - cmdstanpy - INFO - Chain [1] start processing
19:13:05 - cmdstanpy - INFO - Chain [1] done processing
19:13:05 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  80  out of  100

19:13:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

19:13:06 - cmdstanpy - INFO - Chain [1] start processing
19:13:06 - cmdstanpy - INFO - Chain [1] done processing
19:13:06 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  82  out of  100

19:13:06 - cmdstanpy - INFO - Chain [1] done processing
19:13:06 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  83  out of  100

19:13:07 - cmdstanpy - INFO - Chain [1] done processing
19:13:07 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  84  out of  100

19:13:07 - cmdstanpy - INFO - Chain [1] done processing
19:13:07 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  85  out of  100

19:13:07 - cmdstanpy - INFO - Chain [1] done processing
19:13:08 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  86  out of  100

19:13:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

19:13:08 - cmdstanpy - INFO - Chain [1] start processing
19:13:08 - cmdstanpy - INFO - Chain [1] done processing
19:13:08 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  88  out of  100

19:13:08 - cmdstanpy - INFO - Chain [1] done processing
19:13:09 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  89  out of  100

19:13:09 - cmdstanpy - INFO - Chain [1] done processing
19:13:09 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  90  out of  100

19:13:09 - cmdstanpy - INFO - Chain [1] done processing
19:13:09 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  91  out of  100

19:13:09 - cmdstanpy - INFO - Chain [1] done processing
19:13:09 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  92  out of  100

19:13:10 - cmdstanpy - INFO - Chain [1] done processing
19:13:10 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  93  out of  100

19:13:10 - cmdstanpy - INFO - Chain [1] done processing
19:13:10 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  94  out of  100

19:13:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

19:13:10 - cmdstanpy - INFO - Chain [1] start processing
19:13:11 - cmdstanpy - INFO - Chain [1] done processing
19:13:11 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  96  out of  100

19:13:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

19:13:11 - cmdstanpy - INFO - Chain [1] start processing
19:13:11 - cmdstanpy - INFO - Chain [1] done processing
19:13:12 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  98  out of  100

19:13:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

19:13:12 - cmdstanpy - INFO - Chain [1] start processing
19:13:12 - cmdstanpy - INFO - Chain [1] done processing
19:13:12 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  100  out of  100

19:13:12 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 10 / 10....

19:13:13 - cmdstanpy - INFO - Chain [1] start processing
19:13:15 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)

Test set is before train set / CV 10, no test forecast can be made

[run 12/36] ds16 m4 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Processing i =  1  out of  1344
Processing i =  2  out of  1344
Processing i =  3  out of  1344
Processing i =  4  out of  1344
Processing i =  5  out of  1344
Processing i =  6  out of  1344
Processing i =  7  out of  1344
Processing i =  8  out of  1344
Processing i =  9  out of  1344
Processing i =  10  out of  1344
Processing i =  11  out of  1344
Processing i =  12  out of  1344
Processing i =  13  out of  1344
Processing i =  14  out of  1344
Processing i =  15  out of  1344
Processing i =  16  out of  1344
Processing i =  17  out of  1344
Processing i =  18  out of  1344
Processing i =  19  out of  1344
Processing i =  20  out of  1344
Processing i =  21  out of  1344
Processing i =  22  out of  1344
Processing i =  23  out of  1344
Processing i =  24  out of  1344
Processing i =  25  out of  1344
Processing i =  26  out of  1344
Processing i =  27  out of  1344
Processing i =  28  out of  1344
Processing i =  29  out of  1344
Processing i =  30  out of  1344
Processing i =  31  out of  1344
Processing i =  32  out of  1344
Processing i =  33  out of  1344
Processing i =  34  out of  1344
Processing i =  35  out of  1344
Processing i =  36  out of  1344
Processing i =  37  out of  1344
Processing i =  38  out of  1344
Processing i =  39  out of  1344
Processing i =  40  out of  1344
Processing i =  41  out of  1344
Processing i =  42  out of  1344
Processing i =  43  out of  1344
Processing i =  44  out of  1344
Processing i =  45  out of  1344
Processing i =  46  out of  1344
Processing i =  47  out of  1344
Processing i =  48  out of  1344
Processing i =  49  out of  1344
Processing i =  50  out of  1344
Processing i =  51  out of  1344
Processing i =  52  out of  1344
Processing i =  53  out of  1344
Processing i =  54  out of  1344
Processing i =  55  out of  1344
Processing i =  56  out of  1344
Processing i =  57  out of  1344
Processing i =  58  out of  1344
Processing i =  59  out of  1344
Processing i =  60  out of  1344
Processing i =  61  out of  1344
Processing i =  62  out of  1344
Processing i =  63  out of  1344
Processing i =  64  out of  1344
Processing i =  65  out of  1344
Processing i =  66  out of  1344
Processing i =  67  out of  1344
Processing i =  68  out of  1344
Processing i =  69  out of  1344
Processing i =  70  out of  1344
Processing i =  71  out of  1344
Processing i =  72  out of  1344
Processing i =  73  out of  1344
Processing i =  74  out of  1344
Processing i =  75  out of  1344
Processing i =  76  out of  1344
Processing i =  77  out of  1344
Processing i =  78  out of  1344
Processing i =  79  out of  1344
Processing i =  80  out of  1344
Processing i =  81  out of  1344
Processing i =  82  out of  1344
Processing i =  83  out of  1344
Processing i =  84  out of  1344
Processing i =  85  out of  1344
Processing i =  86  out of  1344
Processing i =  87  out of  1344
Processing i =  88  out of  1344
Processing i =  89  out of  1344
Processing i =  90  out of  1344
Processing i =  91  out of  1344
Processing i =  92  out of  1344
Processing i =  93  out of  1344
Processing i =  94  out of  1344
Processing i =  95  out of  1344
Processing i =  96  out of  1344
Processing i =  97  out of  1344
Processing i =  98  out of  1344
Processing i =  99  out of  1344
Processing i =  100  out of  1344
Processing i =  101  out of  1344
Processing i =  102  out of  1344
Processing i =  103  out of  1344
Processing i =  104  out of  1344
Processing i =  105  out of  1344
Processing i =  106  out of  1344
Processing i =  107  out of  1344
Processing i =  108  out of  1344
Processing i =  109  out of  1344
Processing i =  110  out of  1344
Processing i =  111  out of  1344
Processing i =  112  out of  1344
Processing i =  113  out of  1344
Processing i =  114  out of  1344
Processing i =  115  out of  1344
Processing i =  116  out of  1344
Processing i =  117  out of  1344
Processing i =  118  out of  1344
Processing i =  119  out of  1344
Processing i =  120  out of  1344
Processing i =  121  out of  1344
Processing i =  122  out of  1344
Processing i =  123  out of  1344
Processing i =  124  out of  1344
Processing i =  125  out of  1344
Processing i =  126  out of  1344
Processing i =  127  out of  1344
Processing i =  128  out of  1344
Processing i =  129  out of  1344
Processing i =  130  out of  1344
Processing i =  131  out of  1344
Processing i =  132  out of  1344
Processing i =  133  out of  1344
Processing i =  134  out of  1344
Processing i =  135  out of  1344
Processing i =  136  out of  1344
Processing i =  137  out of  1344
Processing i =  138  out of  1344
Processing i =  139  out of  1344
Processing i =  140  out of  1344
Processing i =  141  out of  1344
Processing i =  142  out of  1344
Processing i =  143  out of  1344
Processing i =  144  out of  1344
Processing i =  145  out of  1344
Processing i =  146  out of  1344
Processing i =  147  out of  1344
Processing i =  148  out of  1344
Processing i =  149  out of  1344
Processing i =  150  out of  1344
Processing i =  151  out of  1344
Processing i =  152  out of  1344
Processing i =  153  out of  1344
Processing i =  154  out of  1344
Processing i =  155  out of  1344
Processing i =  156  out of  1344
Processing i =  157  out of  1344
Processing i =  158  out of  1344
Processing i =  159  out of  1344
Processing i =  160  out of  1344
Processing i =  161  out of  1344
Processing i =  162  out of  1344
Processing i =  163  out of  1344
Processing i =  164  out of  1344
Processing i =  165  out of  1344
Processing i =  166  out of  1344
Processing i =  167  out of  1344
Processing i =  168  out of  1344
Processing i =  169  out of  1344
Processing i =  170  out of  1344
Processing i =  171  out of  1344
Processing i =  172  out of  1344
Processing i =  173  out of  1344
Processing i =  174  out of  1344
Processing i =  175  out of  1344
Processing i =  176  out of  1344
Processing i =  177  out of  1344
Processing i =  178  out of  1344
Processing i =  179  out of  1344
Processing i =  180  out of  1344
Processing i =  181  out of  1344
Processing i =  182  out of  1344
Processing i =  183  out of  1344
Processing i =  184  out of  1344
Processing i =  185  out of  1344
Processing i =  186  out of  1344
Processing i =  187  out of  1344
Processing i =  188  out of  1344
Processing i =  189  out of  1344
Processing i =  190  out of  1344
Processing i =  191  out of  1344
Processing i =  192  out of  1344
Processing i =  193  out of  1344
Processing i =  194  out of  1344
Processing i =  195  out of  1344
Processing i =  196  out of  1344
Processing i =  197  out of  1344
Processing i =  198  out of  1344
Processing i =  199  out of  1344
Processing i =  200  out of  1344
Processing i =  201  out of  1344
Processing i =  202  out of  1344
Processing i =  203  out of  1344
Processing i =  204  out of  1344
Processing i =  205  out of  1344
Processing i =  206  out of  1344
Processing i =  207  out of  1344
Processing i =  208  out of  1344
Processing i =  209  out of  1344
Processing i =  210  out of  1344
Processing i =  211  out of  1344
Processing i =  212  out of  1344
Processing i =  213  out of  1344
Processing i =  214  out of  1344
Processing i =  215  out of  1344
Processing i =  216  out of  1344
Processing i =  217  out of  1344
Processing i =  218  out of  1344
Processing i =  219  out of  1344
Processing i =  220  out of  1344
Processing i =  221  out of  1344
Processing i =  222  out of  1344
Processing i =  223  out of  1344
Processing i =  224  out of  1344
Processing i =  225  out of  1344
Processing i =  226  out of  1344
Processing i =  227  out of  1344
Processing i =  228  out of  1344
Processing i =  229  out of  1344
Processing i =  230  out of  1344
Processing i =  231  out of  1344
Processing i =  232  out of  1344
Processing i =  233  out of  1344
Processing i =  234  out of  1344
Processing i =  235  out of  1344
Processing i =  236  out of  1344
Processing i =  237  out of  1344
Processing i =  238  out of  1344
Processing i =  239  out of  1344
Processing i =  240  out of  1344
Processing i =  241  out of  1344
Processing i =  242  out of  1344
Processing i =  243  out of  1344
Processing i =  244  out of  1344
Processing i =  245  out of  1344
Processing i =  246  out of  1344
Processing i =  247  out of  1344
Processing i =  248  out of  1344
Processing i =  249  out of  1344
Processing i =  250  out of  1344
Processing i =  251  out of  1344
Processing i =  252  out of  1344
Processing i =  253  out of  1344
Processing i =  254  out of  1344
Processing i =  255  out of  1344
Processing i =  256  out of  1344
Processing i =  257  out of  1344
Processing i =  258  out of  1344
Processing i =  259  out of  1344
Processing i =  260  out of  1344
Processing i =  261  out of  1344
Processing i =  262  out of  1344
Processing i =  263  out of  1344
Processing i =  264  out of  1344
Processing i =  265  out of  1344
Processing i =  266  out of  1344
Processing i =  267  out of  1344
Processing i =  268  out of  1344
Processing i =  269  out of  1344
Processing i =  270  out of  1344
Processing i =  271  out of  1344
Processing i =  272  out of  1344
Processing i =  273  out of  1344
Processing i =  274  out of  1344
Processing i =  275  out of  1344
Processing i =  276  out of  1344
Processing i =  277  out of  1344
Processing i =  278  out of  1344
Processing i =  279  out of  1344
Processing i =  280  out of  1344
Processing i =  281  out of  1344
Processing i =  282  out of  1344
Processing i =  283  out of  1344
Processing i =  284  out of  1344
Processing i =  285  out of  1344
Processing i =  286  out of  1344
Processing i =  287  out of  1344
Processing i =  288  out of  1344
Processing i =  289  out of  1344
Processing i =  290  out of  1344
Processing i =  291  out of  1344
Processing i =  292  out of  1344
Processing i =  293  out of  1344
Processing i =  294  out of  1344
Processing i =  295  out of  1344
Processing i =  296  out of  1344
Processing i =  297  out of  1344
Processing i =  298  out of  1344
Processing i =  299  out of  1344
Processing i =  300  out of  1344
Processing i =  301  out of  1344
Processing i =  302  out of  1344
Processing i =  303  out of  1344
Processing i =  304  out of  1344
Processing i =  305  out of  1344
Processing i =  306  out of  1344
Processing i =  307  out of  1344
Processing i =  308  out of  1344
Processing i =  309  out of  1344
Processing i =  310  out of  1344
Processing i =  311  out of  1344
Processing i =  312  out of  1344
Processing i =  313  out of  1344
Processing i =  314  out of  1344
Processing i =  315  out of  1344
Processing i =  316  out of  1344
Processing i =  317  out of  1344
Processing i =  318  out of  1344
Processing i =  319  out of  1344
Processing i =  320  out of  1344
Processing i =  321  out of  1344
Processing i =  322  out of  1344
Processing i =  323  out of  1344
Processing i =  324  out of  1344
Processing i =  325  out of  1344
Processing i =  326  out of  1344
Processing i =  327  out of  1344
Processing i =  328  out of  1344
Processing i =  329  out of  1344
Processing i =  330  out of  1344
Processing i =  331  out of  1344
Processing i =  332  out of  1344
Processing i =  333  out of  1344
Processing i =  334  out of  1344
Processing i =  335  out of  1344
Processing i =  336  out of  1344
Processing i =  337  out of  1344
Processing i =  338  out of  1344
Processing i =  339  out of  1344
Processing i =  340  out of  1344
Processing i =  341  out of  1344
Processing i =  342  out of  1344
Processing i =  343  out of  1344
Processing i =  344  out of  1344
Processing i =  345  out of  1344
Processing i =  346  out of  1344
Processing i =  347  out of  1344
Processing i =  348  out of  1344
Processing i =  349  out of  1344
Processing i =  350  out of  1344
Processing i =  351  out of  1344
Processing i =  352  out of  1344
Processing i =  353  out of  1344
Processing i =  354  out of  1344
Processing i =  355  out of  1344
Processing i =  356  out of  1344
Processing i =  357  out of  1344
Processing i =  358  out of  1344
Processing i =  359  out of  1344
Processing i =  360  out of  1344
Processing i =  361  out of  1344
Processing i =  362  out of  1344
Processing i =  363  out of  1344
Processing i =  364  out of  1344
Processing i =  365  out of  1344
Processing i =  366  out of  1344
Processing i =  367  out of  1344
Processing i =  368  out of  1344
Processing i =  369  out of  1344
Processing i =  370  out of  1344
Processing i =  371  out of  1344
Processing i =  372  out of  1344
Processing i =  373  out of  1344
Processing i =  374  out of  1344
Processing i =  375  out of  1344
Processing i =  376  out of  1344
Processing i =  377  out of  1344
Processing i =  378  out of  1344
Processing i =  379  out of  1344
Processing i =  380  out of  1344
Processing i =  381  out of  1344
Processing i =  382  out of  1344
Processing i =  383  out of  1344
Processing i =  384  out of  1344
Processing i =  385  out of  1344
Processing i =  386  out of  1344
Processing i =  387  out of  1344
Processing i =  388  out of  1344
Processing i =  389  out of  1344
Processing i =  390  out of  1344
Processing i =  391  out of  1344
Processing i =  392  out of  1344
Processing i =  393  out of  1344
Processing i =  394  out of  1344
Processing i =  395  out of  1344
Processing i =  396  out of  1344
Processing i =  397  out of  1344
Processing i =  398  out of  1344
Processing i =  399  out of  1344
Processing i =  400  out of  1344
Processing i =  401  out of  1344
Processing i =  402  out of  1344
Processing i =  403  out of  1344
Processing i =  404  out of  1344
Processing i =  405  out of  1344
Processing i =  406  out of  1344
Processing i =  407  out of  1344
Processing i =  408  out of  1344
Processing i =  409  out of  1344
Processing i =  410  out of  1344
Processing i =  411  out of  1344
Processing i =  412  out of  1344
Processing i =  413  out of  1344
Processing i =  414  out of  1344
Processing i =  415  out of  1344
Processing i =  416  out of  1344
Processing i =  417  out of  1344
Processing i =  418  out of  1344
Processing i =  419  out of  1344
Processing i =  420  out of  1344
Processing i =  421  out of  1344
Processing i =  422  out of  1344
Processing i =  423  out of  1344
Processing i =  424  out of  1344
Processing i =  425  out of  1344
Processing i =  426  out of  1344
Processing i =  427  out of  1344
Processing i =  428  out of  1344
Processing i =  429  out of  1344
Processing i =  430  out of  1344
Processing i =  431  out of  1344
Processing i =  432  out of  1344
Processing i =  433  out of  1344
Processing i =  434  out of  1344
Processing i =  435  out of  1344
Processing i =  436  out of  1344
Processing i =  437  out of  1344
Processing i =  438  out of  1344
Processing i =  439  out of  1344
Processing i =  440  out of  1344
Processing i =  441  out of  1344
Processing i =  442  out of  1344
Processing i =  443  out of  1344
Processing i =  444  out of  1344
Processing i =  445  out of  1344
Processing i =  446  out of  1344
Processing i =  447  out of  1344
Processing i =  448  out of  1344
Processing i =  449  out of  1344
Processing i =  450  out of  1344
Processing i =  451  out of  1344
Processing i =  452  out of  1344
Processing i =  453  out of  1344
Processing i =  454  out of  1344
Processing i =  455  out of  1344
Processing i =  456  out of  1344
Processing i =  457  out of  1344
Processing i =  458  out of  1344
Processing i =  459  out of  1344
Processing i =  460  out of  1344
Processing i =  461  out of  1344
Processing i =  462  out of  1344
Processing i =  463  out of  1344
Processing i =  464  out of  1344
Processing i =  465  out of  1344
Processing i =  466  out of  1344
Processing i =  467  out of  1344
Processing i =  468  out of  1344
Processing i =  469  out of  1344
Processing i =  470  out of  1344
Processing i =  471  out of  1344
Processing i =  472  out of  1344
Processing i =  473  out of  1344
Processing i =  474  out of  1344
Processing i =  475  out of  1344
Processing i =  476  out of  1344
Processing i =  477  out of  1344
Processing i =  478  out of  1344
Processing i =  479  out of  1344
Processing i =  480  out of  1344
Processing i =  481  out of  1344
Processing i =  482  out of  1344
Processing i =  483  out of  1344
Processing i =  484  out of  1344
Processing i =  485  out of  1344
Processing i =  486  out of  1344
Processing i =  487  out of  1344
Processing i =  488  out of  1344
Processing i =  489  out of  1344
Processing i =  490  out of  1344
Processing i =  491  out of  1344
Processing i =  492  out of  1344
Processing i =  493  out of  1344
Processing i =  494  out of  1344
Processing i =  495  out of  1344
Processing i =  496  out of  1344
Processing i =  497  out of  1344
Processing i =  498  out of  1344
Processing i =  499  out of  1344
Processing i =  500  out of  1344
Processing i =  501  out of  1344
Processing i =  502  out of  1344
Processing i =  503  out of  1344
Processing i =  504  out of  1344
Processing i =  505  out of  1344
Processing i =  506  out of  1344
Processing i =  507  out of  1344
Processing i =  508  out of  1344
Processing i =  509  out of  1344
Processing i =  510  out of  1344
Processing i =  511  out of  1344
Processing i =  512  out of  1344
Processing i =  513  out of  1344
Processing i =  514  out of  1344
Processing i =  515  out of  1344
Processing i =  516  out of  1344
Processing i =  517  out of  1344
Processing i =  518  out of  1344
Processing i =  519  out of  1344
Processing i =  520  out of  1344
Processing i =  521  out of  1344
Processing i =  522  out of  1344
Processing i =  523  out of  1344
Processing i =  524  out of  1344
Processing i =  525  out of  1344
Processing i =  526  out of  1344
Processing i =  527  out of  1344
Processing i =  528  out of  1344
Processing i =  529  out of  1344
Processing i =  530  out of  1344
Processing i =  531  out of  1344
Processing i =  532  out of  1344
Processing i =  533  out of  1344
Processing i =  534  out of  1344
Processing i =  535  out of  1344
Processing i =  536  out of  1344
Processing i =  537  out of  1344
Processing i =  538  out of  1344
Processing i =  539  out of  1344
Processing i =  540  out of  1344
Processing i =  541  out of  1344
Processing i =  542  out of  1344
Processing i =  543  out of  1344
Processing i =  544  out of  1344
Processing i =  545  out of  1344
Processing i =  546  out of  1344
Processing i =  547  out of  1344
Processing i =  548  out of  1344
Processing i =  549  out of  1344
Processing i =  550  out of  1344
Processing i =  551  out of  1344
Processing i =  552  out of  1344
Processing i =  553  out of  1344
Processing i =  554  out of  1344
Processing i =  555  out of  1344
Processing i =  556  out of  1344
Processing i =  557  out of  1344
Processing i =  558  out of  1344
Processing i =  559  out of  1344
Processing i =  560  out of  1344
Processing i =  561  out of  1344
Processing i =  562  out of  1344
Processing i =  563  out of  1344
Processing i =  564  out of  1344
Processing i =  565  out of  1344
Processing i =  566  out of  1344
Processing i =  567  out of  1344
Processing i =  568  out of  1344
Processing i =  569  out of  1344
Processing i =  570  out of  1344
Processing i =  571  out of  1344
Processing i =  572  out of  1344
Processing i =  573  out of  1344
Processing i =  574  out of  1344
Processing i =  575  out of  1344
Processing i =  576  out of  1344
Processing i =  577  out of  1344
Processing i =  578  out of  1344
Processing i =  579  out of  1344
Processing i =  580  out of  1344
Processing i =  581  out of  1344
Processing i =  582  out of  1344
Processing i =  583  out of  1344
Processing i =  584  out of  1344

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 2 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 3 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 4 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 5 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 6 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 7 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 8 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 9 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 10 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[run 17/36] ds17 m7 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Epoch [1/500], Loss: 43999.8242
Epoch [11/500], Loss: 7375.1626
Epoch [21/500], Loss: 3349.9312
Epoch [31/500], Loss: 2728.8010
Epoch [41/500], Loss: 2107.2002
Epoch [51/500], Loss: 1784.7233
Epoch [61/500], Loss: 1618.0258
Epoch [71/500], Loss: 1502.1895
Epoch [81/500], Loss: 1426.6505
Epoch [91/500], Loss: 1372.4979
Epoch [101/500], Loss: 1324.9268
Epoch [111/500], Loss: 1284.2839
Epoch [121/500], Loss: 1247.6312
Epoch [131/500], Loss: 1214.1729
Epoch [141/500], Loss: 1182.8351
Epoch [151/500], Loss: 1152.8717
Epoch [161/500], Loss: 1123.6965
Epoch [171/500], Loss: 1095.5073
Epoch [181/500], Loss: 1068.6243
Epoch [191/500], Loss: 1042.8508
Epoch [201/500], Loss: 1017.9198
Epoch [211/500], Loss: 993.6056
Epoch [221/500], Loss: 969.8677
Epoch [231/500], Loss: 946.4776
Epoch [241/500], Loss: 923.5723
Epoch [251/500], Loss: 901.2546
Epoch [261/500], Loss: 879.6366
Epoch [271/500], Loss: 858.4816
Epoch [281/500], Loss: 838.0098
Epoch [291/500], Loss: 818.4908
Epoch [301/500], Loss: 799.2297
Epoch [311/500], Loss: 780.1374
Epoch [321/500], Loss: 760.6716
Epoch [331/500], Loss: 739.8621
Epoch [341/500], Loss: 719.9118
Epoch [351/500], Loss: 702.5460
Epoch [361/500], Loss: 684.6243
Epoch [371/500], Loss: 666.4303
Epoch [381/500], Loss: 648.5252
Epoch [391/500], Loss: 632.0613
Epoch [401/500], Loss: 616.7586
Epoch [411/500], Loss: 602.0612
Epoch [421/500], Loss: 588.0485
Epoch [431/500], Loss: 574.6523
Epoch [441/500], Loss: 561.9008
Epoch [451/500], Loss: 549.8268
Epoch [461/500], Loss: 538.4154
Epoch [471/500], Loss: 527.5745
Epoch [481/500], Loss: 517.2401
Epoch [491/500], Loss: 507.3967

Processing CV 2 / 10....
Epoch [1/500], Loss: 43369.0039
Epoch [11/500], Loss: 7000.3979
Epoch [21/500], Loss: 3468.7568
Epoch [31/500], Loss: 2718.9551
Epoch [41/500], Loss: 2125.8386
Epoch [51/500], Loss: 1808.3478
Epoch [61/500], Loss: 1634.8884
Epoch [71/500], Loss: 1520.7930
Epoch [81/500], Loss: 1442.4873
Epoch [91/500], Loss: 1385.5529
Epoch [101/500], Loss: 1336.1763
Epoch [111/500], Loss: 1293.6545
Epoch [121/500], Loss: 1254.8525
Epoch [131/500], Loss: 1218.8854
Epoch [141/500], Loss: 1184.7853
Epoch [151/500], Loss: 1152.4573
Epoch [161/500], Loss: 1121.5653
Epoch [171/500], Loss: 1092.1403
Epoch [181/500], Loss: 1063.9965
Epoch [191/500], Loss: 1037.0173
Epoch [201/500], Loss: 1011.2697
Epoch [211/500], Loss: 986.2840
Epoch [221/500], Loss: 962.5333
Epoch [231/500], Loss: 939.8779
Epoch [241/500], Loss: 917.9507
Epoch [251/500], Loss: 896.7535
Epoch [261/500], Loss: 876.4709
Epoch [271/500], Loss: 856.8255
Epoch [281/500], Loss: 837.7300
Epoch [291/500], Loss: 819.0448
Epoch [301/500], Loss: 800.9906
Epoch [311/500], Loss: 783.5439
Epoch [321/500], Loss: 766.5847
Epoch [331/500], Loss: 750.2037
Epoch [341/500], Loss: 734.1415
Epoch [351/500], Loss: 718.4106
Epoch [361/500], Loss: 702.9176
Epoch [371/500], Loss: 687.5718
Epoch [381/500], Loss: 672.0914
Epoch [391/500], Loss: 656.5216
Epoch [401/500], Loss: 641.3206
Epoch [411/500], Loss: 627.5705
Epoch [421/500], Loss: 614.6882
Epoch [431/500], Loss: 602.3985
Epoch [441/500], Loss: 590.5761
Epoch [451/500], Loss: 579.2880
Epoch [461/500], Loss: 568.4825
Epoch [471/500], Loss: 558.1281
Epoch [481/500], Loss: 548.2069
Epoch [491/500], Loss: 538.6816

Processing CV 3 / 10....
Epoch [1/500], Loss: 43605.7031
Epoch [11/500], Loss: 7325.3047
Epoch [21/500], Loss: 3305.5706
Epoch [31/500], Loss: 2765.2017
Epoch [41/500], Loss: 2152.6611
Epoch [51/500], Loss: 1841.9474
Epoch [61/500], Loss: 1679.5892
Epoch [71/500], Loss: 1562.0859
Epoch [81/500], Loss: 1484.6604
Epoch [91/500], Loss: 1428.6927
Epoch [101/500], Loss: 1379.3625
Epoch [111/500], Loss: 1337.3322
Epoch [121/500], Loss: 1299.1666
Epoch [131/500], Loss: 1264.4568
Epoch [141/500], Loss: 1231.9471
Epoch [151/500], Loss: 1200.7450
Epoch [161/500], Loss: 1169.9950
Epoch [171/500], Loss: 1140.1616
Epoch [181/500], Loss: 1111.4323
Epoch [191/500], Loss: 1083.7491
Epoch [201/500], Loss: 1057.2916
Epoch [211/500], Loss: 1031.9308
Epoch [221/500], Loss: 1007.8795
Epoch [231/500], Loss: 984.6982
Epoch [241/500], Loss: 962.6080
Epoch [251/500], Loss: 941.2617
Epoch [261/500], Loss: 920.4315
Epoch [271/500], Loss: 900.0397
Epoch [281/500], Loss: 880.1275
Epoch [291/500], Loss: 860.7344
Epoch [301/500], Loss: 841.8882
Epoch [311/500], Loss: 823.5000
Epoch [321/500], Loss: 805.5538
Epoch [331/500], Loss: 787.6800
Epoch [341/500], Loss: 769.8230
Epoch [351/500], Loss: 752.0654
Epoch [361/500], Loss: 732.8980
Epoch [371/500], Loss: 713.2558
Epoch [381/500], Loss: 695.8290
Epoch [391/500], Loss: 680.3632
Epoch [401/500], Loss: 665.6617
Epoch [411/500], Loss: 651.5544
Epoch [421/500], Loss: 638.0312
Epoch [431/500], Loss: 625.0681
Epoch [441/500], Loss: 612.6819
Epoch [451/500], Loss: 600.8218
Epoch [461/500], Loss: 589.4368
Epoch [471/500], Loss: 578.4736
Epoch [481/500], Loss: 567.8710
Epoch [491/500], Loss: 557.6376

Processing CV 4 / 10....
Epoch [1/500], Loss: 43993.3320
Epoch [11/500], Loss: 7724.4023
Epoch [21/500], Loss: 3290.2988
Epoch [31/500], Loss: 2761.4204
Epoch [41/500], Loss: 2219.1746
Epoch [51/500], Loss: 1913.6060
Epoch [61/500], Loss: 1746.4236
Epoch [71/500], Loss: 1625.4702
Epoch [81/500], Loss: 1537.8199
Epoch [91/500], Loss: 1474.0793
Epoch [101/500], Loss: 1418.2629
Epoch [111/500], Loss: 1371.1777
Epoch [121/500], Loss: 1329.0470
Epoch [131/500], Loss: 1290.7528
Epoch [141/500], Loss: 1255.1484
Epoch [151/500], Loss: 1221.4402
Epoch [161/500], Loss: 1189.1069
Epoch [171/500], Loss: 1157.7924
Epoch [181/500], Loss: 1127.4473
Epoch [191/500], Loss: 1098.3407
Epoch [201/500], Loss: 1070.3613
Epoch [211/500], Loss: 1043.3679
Epoch [221/500], Loss: 1017.4001
Epoch [231/500], Loss: 992.4241
Epoch [241/500], Loss: 968.7132
Epoch [251/500], Loss: 945.6397
Epoch [261/500], Loss: 923.4813
Epoch [271/500], Loss: 902.3214
Epoch [281/500], Loss: 881.8734
Epoch [291/500], Loss: 861.9251
Epoch [301/500], Loss: 842.3536
Epoch [311/500], Loss: 823.1963
Epoch [321/500], Loss: 804.5760
Epoch [331/500], Loss: 786.3234
Epoch [341/500], Loss: 768.5795
Epoch [351/500], Loss: 750.1248
Epoch [361/500], Loss: 730.1990
Epoch [371/500], Loss: 711.4088
Epoch [381/500], Loss: 695.0590
Epoch [391/500], Loss: 679.6655
Epoch [401/500], Loss: 664.9658
Epoch [411/500], Loss: 650.9253
Epoch [421/500], Loss: 637.5005
Epoch [431/500], Loss: 624.5946
Epoch [441/500], Loss: 612.2232
Epoch [451/500], Loss: 600.3449
Epoch [461/500], Loss: 588.9298
Epoch [471/500], Loss: 577.9001
Epoch [481/500], Loss: 567.3137
Epoch [491/500], Loss: 557.1724

Processing CV 5 / 10....
Epoch [1/500], Loss: 43247.0039
Epoch [11/500], Loss: 7864.7129
Epoch [21/500], Loss: 3336.5642
Epoch [31/500], Loss: 2580.3975
Epoch [41/500], Loss: 2174.1028
Epoch [51/500], Loss: 1916.6152
Epoch [61/500], Loss: 1737.1940
Epoch [71/500], Loss: 1628.2272
Epoch [81/500], Loss: 1538.2346
Epoch [91/500], Loss: 1470.6062
Epoch [101/500], Loss: 1413.4005
Epoch [111/500], Loss: 1364.6288
Epoch [121/500], Loss: 1322.0259
Epoch [131/500], Loss: 1283.8744
Epoch [141/500], Loss: 1249.0919
Epoch [151/500], Loss: 1216.7336
Epoch [161/500], Loss: 1186.0325
Epoch [171/500], Loss: 1156.5186
Epoch [181/500], Loss: 1127.7826
Epoch [191/500], Loss: 1099.8069
Epoch [201/500], Loss: 1072.8331
Epoch [211/500], Loss: 1046.4730
Epoch [221/500], Loss: 1020.3621
Epoch [231/500], Loss: 994.8697
Epoch [241/500], Loss: 969.3618
Epoch [251/500], Loss: 943.4083
Epoch [261/500], Loss: 916.2831
Epoch [271/500], Loss: 886.9297
Epoch [281/500], Loss: 857.4219
Epoch [291/500], Loss: 834.0676
Epoch [301/500], Loss: 812.7869
Epoch [311/500], Loss: 792.4002
Epoch [321/500], Loss: 772.9062
Epoch [331/500], Loss: 754.0109
Epoch [341/500], Loss: 735.3047
Epoch [351/500], Loss: 715.3685
Epoch [361/500], Loss: 694.4772
Epoch [371/500], Loss: 672.7015
Epoch [381/500], Loss: 654.2443
Epoch [391/500], Loss: 637.3993
Epoch [401/500], Loss: 621.4464
Epoch [411/500], Loss: 606.2964
Epoch [421/500], Loss: 591.9310
Epoch [431/500], Loss: 578.3616
Epoch [441/500], Loss: 565.5392
Epoch [451/500], Loss: 553.3802
Epoch [461/500], Loss: 541.8965
Epoch [471/500], Loss: 531.0604
Epoch [481/500], Loss: 520.8375
Epoch [491/500], Loss: 511.1733

Processing CV 6 / 10....
Epoch [1/500], Loss: 42899.8867
Epoch [11/500], Loss: 7763.3389
Epoch [21/500], Loss: 3609.6340
Epoch [31/500], Loss: 2603.0542
Epoch [41/500], Loss: 2206.7861
Epoch [51/500], Loss: 1985.7002
Epoch [61/500], Loss: 1790.3563
Epoch [71/500], Loss: 1675.0885
Epoch [81/500], Loss: 1583.4352
Epoch [91/500], Loss: 1511.6903
Epoch [101/500], Loss: 1453.2043
Epoch [111/500], Loss: 1402.7651
Epoch [121/500], Loss: 1358.9127
Epoch [131/500], Loss: 1319.4301
Epoch [141/500], Loss: 1283.2971
Epoch [151/500], Loss: 1249.6785
Epoch [161/500], Loss: 1217.8833
Epoch [171/500], Loss: 1187.5292
Epoch [181/500], Loss: 1158.3499
Epoch [191/500], Loss: 1130.1792
Epoch [201/500], Loss: 1102.7217
Epoch [211/500], Loss: 1075.3685
Epoch [221/500], Loss: 1047.8862
Epoch [231/500], Loss: 1020.8279
Epoch [241/500], Loss: 994.4279
Epoch [251/500], Loss: 968.3187
Epoch [261/500], Loss: 941.0429
Epoch [271/500], Loss: 910.7184
Epoch [281/500], Loss: 881.3875
Epoch [291/500], Loss: 856.8581
Epoch [301/500], Loss: 834.1240
Epoch [311/500], Loss: 812.6641
Epoch [321/500], Loss: 792.2708
Epoch [331/500], Loss: 772.8881
Epoch [341/500], Loss: 754.6264
Epoch [351/500], Loss: 737.1511
Epoch [361/500], Loss: 720.3204
Epoch [371/500], Loss: 704.0728
Epoch [381/500], Loss: 688.3237
Epoch [391/500], Loss: 673.0986
Epoch [401/500], Loss: 658.3914
Epoch [411/500], Loss: 644.0665
Epoch [421/500], Loss: 630.0996
Epoch [431/500], Loss: 616.6038
Epoch [441/500], Loss: 603.5969
Epoch [451/500], Loss: 591.1196
Epoch [461/500], Loss: 579.1782
Epoch [471/500], Loss: 567.6584
Epoch [481/500], Loss: 556.4642
Epoch [491/500], Loss: 545.6122

Processing CV 7 / 10....
Epoch [1/500], Loss: 42888.3047
Epoch [11/500], Loss: 7697.2163
Epoch [21/500], Loss: 3496.1365
Epoch [31/500], Loss: 2554.3635
Epoch [41/500], Loss: 2169.2761
Epoch [51/500], Loss: 1942.6106
Epoch [61/500], Loss: 1753.7495
Epoch [71/500], Loss: 1644.0197
Epoch [81/500], Loss: 1554.0250
Epoch [91/500], Loss: 1484.4781
Epoch [101/500], Loss: 1427.5541
Epoch [111/500], Loss: 1378.4274
Epoch [121/500], Loss: 1335.7452
Epoch [131/500], Loss: 1297.2671
Epoch [141/500], Loss: 1261.9491
Epoch [151/500], Loss: 1229.1047
Epoch [161/500], Loss: 1198.0891
Epoch [171/500], Loss: 1168.6134
Epoch [181/500], Loss: 1140.2222
Epoch [191/500], Loss: 1112.7233
Epoch [201/500], Loss: 1085.9414
Epoch [211/500], Loss: 1059.5259
Epoch [221/500], Loss: 1033.2853
Epoch [231/500], Loss: 1006.3551
Epoch [241/500], Loss: 978.1826
Epoch [251/500], Loss: 948.3792
Epoch [261/500], Loss: 919.0640
Epoch [271/500], Loss: 892.4783
Epoch [281/500], Loss: 868.2531
Epoch [291/500], Loss: 844.9776
Epoch [301/500], Loss: 822.6174
Epoch [311/500], Loss: 801.0517
Epoch [321/500], Loss: 780.5203
Epoch [331/500], Loss: 761.0394
Epoch [341/500], Loss: 742.4177
Epoch [351/500], Loss: 724.5037
Epoch [361/500], Loss: 707.1238
Epoch [371/500], Loss: 690.2726
Epoch [381/500], Loss: 673.6290
Epoch [391/500], Loss: 657.6281
Epoch [401/500], Loss: 641.7122
Epoch [411/500], Loss: 624.8401
Epoch [421/500], Loss: 607.1135
Epoch [431/500], Loss: 590.3849
Epoch [441/500], Loss: 576.1487
Epoch [451/500], Loss: 562.8826
Epoch [461/500], Loss: 550.4749
Epoch [471/500], Loss: 538.8381
Epoch [481/500], Loss: 527.9362
Epoch [491/500], Loss: 517.7220

Processing CV 8 / 10....
Epoch [1/500], Loss: 43764.5547
Epoch [11/500], Loss: 7952.6309
Epoch [21/500], Loss: 3349.0967
Epoch [31/500], Loss: 2678.4243
Epoch [41/500], Loss: 2239.0684
Epoch [51/500], Loss: 1960.5962
Epoch [61/500], Loss: 1785.0873
Epoch [71/500], Loss: 1671.9949
Epoch [81/500], Loss: 1581.4888
Epoch [91/500], Loss: 1514.7240
Epoch [101/500], Loss: 1456.5122
Epoch [111/500], Loss: 1406.2625
Epoch [121/500], Loss: 1361.3602
Epoch [131/500], Loss: 1320.5518
Epoch [141/500], Loss: 1283.0486
Epoch [151/500], Loss: 1248.0801
Epoch [161/500], Loss: 1215.4158
Epoch [171/500], Loss: 1184.5082
Epoch [181/500], Loss: 1154.9274
Epoch [191/500], Loss: 1126.3340
Epoch [201/500], Loss: 1098.4519
Epoch [211/500], Loss: 1070.6735
Epoch [221/500], Loss: 1043.2867
Epoch [231/500], Loss: 1016.1641
Epoch [241/500], Loss: 989.1411
Epoch [251/500], Loss: 961.5002
Epoch [261/500], Loss: 931.6420
Epoch [271/500], Loss: 898.9062
Epoch [281/500], Loss: 872.2986
Epoch [291/500], Loss: 847.9765
Epoch [301/500], Loss: 822.1301
Epoch [311/500], Loss: 794.5982
Epoch [321/500], Loss: 769.1052
Epoch [331/500], Loss: 747.4524
Epoch [341/500], Loss: 726.8707
Epoch [351/500], Loss: 707.0687
Epoch [361/500], Loss: 688.0556
Epoch [371/500], Loss: 669.7596
Epoch [381/500], Loss: 652.2911
Epoch [391/500], Loss: 635.6553
Epoch [401/500], Loss: 619.8297
Epoch [411/500], Loss: 604.8390
Epoch [421/500], Loss: 590.6573
Epoch [431/500], Loss: 577.2853
Epoch [441/500], Loss: 564.6436
Epoch [451/500], Loss: 552.7174
Epoch [461/500], Loss: 541.5002
Epoch [471/500], Loss: 530.9094
Epoch [481/500], Loss: 520.9147
Epoch [491/500], Loss: 511.4793

Processing CV 9 / 10....
Epoch [1/500], Loss: 44347.9805
Epoch [11/500], Loss: 7828.0005
Epoch [21/500], Loss: 3349.3174
Epoch [31/500], Loss: 2743.4670
Epoch [41/500], Loss: 2225.5945
Epoch [51/500], Loss: 1920.8898
Epoch [61/500], Loss: 1751.1050
Epoch [71/500], Loss: 1635.2419
Epoch [81/500], Loss: 1549.7644
Epoch [91/500], Loss: 1487.2173
Epoch [101/500], Loss: 1432.5734
Epoch [111/500], Loss: 1386.3333
Epoch [121/500], Loss: 1345.3508
Epoch [131/500], Loss: 1308.3362
Epoch [141/500], Loss: 1273.9718
Epoch [151/500], Loss: 1241.2501
Epoch [161/500], Loss: 1209.4974
Epoch [171/500], Loss: 1178.7104
Epoch [181/500], Loss: 1149.0933
Epoch [191/500], Loss: 1120.4034
Epoch [201/500], Loss: 1092.1182
Epoch [211/500], Loss: 1064.6536
Epoch [221/500], Loss: 1037.6708
Epoch [231/500], Loss: 1010.7188
Epoch [241/500], Loss: 982.7495
Epoch [251/500], Loss: 951.7912
Epoch [261/500], Loss: 919.2231
Epoch [271/500], Loss: 892.5266
Epoch [281/500], Loss: 867.9648
Epoch [291/500], Loss: 844.0582
Epoch [301/500], Loss: 821.1303
Epoch [311/500], Loss: 797.4476
Epoch [321/500], Loss: 771.6439
Epoch [331/500], Loss: 745.1794
Epoch [341/500], Loss: 723.5430
Epoch [351/500], Loss: 703.6783
Epoch [361/500], Loss: 684.5804
Epoch [371/500], Loss: 666.1967
Epoch [381/500], Loss: 648.5273
Epoch [391/500], Loss: 631.6711
Epoch [401/500], Loss: 615.6159
Epoch [411/500], Loss: 600.3542
Epoch [421/500], Loss: 585.9312
Epoch [431/500], Loss: 572.3723
Epoch [441/500], Loss: 559.6299
Epoch [451/500], Loss: 547.6405
Epoch [461/500], Loss: 536.3596
Epoch [471/500], Loss: 525.7517
Epoch [481/500], Loss: 515.7539
Epoch [491/500], Loss: 506.3163

Processing CV 10 / 10....
Epoch [1/500], Loss: 44010.2656
Epoch [11/500], Loss: 7477.5298
Epoch [21/500], Loss: 3422.8372
Epoch [31/500], Loss: 2830.5686
Epoch [41/500], Loss: 2248.0068
Epoch [51/500], Loss: 1936.2360
Epoch [61/500], Loss: 1761.9817
Epoch [71/500], Loss: 1640.1255
Epoch [81/500], Loss: 1554.9551
Epoch [91/500], Loss: 1492.8112
Epoch [101/500], Loss: 1438.3741
Epoch [111/500], Loss: 1391.8545
Epoch [121/500], Loss: 1349.7502
Epoch [131/500], Loss: 1311.0387
Epoch [141/500], Loss: 1274.2762
Epoch [151/500], Loss: 1239.0363
Epoch [161/500], Loss: 1205.5111
Epoch [171/500], Loss: 1173.6669
Epoch [181/500], Loss: 1143.1399
Epoch [191/500], Loss: 1113.6899
Epoch [201/500], Loss: 1085.1638
Epoch [211/500], Loss: 1057.3264
Epoch [221/500], Loss: 1030.4823
Epoch [231/500], Loss: 1004.3204
Epoch [241/500], Loss: 979.0821
Epoch [251/500], Loss: 955.0458
Epoch [261/500], Loss: 931.7690
Epoch [271/500], Loss: 909.5178
Epoch [281/500], Loss: 888.2219
Epoch [291/500], Loss: 867.5349
Epoch [301/500], Loss: 847.3989
Epoch [311/500], Loss: 828.0482
Epoch [321/500], Loss: 809.4619
Epoch [331/500], Loss: 791.6331
Epoch [341/500], Loss: 774.3630
Epoch [351/500], Loss: 757.6489
Epoch [361/500], Loss: 741.4908
Epoch [371/500], Loss: 725.9266
Epoch [381/500], Loss: 710.9610
Epoch [391/500], Loss: 696.4955
Epoch [401/500], Loss: 682.4577
Epoch [411/500], Loss: 668.8444
Epoch [421/500], Loss: 655.6255
Epoch [431/500], Loss: 642.6171
Epoch [441/500], Loss: 629.7969
Epoch [451/500], Loss: 616.9894
Epoch [461/500], Loss: 604.5744
Epoch [471/500], Loss: 592.3449
Epoch [481/500], Loss: 580.5530
Epoch [491/500], Loss: 569.5052

[run 18/36] ds17 m1 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....

Processing CV 2 / 10....

Processing CV 3 / 10....

Processing CV 4 / 10....

Processing CV 5 / 10....

Processing CV 6 / 10....

Processing CV 7 / 10....

Processing CV 8 / 10....

Processing CV 9 / 10....

Processing CV 10 / 10....

[run 19/36] ds17 m3 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Processing i =  1  out of  1344
Processing i =  2  out of  1344
Processing i =  3  out of  1344
Processing i =  4  out of  1344
Processing i =  5  out of  1344
Processing i =  6  out of  1344
Processing i =  7  out of  1344
Processing i =  8  out of  1344
Processing i =  9  out of  1344
Processing i =  10  out of  1344
Processing i =  11  out of  1344
Processing i =  12  out of  1344
Processing i =  13  out of  1344
Processing i =  14  out of  1344
Processing i =  15  out of  1344
Processing i =  16  out of  1344
Processing i =  17  out of  1344
Processing i =  18  out of  1344
Processing i =  19  out of  1344
Processing i =  20  out of  1344
Processing i =  21  out of  1344
Processing i =  22  out of  1344
Processing i =  23  out of  1344
Processing i =  24  out of  1344
Processing i =  25  out of  1344
Processing i =  26  out of  1344
Processing i =  27  out of  1344
Processing i =  28  out of  1344
Processing i =  29  out of  1344
Processing i =  30  out of  1344
Processing i =  31  out of  1344
Processing i =  32  out of  1344
Processing i =  33  out of  1344
Processing i =  34  out of  1344
Processing i =  35  out of  1344
Processing i =  36  out of  1344
Processing i =  37  out of  1344
Processing i =  38  out of  1344
Processing i =  39  out of  1344
Processing i =  40  out of  1344
Processing i =  41  out of  1344
Processing i =  42  out of  1344
Processing i =  43  out of  1344
Processing i =  44  out of  1344
Processing i =  45  out of  1344
Processing i =  46  out of  1344
Processing i =  47  out of  1344
Processing i =  48  out of  1344
Processing i =  49  out of  1344
Processing i =  50  out of  1344
Processing i =  51  out of  1344
Processing i =  52  out of  1344
Processing i =  53  out of  1344
Processing i =  54  out of  1344
Processing i =  55  out of  1344
Processing i =  56  out of  1344
Processing i =  57  out of  1344
Processing i =  58  out of  1344
Processing i =  59  out of  1344
Processing i =  60  out of  1344
Processing i =  61  out of  1344
Processing i =  62  out of  1344
Processing i =  63  out of  1344
Processing i =  64  out of  1344
Processing i =  65  out of  1344
Processing i =  66  out of  1344
Processing i =  67  out of  1344
Processing i =  68  out of  1344
Processing i =  69  out of  1344
Processing i =  70  out of  1344
Processing i =  71  out of  1344
Processing i =  72  out of  1344
Processing i =  73  out of  1344
Processing i =  74  out of  1344
Processing i =  75  out of  1344
Processing i =  76  out of  1344
Processing i =  77  out of  1344
Processing i =  78  out of  1344
Processing i =  79  out of  1344
Processing i =  80  out of  1344
Processing i =  81  out of  1344
Processing i =  82  out of  1344
Processing i =  83  out of  1344
Processing i =  84  out of  1344
Processing i =  85  out of  1344
Processing i =  86  out of  1344

23:12:00 - cmdstanpy - INFO - Chain [1] start processing
23:12:02 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:12:03 - cmdstanpy - INFO - Chain [1] start processing
23:12:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:12:05 - cmdstanpy - INFO - Chain [1] start processing
23:12:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:12:06 - cmdstanpy - INFO - Chain [1] start processing
23:12:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

23:12:07 - cmdstanpy - INFO - Chain [1] start processing
23:12:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

23:12:07 - cmdstanpy - INFO - Chain [1] start processing
23:12:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

23:12:08 - cmdstanpy - INFO - Chain [1] start processing
23:12:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:12:09 - cmdstanpy - INFO - Chain [1] start processing
23:12:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

23:12:10 - cmdstanpy - INFO - Chain [1] start processing
23:12:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

23:12:11 - cmdstanpy - INFO - Chain [1] start processing
23:12:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

23:12:12 - cmdstanpy - INFO - Chain [1] start processing
23:12:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:12:13 - cmdstanpy - INFO - Chain [1] start processing
23:12:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

23:12:14 - cmdstanpy - INFO - Chain [1] start processing
23:12:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

23:12:14 - cmdstanpy - INFO - Chain [1] start processing
23:12:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:12:15 - cmdstanpy - INFO - Chain [1] start processing
23:12:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

23:12:16 - cmdstanpy - INFO - Chain [1] start processing
23:12:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

23:12:17 - cmdstanpy - INFO - Chain [1] start processing
23:12:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

23:12:18 - cmdstanpy - INFO - Chain [1] start processing
23:12:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:12:19 - cmdstanpy - INFO - Chain [1] start processing
23:12:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:12:20 - cmdstanpy - INFO - Chain [1] start processing
23:12:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:12:21 - cmdstanpy - INFO - Chain [1] start processing
23:12:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:12:21 - cmdstanpy - INFO - Chain [1] start processing
23:12:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

23:12:22 - cmdstanpy - INFO - Chain [1] start processing
23:12:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

23:12:23 - cmdstanpy - INFO - Chain [1] start processing
23:12:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

23:12:24 - cmdstanpy - INFO - Chain [1] start processing
23:12:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:12:25 - cmdstanpy - INFO - Chain [1] start processing
23:12:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:12:26 - cmdstanpy - INFO - Chain [1] start processing
23:12:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:12:27 - cmdstanpy - INFO - Chain [1] start processing
23:12:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

23:12:28 - cmdstanpy - INFO - Chain [1] start processing
23:12:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

23:12:29 - cmdstanpy - INFO - Chain [1] start processing
23:12:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:12:30 - cmdstanpy - INFO - Chain [1] start processing
23:12:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

23:12:31 - cmdstanpy - INFO - Chain [1] start processing
23:12:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:12:32 - cmdstanpy - INFO - Chain [1] start processing
23:12:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:12:33 - cmdstanpy - INFO - Chain [1] start processing
23:12:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

23:12:34 - cmdstanpy - INFO - Chain [1] start processing
23:12:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

23:12:35 - cmdstanpy - INFO - Chain [1] start processing
23:12:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:12:36 - cmdstanpy - INFO - Chain [1] start processing
23:12:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:12:37 - cmdstanpy - INFO - Chain [1] start processing
23:12:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:12:38 - cmdstanpy - INFO - Chain [1] start processing
23:12:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

23:12:39 - cmdstanpy - INFO - Chain [1] start processing
23:12:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

23:12:40 - cmdstanpy - INFO - Chain [1] start processing
23:12:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:12:41 - cmdstanpy - INFO - Chain [1] start processing
23:12:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:12:42 - cmdstanpy - INFO - Chain [1] start processing
23:12:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

23:12:43 - cmdstanpy - INFO - Chain [1] start processing
23:12:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:12:44 - cmdstanpy - INFO - Chain [1] start processing
23:12:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:12:45 - cmdstanpy - INFO - Chain [1] start processing
23:12:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

23:12:46 - cmdstanpy - INFO - Chain [1] start processing
23:12:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:12:46 - cmdstanpy - INFO - Chain [1] start processing
23:12:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:12:48 - cmdstanpy - INFO - Chain [1] start processing
23:12:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:12:49 - cmdstanpy - INFO - Chain [1] start processing
23:12:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:12:50 - cmdstanpy - INFO - Chain [1] start processing
23:12:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:12:51 - cmdstanpy - INFO - Chain [1] start processing
23:12:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:12:52 - cmdstanpy - INFO - Chain [1] start processing
23:12:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:12:54 - cmdstanpy - INFO - Chain [1] start processing
23:12:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

23:12:55 - cmdstanpy - INFO - Chain [1] start processing
23:12:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:12:56 - cmdstanpy - INFO - Chain [1] start processing
23:12:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

23:12:57 - cmdstanpy - INFO - Chain [1] start processing
23:12:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

23:12:58 - cmdstanpy - INFO - Chain [1] start processing
23:12:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

23:12:58 - cmdstanpy - INFO - Chain [1] start processing
23:12:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:12:59 - cmdstanpy - INFO - Chain [1] start processing
23:12:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:13:00 - cmdstanpy - INFO - Chain [1] start processing
23:13:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:13:01 - cmdstanpy - INFO - Chain [1] start processing
23:13:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:13:02 - cmdstanpy - INFO - Chain [1] start processing
23:13:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:13:03 - cmdstanpy - INFO - Chain [1] start processing
23:13:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:13:04 - cmdstanpy - INFO - Chain [1] start processing
23:13:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:13:04 - cmdstanpy - INFO - Chain [1] start processing
23:13:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

23:13:05 - cmdstanpy - INFO - Chain [1] start processing
23:13:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:13:07 - cmdstanpy - INFO - Chain [1] start processing
23:13:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:13:07 - cmdstanpy - INFO - Chain [1] start processing
23:13:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:13:08 - cmdstanpy - INFO - Chain [1] start processing
23:13:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:13:09 - cmdstanpy - INFO - Chain [1] start processing
23:13:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:13:10 - cmdstanpy - INFO - Chain [1] start processing
23:13:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:13:11 - cmdstanpy - INFO - Chain [1] start processing
23:13:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:13:12 - cmdstanpy - INFO - Chain [1] start processing
23:13:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:13:13 - cmdstanpy - INFO - Chain [1] start processing
23:13:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

23:13:14 - cmdstanpy - INFO - Chain [1] start processing
23:13:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:13:15 - cmdstanpy - INFO - Chain [1] start processing
23:13:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:13:16 - cmdstanpy - INFO - Chain [1] start processing
23:13:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:13:16 - cmdstanpy - INFO - Chain [1] start processing
23:13:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:13:17 - cmdstanpy - INFO - Chain [1] start processing
23:13:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:13:18 - cmdstanpy - INFO - Chain [1] start processing
23:13:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:13:19 - cmdstanpy - INFO - Chain [1] start processing
23:13:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:13:20 - cmdstanpy - INFO - Chain [1] start processing
23:13:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:13:21 - cmdstanpy - INFO - Chain [1] start processing
23:13:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:13:21 - cmdstanpy - INFO - Chain [1] start processing
23:13:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

23:13:22 - cmdstanpy - INFO - Chain [1] start processing
23:13:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

23:13:23 - cmdstanpy - INFO - Chain [1] start processing
23:13:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:13:24 - cmdstanpy - INFO - Chain [1] start processing
23:13:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:13:25 - cmdstanpy - INFO - Chain [1] start processing
23:13:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:13:26 - cmdstanpy - INFO - Chain [1] start processing
23:13:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:13:27 - cmdstanpy - INFO - Chain [1] start processing
23:13:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:13:28 - cmdstanpy - INFO - Chain [1] start processing
23:13:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:13:30 - cmdstanpy - INFO - Chain [1] start processing
23:13:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:13:30 - cmdstanpy - INFO - Chain [1] start processing
23:13:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:13:31 - cmdstanpy - INFO - Chain [1] start processing
23:13:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:13:32 - cmdstanpy - INFO - Chain [1] start processing
23:13:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:13:33 - cmdstanpy - INFO - Chain [1] start processing
23:13:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:13:34 - cmdstanpy - INFO - Chain [1] start processing
23:13:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:13:35 - cmdstanpy - INFO - Chain [1] start processing
23:13:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:13:36 - cmdstanpy - INFO - Chain [1] start processing
23:13:36 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 2 / 10....

23:13:38 - cmdstanpy - INFO - Chain [1] start processing
23:13:38 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:13:40 - cmdstanpy - INFO - Chain [1] start processing
23:13:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:13:42 - cmdstanpy - INFO - Chain [1] start processing
23:13:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:13:43 - cmdstanpy - INFO - Chain [1] start processing
23:13:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

23:13:43 - cmdstanpy - INFO - Chain [1] start processing
23:13:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

23:13:44 - cmdstanpy - INFO - Chain [1] start processing
23:13:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

23:13:45 - cmdstanpy - INFO - Chain [1] start processing
23:13:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:13:46 - cmdstanpy - INFO - Chain [1] start processing
23:13:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

23:13:47 - cmdstanpy - INFO - Chain [1] start processing
23:13:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

23:13:48 - cmdstanpy - INFO - Chain [1] start processing
23:13:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

23:13:48 - cmdstanpy - INFO - Chain [1] start processing
23:13:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:13:49 - cmdstanpy - INFO - Chain [1] start processing
23:13:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

23:13:50 - cmdstanpy - INFO - Chain [1] start processing
23:13:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

23:13:51 - cmdstanpy - INFO - Chain [1] start processing
23:13:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:13:52 - cmdstanpy - INFO - Chain [1] start processing
23:13:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

23:13:53 - cmdstanpy - INFO - Chain [1] start processing
23:13:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

23:13:53 - cmdstanpy - INFO - Chain [1] start processing
23:13:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

23:13:54 - cmdstanpy - INFO - Chain [1] start processing
23:13:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:13:55 - cmdstanpy - INFO - Chain [1] start processing
23:13:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:13:56 - cmdstanpy - INFO - Chain [1] start processing
23:13:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:13:57 - cmdstanpy - INFO - Chain [1] start processing
23:13:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:13:58 - cmdstanpy - INFO - Chain [1] start processing
23:13:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

23:13:58 - cmdstanpy - INFO - Chain [1] start processing
23:13:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

23:13:59 - cmdstanpy - INFO - Chain [1] start processing
23:13:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

23:14:00 - cmdstanpy - INFO - Chain [1] start processing
23:14:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:14:01 - cmdstanpy - INFO - Chain [1] start processing
23:14:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:14:02 - cmdstanpy - INFO - Chain [1] start processing
23:14:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:14:03 - cmdstanpy - INFO - Chain [1] start processing
23:14:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

23:14:04 - cmdstanpy - INFO - Chain [1] start processing
23:14:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

23:14:05 - cmdstanpy - INFO - Chain [1] start processing
23:14:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:14:06 - cmdstanpy - INFO - Chain [1] start processing
23:14:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

23:14:07 - cmdstanpy - INFO - Chain [1] start processing
23:14:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:14:08 - cmdstanpy - INFO - Chain [1] start processing
23:14:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:14:09 - cmdstanpy - INFO - Chain [1] start processing
23:14:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

23:14:10 - cmdstanpy - INFO - Chain [1] start processing
23:14:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

23:14:11 - cmdstanpy - INFO - Chain [1] start processing
23:14:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:14:11 - cmdstanpy - INFO - Chain [1] start processing
23:14:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:14:12 - cmdstanpy - INFO - Chain [1] start processing
23:14:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:14:13 - cmdstanpy - INFO - Chain [1] start processing
23:14:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

23:14:14 - cmdstanpy - INFO - Chain [1] start processing
23:14:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

23:14:15 - cmdstanpy - INFO - Chain [1] start processing
23:14:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:14:16 - cmdstanpy - INFO - Chain [1] start processing
23:14:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:14:17 - cmdstanpy - INFO - Chain [1] start processing
23:14:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

23:14:18 - cmdstanpy - INFO - Chain [1] start processing
23:14:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:14:19 - cmdstanpy - INFO - Chain [1] start processing
23:14:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:14:20 - cmdstanpy - INFO - Chain [1] start processing
23:14:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

23:14:21 - cmdstanpy - INFO - Chain [1] start processing
23:14:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:14:22 - cmdstanpy - INFO - Chain [1] start processing
23:14:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:14:23 - cmdstanpy - INFO - Chain [1] start processing
23:14:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:14:24 - cmdstanpy - INFO - Chain [1] start processing
23:14:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:14:24 - cmdstanpy - INFO - Chain [1] start processing
23:14:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:14:25 - cmdstanpy - INFO - Chain [1] start processing
23:14:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:14:26 - cmdstanpy - INFO - Chain [1] start processing
23:14:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:14:27 - cmdstanpy - INFO - Chain [1] start processing
23:14:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

23:14:27 - cmdstanpy - INFO - Chain [1] start processing
23:14:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:14:28 - cmdstanpy - INFO - Chain [1] start processing
23:14:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

23:14:29 - cmdstanpy - INFO - Chain [1] start processing
23:14:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

23:14:30 - cmdstanpy - INFO - Chain [1] start processing
23:14:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

23:14:31 - cmdstanpy - INFO - Chain [1] start processing
23:14:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:14:32 - cmdstanpy - INFO - Chain [1] start processing
23:14:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:14:33 - cmdstanpy - INFO - Chain [1] start processing
23:14:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:14:34 - cmdstanpy - INFO - Chain [1] start processing
23:14:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:14:35 - cmdstanpy - INFO - Chain [1] start processing
23:14:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:14:36 - cmdstanpy - INFO - Chain [1] start processing
23:14:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:14:37 - cmdstanpy - INFO - Chain [1] start processing
23:14:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:14:38 - cmdstanpy - INFO - Chain [1] start processing
23:14:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

23:14:39 - cmdstanpy - INFO - Chain [1] start processing
23:14:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:14:39 - cmdstanpy - INFO - Chain [1] start processing
23:14:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:14:40 - cmdstanpy - INFO - Chain [1] start processing
23:14:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:14:41 - cmdstanpy - INFO - Chain [1] start processing
23:14:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:14:42 - cmdstanpy - INFO - Chain [1] start processing
23:14:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:14:43 - cmdstanpy - INFO - Chain [1] start processing
23:14:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:14:43 - cmdstanpy - INFO - Chain [1] start processing
23:14:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:14:44 - cmdstanpy - INFO - Chain [1] start processing
23:14:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:14:45 - cmdstanpy - INFO - Chain [1] start processing
23:14:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

23:14:46 - cmdstanpy - INFO - Chain [1] start processing
23:14:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:14:46 - cmdstanpy - INFO - Chain [1] start processing
23:14:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:14:47 - cmdstanpy - INFO - Chain [1] start processing
23:14:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:14:48 - cmdstanpy - INFO - Chain [1] start processing
23:14:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:14:49 - cmdstanpy - INFO - Chain [1] start processing
23:14:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:14:50 - cmdstanpy - INFO - Chain [1] start processing
23:14:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:14:51 - cmdstanpy - INFO - Chain [1] start processing
23:14:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:14:51 - cmdstanpy - INFO - Chain [1] start processing
23:14:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:14:52 - cmdstanpy - INFO - Chain [1] start processing
23:14:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:14:54 - cmdstanpy - INFO - Chain [1] start processing
23:14:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

23:14:55 - cmdstanpy - INFO - Chain [1] start processing
23:14:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

23:14:55 - cmdstanpy - INFO - Chain [1] start processing
23:14:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:14:56 - cmdstanpy - INFO - Chain [1] start processing
23:14:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:14:57 - cmdstanpy - INFO - Chain [1] start processing
23:14:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:14:58 - cmdstanpy - INFO - Chain [1] start processing
23:14:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:14:59 - cmdstanpy - INFO - Chain [1] start processing
23:14:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:15:00 - cmdstanpy - INFO - Chain [1] start processing
23:15:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:15:01 - cmdstanpy - INFO - Chain [1] start processing
23:15:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:15:02 - cmdstanpy - INFO - Chain [1] start processing
23:15:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:15:03 - cmdstanpy - INFO - Chain [1] start processing
23:15:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:15:04 - cmdstanpy - INFO - Chain [1] start processing
23:15:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:15:05 - cmdstanpy - INFO - Chain [1] start processing
23:15:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:15:06 - cmdstanpy - INFO - Chain [1] start processing
23:15:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:15:07 - cmdstanpy - INFO - Chain [1] start processing
23:15:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:15:07 - cmdstanpy - INFO - Chain [1] start processing
23:15:08 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 3 / 10....

23:15:09 - cmdstanpy - INFO - Chain [1] start processing
23:15:09 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:15:11 - cmdstanpy - INFO - Chain [1] start processing
23:15:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:15:12 - cmdstanpy - INFO - Chain [1] start processing
23:15:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:15:13 - cmdstanpy - INFO - Chain [1] start processing
23:15:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

23:15:14 - cmdstanpy - INFO - Chain [1] start processing
23:15:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

23:15:14 - cmdstanpy - INFO - Chain [1] start processing
23:15:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

23:15:15 - cmdstanpy - INFO - Chain [1] start processing
23:15:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:15:16 - cmdstanpy - INFO - Chain [1] start processing
23:15:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

23:15:16 - cmdstanpy - INFO - Chain [1] start processing
23:15:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

23:15:17 - cmdstanpy - INFO - Chain [1] start processing
23:15:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

23:15:18 - cmdstanpy - INFO - Chain [1] start processing
23:15:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:15:19 - cmdstanpy - INFO - Chain [1] start processing
23:15:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

23:15:19 - cmdstanpy - INFO - Chain [1] start processing
23:15:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

23:15:20 - cmdstanpy - INFO - Chain [1] start processing
23:15:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:15:21 - cmdstanpy - INFO - Chain [1] start processing
23:15:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

23:15:22 - cmdstanpy - INFO - Chain [1] start processing
23:15:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

23:15:22 - cmdstanpy - INFO - Chain [1] start processing
23:15:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

23:15:23 - cmdstanpy - INFO - Chain [1] start processing
23:15:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:15:24 - cmdstanpy - INFO - Chain [1] start processing
23:15:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:15:24 - cmdstanpy - INFO - Chain [1] start processing
23:15:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:15:25 - cmdstanpy - INFO - Chain [1] start processing
23:15:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:15:27 - cmdstanpy - INFO - Chain [1] start processing
23:15:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

23:15:28 - cmdstanpy - INFO - Chain [1] start processing
23:15:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

23:15:28 - cmdstanpy - INFO - Chain [1] start processing
23:15:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

23:15:29 - cmdstanpy - INFO - Chain [1] start processing
23:15:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:15:30 - cmdstanpy - INFO - Chain [1] start processing
23:15:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:15:31 - cmdstanpy - INFO - Chain [1] start processing
23:15:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:15:31 - cmdstanpy - INFO - Chain [1] start processing
23:15:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

23:15:32 - cmdstanpy - INFO - Chain [1] start processing
23:15:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

23:15:33 - cmdstanpy - INFO - Chain [1] start processing
23:15:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:15:34 - cmdstanpy - INFO - Chain [1] start processing
23:15:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

23:15:35 - cmdstanpy - INFO - Chain [1] start processing
23:15:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:15:36 - cmdstanpy - INFO - Chain [1] start processing
23:15:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:15:36 - cmdstanpy - INFO - Chain [1] start processing
23:15:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

23:15:37 - cmdstanpy - INFO - Chain [1] start processing
23:15:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

23:15:38 - cmdstanpy - INFO - Chain [1] start processing
23:15:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:15:38 - cmdstanpy - INFO - Chain [1] start processing
23:15:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:15:39 - cmdstanpy - INFO - Chain [1] start processing
23:15:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:15:40 - cmdstanpy - INFO - Chain [1] start processing
23:15:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

23:15:41 - cmdstanpy - INFO - Chain [1] start processing
23:15:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

23:15:42 - cmdstanpy - INFO - Chain [1] start processing
23:15:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:15:43 - cmdstanpy - INFO - Chain [1] start processing
23:15:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:15:44 - cmdstanpy - INFO - Chain [1] start processing
23:15:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

23:15:45 - cmdstanpy - INFO - Chain [1] start processing
23:15:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:15:45 - cmdstanpy - INFO - Chain [1] start processing
23:15:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:15:46 - cmdstanpy - INFO - Chain [1] start processing
23:15:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

23:15:47 - cmdstanpy - INFO - Chain [1] start processing
23:15:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:15:48 - cmdstanpy - INFO - Chain [1] start processing
23:15:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:15:48 - cmdstanpy - INFO - Chain [1] start processing
23:15:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:15:49 - cmdstanpy - INFO - Chain [1] start processing
23:15:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:15:50 - cmdstanpy - INFO - Chain [1] start processing
23:15:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:15:51 - cmdstanpy - INFO - Chain [1] start processing
23:15:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:15:52 - cmdstanpy - INFO - Chain [1] start processing
23:15:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:15:53 - cmdstanpy - INFO - Chain [1] start processing
23:15:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

23:15:54 - cmdstanpy - INFO - Chain [1] start processing
23:15:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:15:55 - cmdstanpy - INFO - Chain [1] start processing
23:15:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

23:15:56 - cmdstanpy - INFO - Chain [1] start processing
23:15:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

23:15:56 - cmdstanpy - INFO - Chain [1] start processing
23:15:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

23:15:57 - cmdstanpy - INFO - Chain [1] start processing
23:15:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:15:58 - cmdstanpy - INFO - Chain [1] start processing
23:15:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:15:59 - cmdstanpy - INFO - Chain [1] start processing
23:15:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:16:00 - cmdstanpy - INFO - Chain [1] start processing
23:16:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:16:00 - cmdstanpy - INFO - Chain [1] start processing
23:16:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:16:01 - cmdstanpy - INFO - Chain [1] start processing
23:16:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:16:02 - cmdstanpy - INFO - Chain [1] start processing
23:16:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:16:02 - cmdstanpy - INFO - Chain [1] start processing
23:16:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

23:16:03 - cmdstanpy - INFO - Chain [1] start processing
23:16:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:16:04 - cmdstanpy - INFO - Chain [1] start processing
23:16:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:16:05 - cmdstanpy - INFO - Chain [1] start processing
23:16:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:16:05 - cmdstanpy - INFO - Chain [1] start processing
23:16:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:16:06 - cmdstanpy - INFO - Chain [1] start processing
23:16:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:16:07 - cmdstanpy - INFO - Chain [1] start processing
23:16:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:16:08 - cmdstanpy - INFO - Chain [1] start processing
23:16:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:16:09 - cmdstanpy - INFO - Chain [1] start processing
23:16:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:16:10 - cmdstanpy - INFO - Chain [1] start processing
23:16:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

23:16:10 - cmdstanpy - INFO - Chain [1] start processing
23:16:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:16:11 - cmdstanpy - INFO - Chain [1] start processing
23:16:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:16:12 - cmdstanpy - INFO - Chain [1] start processing
23:16:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:16:13 - cmdstanpy - INFO - Chain [1] start processing
23:16:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:16:14 - cmdstanpy - INFO - Chain [1] start processing
23:16:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:16:14 - cmdstanpy - INFO - Chain [1] start processing
23:16:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:16:15 - cmdstanpy - INFO - Chain [1] start processing
23:16:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:16:16 - cmdstanpy - INFO - Chain [1] start processing
23:16:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:16:17 - cmdstanpy - INFO - Chain [1] start processing
23:16:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:16:17 - cmdstanpy - INFO - Chain [1] start processing
23:16:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

23:16:18 - cmdstanpy - INFO - Chain [1] start processing
23:16:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

23:16:19 - cmdstanpy - INFO - Chain [1] start processing
23:16:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:16:20 - cmdstanpy - INFO - Chain [1] start processing
23:16:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:16:21 - cmdstanpy - INFO - Chain [1] start processing
23:16:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:16:22 - cmdstanpy - INFO - Chain [1] start processing
23:16:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:16:23 - cmdstanpy - INFO - Chain [1] start processing
23:16:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:16:24 - cmdstanpy - INFO - Chain [1] start processing
23:16:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:16:25 - cmdstanpy - INFO - Chain [1] start processing
23:16:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:16:25 - cmdstanpy - INFO - Chain [1] start processing
23:16:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:16:27 - cmdstanpy - INFO - Chain [1] start processing
23:16:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:16:28 - cmdstanpy - INFO - Chain [1] start processing
23:16:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:16:29 - cmdstanpy - INFO - Chain [1] start processing
23:16:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:16:29 - cmdstanpy - INFO - Chain [1] start processing
23:16:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:16:31 - cmdstanpy - INFO - Chain [1] start processing
23:16:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:16:32 - cmdstanpy - INFO - Chain [1] start processing
23:16:33 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 4 / 10....

23:16:33 - cmdstanpy - INFO - Chain [1] start processing
23:16:35 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:16:36 - cmdstanpy - INFO - Chain [1] start processing
23:16:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:16:37 - cmdstanpy - INFO - Chain [1] start processing
23:16:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:16:38 - cmdstanpy - INFO - Chain [1] start processing
23:16:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

23:16:39 - cmdstanpy - INFO - Chain [1] start processing
23:16:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

23:16:40 - cmdstanpy - INFO - Chain [1] start processing
23:16:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

23:16:40 - cmdstanpy - INFO - Chain [1] start processing
23:16:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:16:41 - cmdstanpy - INFO - Chain [1] start processing
23:16:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

23:16:41 - cmdstanpy - INFO - Chain [1] start processing
23:16:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

23:16:42 - cmdstanpy - INFO - Chain [1] start processing
23:16:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

23:16:43 - cmdstanpy - INFO - Chain [1] start processing
23:16:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:16:43 - cmdstanpy - INFO - Chain [1] start processing
23:16:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

23:16:44 - cmdstanpy - INFO - Chain [1] start processing
23:16:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

23:16:44 - cmdstanpy - INFO - Chain [1] start processing
23:16:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:16:45 - cmdstanpy - INFO - Chain [1] start processing
23:16:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

23:16:46 - cmdstanpy - INFO - Chain [1] start processing
23:16:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

23:16:46 - cmdstanpy - INFO - Chain [1] start processing
23:16:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

23:16:47 - cmdstanpy - INFO - Chain [1] start processing
23:16:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:16:48 - cmdstanpy - INFO - Chain [1] start processing
23:16:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:16:48 - cmdstanpy - INFO - Chain [1] start processing
23:16:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:16:49 - cmdstanpy - INFO - Chain [1] start processing
23:16:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:16:50 - cmdstanpy - INFO - Chain [1] start processing
23:16:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

23:16:50 - cmdstanpy - INFO - Chain [1] start processing
23:16:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

23:16:51 - cmdstanpy - INFO - Chain [1] start processing
23:16:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

23:16:52 - cmdstanpy - INFO - Chain [1] start processing
23:16:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:16:53 - cmdstanpy - INFO - Chain [1] start processing
23:16:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:16:53 - cmdstanpy - INFO - Chain [1] start processing
23:16:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:16:54 - cmdstanpy - INFO - Chain [1] start processing
23:16:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

23:16:55 - cmdstanpy - INFO - Chain [1] start processing
23:16:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

23:16:55 - cmdstanpy - INFO - Chain [1] start processing
23:16:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:16:56 - cmdstanpy - INFO - Chain [1] start processing
23:16:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

23:16:57 - cmdstanpy - INFO - Chain [1] start processing
23:16:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:16:58 - cmdstanpy - INFO - Chain [1] start processing
23:16:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:16:58 - cmdstanpy - INFO - Chain [1] start processing
23:16:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

23:16:59 - cmdstanpy - INFO - Chain [1] start processing
23:16:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

23:16:59 - cmdstanpy - INFO - Chain [1] start processing
23:17:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:17:00 - cmdstanpy - INFO - Chain [1] start processing
23:17:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:17:01 - cmdstanpy - INFO - Chain [1] start processing
23:17:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:17:01 - cmdstanpy - INFO - Chain [1] start processing
23:17:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

23:17:02 - cmdstanpy - INFO - Chain [1] start processing
23:17:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

23:17:03 - cmdstanpy - INFO - Chain [1] start processing
23:17:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:17:03 - cmdstanpy - INFO - Chain [1] start processing
23:17:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:17:04 - cmdstanpy - INFO - Chain [1] start processing
23:17:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

23:17:05 - cmdstanpy - INFO - Chain [1] start processing
23:17:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:17:05 - cmdstanpy - INFO - Chain [1] start processing
23:17:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:17:06 - cmdstanpy - INFO - Chain [1] start processing
23:17:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

23:17:07 - cmdstanpy - INFO - Chain [1] start processing
23:17:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:17:07 - cmdstanpy - INFO - Chain [1] start processing
23:17:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:17:08 - cmdstanpy - INFO - Chain [1] start processing
23:17:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:17:09 - cmdstanpy - INFO - Chain [1] start processing
23:17:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:17:10 - cmdstanpy - INFO - Chain [1] start processing
23:17:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:17:10 - cmdstanpy - INFO - Chain [1] start processing
23:17:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:17:11 - cmdstanpy - INFO - Chain [1] start processing
23:17:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:17:12 - cmdstanpy - INFO - Chain [1] start processing
23:17:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

23:17:12 - cmdstanpy - INFO - Chain [1] start processing
23:17:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:17:13 - cmdstanpy - INFO - Chain [1] start processing
23:17:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

23:17:14 - cmdstanpy - INFO - Chain [1] start processing
23:17:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

23:17:15 - cmdstanpy - INFO - Chain [1] start processing
23:17:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

23:17:16 - cmdstanpy - INFO - Chain [1] start processing
23:17:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:17:16 - cmdstanpy - INFO - Chain [1] start processing
23:17:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:17:17 - cmdstanpy - INFO - Chain [1] start processing
23:17:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:17:18 - cmdstanpy - INFO - Chain [1] start processing
23:17:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:17:19 - cmdstanpy - INFO - Chain [1] start processing
23:17:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:17:19 - cmdstanpy - INFO - Chain [1] start processing
23:17:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:17:20 - cmdstanpy - INFO - Chain [1] start processing
23:17:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:17:20 - cmdstanpy - INFO - Chain [1] start processing
23:17:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

23:17:21 - cmdstanpy - INFO - Chain [1] start processing
23:17:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:17:22 - cmdstanpy - INFO - Chain [1] start processing
23:17:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:17:23 - cmdstanpy - INFO - Chain [1] start processing
23:17:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:17:23 - cmdstanpy - INFO - Chain [1] start processing
23:17:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:17:24 - cmdstanpy - INFO - Chain [1] start processing
23:17:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:17:25 - cmdstanpy - INFO - Chain [1] start processing
23:17:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:17:26 - cmdstanpy - INFO - Chain [1] start processing
23:17:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:17:26 - cmdstanpy - INFO - Chain [1] start processing
23:17:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:17:27 - cmdstanpy - INFO - Chain [1] start processing
23:17:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

23:17:28 - cmdstanpy - INFO - Chain [1] start processing
23:17:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:17:28 - cmdstanpy - INFO - Chain [1] start processing
23:17:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:17:29 - cmdstanpy - INFO - Chain [1] start processing
23:17:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:17:30 - cmdstanpy - INFO - Chain [1] start processing
23:17:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:17:30 - cmdstanpy - INFO - Chain [1] start processing
23:17:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:17:31 - cmdstanpy - INFO - Chain [1] start processing
23:17:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:17:32 - cmdstanpy - INFO - Chain [1] start processing
23:17:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:17:32 - cmdstanpy - INFO - Chain [1] start processing
23:17:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:17:33 - cmdstanpy - INFO - Chain [1] start processing
23:17:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:17:34 - cmdstanpy - INFO - Chain [1] start processing
23:17:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

23:17:35 - cmdstanpy - INFO - Chain [1] start processing
23:17:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

23:17:35 - cmdstanpy - INFO - Chain [1] start processing
23:17:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:17:36 - cmdstanpy - INFO - Chain [1] start processing
23:17:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:17:37 - cmdstanpy - INFO - Chain [1] start processing
23:17:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:17:37 - cmdstanpy - INFO - Chain [1] start processing
23:17:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:17:38 - cmdstanpy - INFO - Chain [1] start processing
23:17:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:17:39 - cmdstanpy - INFO - Chain [1] start processing
23:17:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:17:40 - cmdstanpy - INFO - Chain [1] start processing
23:17:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:17:41 - cmdstanpy - INFO - Chain [1] start processing
23:17:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:17:41 - cmdstanpy - INFO - Chain [1] start processing
23:17:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:17:42 - cmdstanpy - INFO - Chain [1] start processing
23:17:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:17:43 - cmdstanpy - INFO - Chain [1] start processing
23:17:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:17:43 - cmdstanpy - INFO - Chain [1] start processing
23:17:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:17:44 - cmdstanpy - INFO - Chain [1] start processing
23:17:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:17:45 - cmdstanpy - INFO - Chain [1] start processing
23:17:45 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 5 / 10....

23:17:46 - cmdstanpy - INFO - Chain [1] start processing
23:17:46 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:17:47 - cmdstanpy - INFO - Chain [1] start processing
23:17:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:17:49 - cmdstanpy - INFO - Chain [1] start processing
23:17:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:17:49 - cmdstanpy - INFO - Chain [1] start processing
23:17:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

23:17:49 - cmdstanpy - INFO - Chain [1] start processing
23:17:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

23:17:50 - cmdstanpy - INFO - Chain [1] start processing
23:17:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

23:17:50 - cmdstanpy - INFO - Chain [1] start processing
23:17:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:17:51 - cmdstanpy - INFO - Chain [1] start processing
23:17:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

23:17:52 - cmdstanpy - INFO - Chain [1] start processing
23:17:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

23:17:52 - cmdstanpy - INFO - Chain [1] start processing
23:17:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

23:17:53 - cmdstanpy - INFO - Chain [1] start processing
23:17:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:17:54 - cmdstanpy - INFO - Chain [1] start processing
23:17:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

23:17:54 - cmdstanpy - INFO - Chain [1] start processing
23:17:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

23:17:55 - cmdstanpy - INFO - Chain [1] start processing
23:17:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:17:55 - cmdstanpy - INFO - Chain [1] start processing
23:17:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

23:17:56 - cmdstanpy - INFO - Chain [1] start processing
23:17:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

23:17:56 - cmdstanpy - INFO - Chain [1] start processing
23:17:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

23:17:57 - cmdstanpy - INFO - Chain [1] start processing
23:17:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:17:57 - cmdstanpy - INFO - Chain [1] start processing
23:17:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:17:58 - cmdstanpy - INFO - Chain [1] start processing
23:17:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:17:58 - cmdstanpy - INFO - Chain [1] start processing
23:17:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:17:59 - cmdstanpy - INFO - Chain [1] start processing
23:17:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

23:18:00 - cmdstanpy - INFO - Chain [1] start processing
23:18:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

23:18:00 - cmdstanpy - INFO - Chain [1] start processing
23:18:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

23:18:01 - cmdstanpy - INFO - Chain [1] start processing
23:18:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:18:01 - cmdstanpy - INFO - Chain [1] start processing
23:18:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:18:02 - cmdstanpy - INFO - Chain [1] start processing
23:18:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:18:02 - cmdstanpy - INFO - Chain [1] start processing
23:18:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

23:18:03 - cmdstanpy - INFO - Chain [1] start processing
23:18:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

23:18:04 - cmdstanpy - INFO - Chain [1] start processing
23:18:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:18:04 - cmdstanpy - INFO - Chain [1] start processing
23:18:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

23:18:05 - cmdstanpy - INFO - Chain [1] start processing
23:18:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:18:05 - cmdstanpy - INFO - Chain [1] start processing
23:18:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:18:06 - cmdstanpy - INFO - Chain [1] start processing
23:18:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

23:18:07 - cmdstanpy - INFO - Chain [1] start processing
23:18:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

23:18:07 - cmdstanpy - INFO - Chain [1] start processing
23:18:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:18:08 - cmdstanpy - INFO - Chain [1] start processing
23:18:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:18:08 - cmdstanpy - INFO - Chain [1] start processing
23:18:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:18:09 - cmdstanpy - INFO - Chain [1] start processing
23:18:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

23:18:10 - cmdstanpy - INFO - Chain [1] start processing
23:18:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

23:18:10 - cmdstanpy - INFO - Chain [1] start processing
23:18:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:18:11 - cmdstanpy - INFO - Chain [1] start processing
23:18:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:18:11 - cmdstanpy - INFO - Chain [1] start processing
23:18:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

23:18:12 - cmdstanpy - INFO - Chain [1] start processing
23:18:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:18:12 - cmdstanpy - INFO - Chain [1] start processing
23:18:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:18:13 - cmdstanpy - INFO - Chain [1] start processing
23:18:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

23:18:14 - cmdstanpy - INFO - Chain [1] start processing
23:18:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:18:14 - cmdstanpy - INFO - Chain [1] start processing
23:18:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:18:15 - cmdstanpy - INFO - Chain [1] start processing
23:18:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:18:15 - cmdstanpy - INFO - Chain [1] start processing
23:18:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:18:15 - cmdstanpy - INFO - Chain [1] start processing
23:18:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:18:16 - cmdstanpy - INFO - Chain [1] start processing
23:18:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:18:17 - cmdstanpy - INFO - Chain [1] start processing
23:18:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:18:17 - cmdstanpy - INFO - Chain [1] start processing
23:18:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

23:18:18 - cmdstanpy - INFO - Chain [1] start processing
23:18:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:18:19 - cmdstanpy - INFO - Chain [1] start processing
23:18:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

23:18:19 - cmdstanpy - INFO - Chain [1] start processing
23:18:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

23:18:20 - cmdstanpy - INFO - Chain [1] start processing
23:18:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

23:18:20 - cmdstanpy - INFO - Chain [1] start processing
23:18:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:18:21 - cmdstanpy - INFO - Chain [1] start processing
23:18:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:18:22 - cmdstanpy - INFO - Chain [1] start processing
23:18:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:18:22 - cmdstanpy - INFO - Chain [1] start processing
23:18:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:18:23 - cmdstanpy - INFO - Chain [1] start processing
23:18:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:18:24 - cmdstanpy - INFO - Chain [1] start processing
23:18:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:18:24 - cmdstanpy - INFO - Chain [1] start processing
23:18:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:18:25 - cmdstanpy - INFO - Chain [1] start processing
23:18:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

23:18:25 - cmdstanpy - INFO - Chain [1] start processing
23:18:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:18:26 - cmdstanpy - INFO - Chain [1] start processing
23:18:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:18:27 - cmdstanpy - INFO - Chain [1] start processing
23:18:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:18:27 - cmdstanpy - INFO - Chain [1] start processing
23:18:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:18:28 - cmdstanpy - INFO - Chain [1] start processing
23:18:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:18:29 - cmdstanpy - INFO - Chain [1] start processing
23:18:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:18:29 - cmdstanpy - INFO - Chain [1] start processing
23:18:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:18:30 - cmdstanpy - INFO - Chain [1] start processing
23:18:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:18:31 - cmdstanpy - INFO - Chain [1] start processing
23:18:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

23:18:31 - cmdstanpy - INFO - Chain [1] start processing
23:18:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:18:32 - cmdstanpy - INFO - Chain [1] start processing
23:18:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:18:32 - cmdstanpy - INFO - Chain [1] start processing
23:18:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:18:33 - cmdstanpy - INFO - Chain [1] start processing
23:18:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:18:34 - cmdstanpy - INFO - Chain [1] start processing
23:18:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:18:34 - cmdstanpy - INFO - Chain [1] start processing
23:18:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:18:35 - cmdstanpy - INFO - Chain [1] start processing
23:18:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:18:36 - cmdstanpy - INFO - Chain [1] start processing
23:18:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:18:36 - cmdstanpy - INFO - Chain [1] start processing
23:18:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:18:37 - cmdstanpy - INFO - Chain [1] start processing
23:18:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

23:18:37 - cmdstanpy - INFO - Chain [1] start processing
23:18:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

23:18:38 - cmdstanpy - INFO - Chain [1] start processing
23:18:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:18:38 - cmdstanpy - INFO - Chain [1] start processing
23:18:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:18:39 - cmdstanpy - INFO - Chain [1] start processing
23:18:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:18:40 - cmdstanpy - INFO - Chain [1] start processing
23:18:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:18:40 - cmdstanpy - INFO - Chain [1] start processing
23:18:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:18:41 - cmdstanpy - INFO - Chain [1] start processing
23:18:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:18:42 - cmdstanpy - INFO - Chain [1] start processing
23:18:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:18:42 - cmdstanpy - INFO - Chain [1] start processing
23:18:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:18:43 - cmdstanpy - INFO - Chain [1] start processing
23:18:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:18:43 - cmdstanpy - INFO - Chain [1] start processing
23:18:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:18:44 - cmdstanpy - INFO - Chain [1] start processing
23:18:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:18:45 - cmdstanpy - INFO - Chain [1] start processing
23:18:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:18:45 - cmdstanpy - INFO - Chain [1] start processing
23:18:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:18:46 - cmdstanpy - INFO - Chain [1] start processing
23:18:47 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 6 / 10....

23:18:47 - cmdstanpy - INFO - Chain [1] start processing
23:18:48 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:18:49 - cmdstanpy - INFO - Chain [1] start processing
23:18:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:18:49 - cmdstanpy - INFO - Chain [1] start processing
23:18:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:18:50 - cmdstanpy - INFO - Chain [1] start processing
23:18:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

23:18:51 - cmdstanpy - INFO - Chain [1] start processing
23:18:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

23:18:51 - cmdstanpy - INFO - Chain [1] start processing
23:18:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

23:18:52 - cmdstanpy - INFO - Chain [1] start processing
23:18:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:18:52 - cmdstanpy - INFO - Chain [1] start processing
23:18:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

23:18:53 - cmdstanpy - INFO - Chain [1] start processing
23:18:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

23:18:53 - cmdstanpy - INFO - Chain [1] start processing
23:18:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

23:18:54 - cmdstanpy - INFO - Chain [1] start processing
23:18:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:18:54 - cmdstanpy - INFO - Chain [1] start processing
23:18:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

23:18:55 - cmdstanpy - INFO - Chain [1] start processing
23:18:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

23:18:55 - cmdstanpy - INFO - Chain [1] start processing
23:18:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:18:56 - cmdstanpy - INFO - Chain [1] start processing
23:18:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

23:18:56 - cmdstanpy - INFO - Chain [1] start processing
23:18:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

23:18:57 - cmdstanpy - INFO - Chain [1] start processing
23:18:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

23:18:57 - cmdstanpy - INFO - Chain [1] start processing
23:18:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:18:58 - cmdstanpy - INFO - Chain [1] start processing
23:18:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:18:58 - cmdstanpy - INFO - Chain [1] start processing
23:18:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:18:59 - cmdstanpy - INFO - Chain [1] start processing
23:18:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:18:59 - cmdstanpy - INFO - Chain [1] start processing
23:18:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

23:19:00 - cmdstanpy - INFO - Chain [1] start processing
23:19:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

23:19:00 - cmdstanpy - INFO - Chain [1] start processing
23:19:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

23:19:01 - cmdstanpy - INFO - Chain [1] start processing
23:19:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:19:02 - cmdstanpy - INFO - Chain [1] start processing
23:19:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:19:02 - cmdstanpy - INFO - Chain [1] start processing
23:19:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:19:03 - cmdstanpy - INFO - Chain [1] start processing
23:19:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

23:19:03 - cmdstanpy - INFO - Chain [1] start processing
23:19:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

23:19:03 - cmdstanpy - INFO - Chain [1] start processing
23:19:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:19:04 - cmdstanpy - INFO - Chain [1] start processing
23:19:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

23:19:04 - cmdstanpy - INFO - Chain [1] start processing
23:19:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:19:05 - cmdstanpy - INFO - Chain [1] start processing
23:19:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:19:05 - cmdstanpy - INFO - Chain [1] start processing
23:19:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

23:19:06 - cmdstanpy - INFO - Chain [1] start processing
23:19:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

23:19:07 - cmdstanpy - INFO - Chain [1] start processing
23:19:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:19:07 - cmdstanpy - INFO - Chain [1] start processing
23:19:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:19:08 - cmdstanpy - INFO - Chain [1] start processing
23:19:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:19:08 - cmdstanpy - INFO - Chain [1] start processing
23:19:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

23:19:09 - cmdstanpy - INFO - Chain [1] start processing
23:19:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

23:19:09 - cmdstanpy - INFO - Chain [1] start processing
23:19:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:19:10 - cmdstanpy - INFO - Chain [1] start processing
23:19:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:19:10 - cmdstanpy - INFO - Chain [1] start processing
23:19:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

23:19:11 - cmdstanpy - INFO - Chain [1] start processing
23:19:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:19:11 - cmdstanpy - INFO - Chain [1] start processing
23:19:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:19:12 - cmdstanpy - INFO - Chain [1] start processing
23:19:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

23:19:12 - cmdstanpy - INFO - Chain [1] start processing
23:19:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:19:13 - cmdstanpy - INFO - Chain [1] start processing
23:19:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:19:13 - cmdstanpy - INFO - Chain [1] start processing
23:19:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:19:14 - cmdstanpy - INFO - Chain [1] start processing
23:19:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:19:14 - cmdstanpy - INFO - Chain [1] start processing
23:19:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:19:15 - cmdstanpy - INFO - Chain [1] start processing
23:19:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:19:15 - cmdstanpy - INFO - Chain [1] start processing
23:19:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:19:16 - cmdstanpy - INFO - Chain [1] start processing
23:19:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

23:19:17 - cmdstanpy - INFO - Chain [1] start processing
23:19:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:19:17 - cmdstanpy - INFO - Chain [1] start processing
23:19:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

23:19:18 - cmdstanpy - INFO - Chain [1] start processing
23:19:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

23:19:18 - cmdstanpy - INFO - Chain [1] start processing
23:19:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

23:19:19 - cmdstanpy - INFO - Chain [1] start processing
23:19:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:19:19 - cmdstanpy - INFO - Chain [1] start processing
23:19:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:19:20 - cmdstanpy - INFO - Chain [1] start processing
23:19:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:19:21 - cmdstanpy - INFO - Chain [1] start processing
23:19:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:19:21 - cmdstanpy - INFO - Chain [1] start processing
23:19:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:19:22 - cmdstanpy - INFO - Chain [1] start processing
23:19:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:19:23 - cmdstanpy - INFO - Chain [1] start processing
23:19:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:19:23 - cmdstanpy - INFO - Chain [1] start processing
23:19:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

23:19:24 - cmdstanpy - INFO - Chain [1] start processing
23:19:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:19:24 - cmdstanpy - INFO - Chain [1] start processing
23:19:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:19:25 - cmdstanpy - INFO - Chain [1] start processing
23:19:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:19:25 - cmdstanpy - INFO - Chain [1] start processing
23:19:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:19:26 - cmdstanpy - INFO - Chain [1] start processing
23:19:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:19:26 - cmdstanpy - INFO - Chain [1] start processing
23:19:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:19:27 - cmdstanpy - INFO - Chain [1] start processing
23:19:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:19:27 - cmdstanpy - INFO - Chain [1] start processing
23:19:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:19:28 - cmdstanpy - INFO - Chain [1] start processing
23:19:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

23:19:29 - cmdstanpy - INFO - Chain [1] start processing
23:19:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:19:30 - cmdstanpy - INFO - Chain [1] start processing
23:19:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:19:30 - cmdstanpy - INFO - Chain [1] start processing
23:19:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:19:31 - cmdstanpy - INFO - Chain [1] start processing
23:19:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:19:31 - cmdstanpy - INFO - Chain [1] start processing
23:19:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:19:32 - cmdstanpy - INFO - Chain [1] start processing
23:19:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:19:32 - cmdstanpy - INFO - Chain [1] start processing
23:19:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:19:33 - cmdstanpy - INFO - Chain [1] start processing
23:19:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:19:33 - cmdstanpy - INFO - Chain [1] start processing
23:19:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:19:34 - cmdstanpy - INFO - Chain [1] start processing
23:19:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

23:19:34 - cmdstanpy - INFO - Chain [1] start processing
23:19:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

23:19:35 - cmdstanpy - INFO - Chain [1] start processing
23:19:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:19:36 - cmdstanpy - INFO - Chain [1] start processing
23:19:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:19:36 - cmdstanpy - INFO - Chain [1] start processing
23:19:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:19:37 - cmdstanpy - INFO - Chain [1] start processing
23:19:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:19:37 - cmdstanpy - INFO - Chain [1] start processing
23:19:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:19:38 - cmdstanpy - INFO - Chain [1] start processing
23:19:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:19:38 - cmdstanpy - INFO - Chain [1] start processing
23:19:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:19:39 - cmdstanpy - INFO - Chain [1] start processing
23:19:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:19:40 - cmdstanpy - INFO - Chain [1] start processing
23:19:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:19:40 - cmdstanpy - INFO - Chain [1] start processing
23:19:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:19:41 - cmdstanpy - INFO - Chain [1] start processing
23:19:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:19:41 - cmdstanpy - INFO - Chain [1] start processing
23:19:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:19:42 - cmdstanpy - INFO - Chain [1] start processing
23:19:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:19:42 - cmdstanpy - INFO - Chain [1] start processing
23:19:43 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 7 / 10....

23:19:43 - cmdstanpy - INFO - Chain [1] start processing
23:19:44 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:19:45 - cmdstanpy - INFO - Chain [1] start processing
23:19:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:19:45 - cmdstanpy - INFO - Chain [1] start processing
23:19:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:19:46 - cmdstanpy - INFO - Chain [1] start processing
23:19:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

23:19:46 - cmdstanpy - INFO - Chain [1] start processing
23:19:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

23:19:47 - cmdstanpy - INFO - Chain [1] start processing
23:19:47 - cmdstanpy - INFO - Chain [1] done processing
23:19:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  7  out of  100

23:19:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:19:47 - cmdstanpy - INFO - Chain [1] start processing
23:19:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

23:19:48 - cmdstanpy - INFO - Chain [1] start processing
23:19:48 - cmdstanpy - INFO - Chain [1] done processing
23:19:48 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  10  out of  100

23:19:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

23:19:49 - cmdstanpy - INFO - Chain [1] start processing
23:19:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:19:49 - cmdstanpy - INFO - Chain [1] start processing
23:19:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

23:19:49 - cmdstanpy - INFO - Chain [1] start processing
23:19:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

23:19:50 - cmdstanpy - INFO - Chain [1] start processing
23:19:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:19:50 - cmdstanpy - INFO - Chain [1] start processing
23:19:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

23:19:51 - cmdstanpy - INFO - Chain [1] start processing
23:19:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

23:19:51 - cmdstanpy - INFO - Chain [1] start processing
23:19:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

23:19:52 - cmdstanpy - INFO - Chain [1] start processing
23:19:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:19:52 - cmdstanpy - INFO - Chain [1] start processing
23:19:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:19:53 - cmdstanpy - INFO - Chain [1] start processing
23:19:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:19:53 - cmdstanpy - INFO - Chain [1] start processing
23:19:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:19:54 - cmdstanpy - INFO - Chain [1] start processing
23:19:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

23:19:54 - cmdstanpy - INFO - Chain [1] start processing
23:19:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

23:19:54 - cmdstanpy - INFO - Chain [1] start processing
23:19:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

23:19:55 - cmdstanpy - INFO - Chain [1] start processing
23:19:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:19:56 - cmdstanpy - INFO - Chain [1] start processing
23:19:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:19:56 - cmdstanpy - INFO - Chain [1] start processing
23:19:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:19:56 - cmdstanpy - INFO - Chain [1] start processing
23:19:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

23:19:57 - cmdstanpy - INFO - Chain [1] start processing
23:19:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

23:19:58 - cmdstanpy - INFO - Chain [1] start processing
23:19:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:19:58 - cmdstanpy - INFO - Chain [1] start processing
23:19:58 - cmdstanpy - INFO - Chain [1] done processing
23:19:58 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  32  out of  100

23:19:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:19:59 - cmdstanpy - INFO - Chain [1] start processing
23:19:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:19:59 - cmdstanpy - INFO - Chain [1] start processing
23:19:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

23:20:00 - cmdstanpy - INFO - Chain [1] start processing
23:20:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

23:20:00 - cmdstanpy - INFO - Chain [1] start processing
23:20:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:20:01 - cmdstanpy - INFO - Chain [1] start processing
23:20:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:20:01 - cmdstanpy - INFO - Chain [1] start processing
23:20:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:20:02 - cmdstanpy - INFO - Chain [1] start processing
23:20:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

23:20:02 - cmdstanpy - INFO - Chain [1] start processing
23:20:02 - cmdstanpy - INFO - Chain [1] done processing
23:20:03 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  41  out of  100

23:20:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:20:03 - cmdstanpy - INFO - Chain [1] start processing
23:20:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:20:04 - cmdstanpy - INFO - Chain [1] start processing
23:20:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

23:20:04 - cmdstanpy - INFO - Chain [1] start processing
23:20:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:20:05 - cmdstanpy - INFO - Chain [1] start processing
23:20:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:20:05 - cmdstanpy - INFO - Chain [1] start processing
23:20:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

23:20:06 - cmdstanpy - INFO - Chain [1] start processing
23:20:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:20:06 - cmdstanpy - INFO - Chain [1] start processing
23:20:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:20:06 - cmdstanpy - INFO - Chain [1] start processing
23:20:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:20:07 - cmdstanpy - INFO - Chain [1] start processing
23:20:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:20:07 - cmdstanpy - INFO - Chain [1] start processing
23:20:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:20:08 - cmdstanpy - INFO - Chain [1] start processing
23:20:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:20:08 - cmdstanpy - INFO - Chain [1] start processing
23:20:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:20:09 - cmdstanpy - INFO - Chain [1] start processing
23:20:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

23:20:09 - cmdstanpy - INFO - Chain [1] start processing
23:20:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:20:09 - cmdstanpy - INFO - Chain [1] start processing
23:20:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

23:20:10 - cmdstanpy - INFO - Chain [1] start processing
23:20:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

23:20:10 - cmdstanpy - INFO - Chain [1] start processing
23:20:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

23:20:11 - cmdstanpy - INFO - Chain [1] start processing
23:20:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:20:11 - cmdstanpy - INFO - Chain [1] start processing
23:20:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:20:12 - cmdstanpy - INFO - Chain [1] start processing
23:20:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:20:12 - cmdstanpy - INFO - Chain [1] start processing
23:20:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:20:13 - cmdstanpy - INFO - Chain [1] start processing
23:20:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:20:13 - cmdstanpy - INFO - Chain [1] start processing
23:20:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:20:14 - cmdstanpy - INFO - Chain [1] start processing
23:20:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:20:14 - cmdstanpy - INFO - Chain [1] start processing
23:20:15 - cmdstanpy - INFO - Chain [1] done processing
23:20:15 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  67  out of  100

23:20:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:20:15 - cmdstanpy - INFO - Chain [1] start processing
23:20:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:20:16 - cmdstanpy - INFO - Chain [1] start processing
23:20:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:20:16 - cmdstanpy - INFO - Chain [1] start processing
23:20:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:20:17 - cmdstanpy - INFO - Chain [1] start processing
23:20:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:20:17 - cmdstanpy - INFO - Chain [1] start processing
23:20:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:20:18 - cmdstanpy - INFO - Chain [1] start processing
23:20:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:20:18 - cmdstanpy - INFO - Chain [1] start processing
23:20:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:20:19 - cmdstanpy - INFO - Chain [1] start processing
23:20:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

23:20:19 - cmdstanpy - INFO - Chain [1] start processing
23:20:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:20:20 - cmdstanpy - INFO - Chain [1] start processing
23:20:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:20:20 - cmdstanpy - INFO - Chain [1] start processing
23:20:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:20:21 - cmdstanpy - INFO - Chain [1] start processing
23:20:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:20:21 - cmdstanpy - INFO - Chain [1] start processing
23:20:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:20:22 - cmdstanpy - INFO - Chain [1] start processing
23:20:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:20:22 - cmdstanpy - INFO - Chain [1] start processing
23:20:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:20:23 - cmdstanpy - INFO - Chain [1] start processing
23:20:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:20:23 - cmdstanpy - INFO - Chain [1] start processing
23:20:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:20:23 - cmdstanpy - INFO - Chain [1] start processing
23:20:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

23:20:24 - cmdstanpy - INFO - Chain [1] start processing
23:20:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

23:20:25 - cmdstanpy - INFO - Chain [1] start processing
23:20:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:20:25 - cmdstanpy - INFO - Chain [1] start processing
23:20:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:20:26 - cmdstanpy - INFO - Chain [1] start processing
23:20:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:20:26 - cmdstanpy - INFO - Chain [1] start processing
23:20:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:20:27 - cmdstanpy - INFO - Chain [1] start processing
23:20:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:20:27 - cmdstanpy - INFO - Chain [1] start processing
23:20:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:20:27 - cmdstanpy - INFO - Chain [1] start processing
23:20:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:20:28 - cmdstanpy - INFO - Chain [1] start processing
23:20:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:20:28 - cmdstanpy - INFO - Chain [1] start processing
23:20:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:20:29 - cmdstanpy - INFO - Chain [1] start processing
23:20:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:20:30 - cmdstanpy - INFO - Chain [1] start processing
23:20:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:20:30 - cmdstanpy - INFO - Chain [1] start processing
23:20:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:20:31 - cmdstanpy - INFO - Chain [1] start processing
23:20:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:20:31 - cmdstanpy - INFO - Chain [1] start processing
23:20:31 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 8 / 10....

23:20:32 - cmdstanpy - INFO - Chain [1] start processing
23:20:32 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

23:20:33 - cmdstanpy - INFO - Chain [1] start processing
23:20:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

23:20:33 - cmdstanpy - INFO - Chain [1] start processing
23:20:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

23:20:33 - cmdstanpy - INFO - Chain [1] start processing
23:20:34 - cmdstanpy - INFO - Chain [1] done processing
23:20:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  5  out of  100

23:20:34 - cmdstanpy - INFO - Chain [1] done processing
23:20:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  6  out of  100

23:20:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

23:20:35 - cmdstanpy - INFO - Chain [1] start processing
23:20:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

23:20:35 - cmdstanpy - INFO - Chain [1] start processing
23:20:35 - cmdstanpy - INFO - Chain [1] done processing
23:20:35 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  9  out of  100

23:20:35 - cmdstanpy - INFO - Chain [1] done processing
23:20:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  10  out of  100

23:20:36 - cmdstanpy - INFO - Chain [1] done processing
23:20:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  11  out of  100

23:20:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

23:20:36 - cmdstanpy - INFO - Chain [1] start processing
23:20:36 - cmdstanpy - INFO - Chain [1] done processing
23:20:37 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  13  out of  100

23:20:37 - cmdstanpy - INFO - Chain [1] done processing
23:20:37 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  14  out of  100

23:20:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

23:20:37 - cmdstanpy - INFO - Chain [1] start processing
23:20:37 - cmdstanpy - INFO - Chain [1] done processing
23:20:38 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  16  out of  100

23:20:38 - cmdstanpy - INFO - Chain [1] done processing
23:20:38 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  17  out of  100

23:20:38 - cmdstanpy - INFO - Chain [1] done processing
23:20:39 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  18  out of  100

23:20:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

23:20:39 - cmdstanpy - INFO - Chain [1] start processing
23:20:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

23:20:39 - cmdstanpy - INFO - Chain [1] start processing
23:20:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

23:20:40 - cmdstanpy - INFO - Chain [1] start processing
23:20:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

23:20:40 - cmdstanpy - INFO - Chain [1] start processing
23:20:40 - cmdstanpy - INFO - Chain [1] done processing
23:20:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  23  out of  100

23:20:41 - cmdstanpy - INFO - Chain [1] done processing
23:20:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  24  out of  100

23:20:41 - cmdstanpy - INFO - Chain [1] done processing
23:20:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  25  out of  100

23:20:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

23:20:42 - cmdstanpy - INFO - Chain [1] start processing
23:20:42 - cmdstanpy - INFO - Chain [1] done processing
23:20:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  27  out of  100

23:20:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

23:20:42 - cmdstanpy - INFO - Chain [1] start processing
23:20:43 - cmdstanpy - INFO - Chain [1] done processing
23:20:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  29  out of  100

23:20:43 - cmdstanpy - INFO - Chain [1] done processing
23:20:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  30  out of  100

23:20:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

23:20:44 - cmdstanpy - INFO - Chain [1] start processing
23:20:44 - cmdstanpy - INFO - Chain [1] done processing
23:20:44 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  32  out of  100

23:20:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

23:20:44 - cmdstanpy - INFO - Chain [1] start processing
23:20:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

23:20:45 - cmdstanpy - INFO - Chain [1] start processing
23:20:45 - cmdstanpy - INFO - Chain [1] done processing
23:20:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  35  out of  100

23:20:45 - cmdstanpy - INFO - Chain [1] done processing
23:20:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  36  out of  100

23:20:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

23:20:46 - cmdstanpy - INFO - Chain [1] start processing
23:20:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

23:20:46 - cmdstanpy - INFO - Chain [1] start processing
23:20:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:20:47 - cmdstanpy - INFO - Chain [1] start processing
23:20:47 - cmdstanpy - INFO - Chain [1] done processing
23:20:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  40  out of  100

23:20:47 - cmdstanpy - INFO - Chain [1] done processing
23:20:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  41  out of  100

23:20:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

23:20:48 - cmdstanpy - INFO - Chain [1] start processing
23:20:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

23:20:48 - cmdstanpy - INFO - Chain [1] start processing
23:20:48 - cmdstanpy - INFO - Chain [1] done processing
23:20:49 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  44  out of  100

23:20:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

23:20:49 - cmdstanpy - INFO - Chain [1] start processing
23:20:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

23:20:50 - cmdstanpy - INFO - Chain [1] start processing
23:20:50 - cmdstanpy - INFO - Chain [1] done processing
23:20:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  47  out of  100

23:20:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

23:20:50 - cmdstanpy - INFO - Chain [1] start processing
23:20:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

23:20:51 - cmdstanpy - INFO - Chain [1] start processing
23:20:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

23:20:51 - cmdstanpy - INFO - Chain [1] start processing
23:20:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

23:20:52 - cmdstanpy - INFO - Chain [1] start processing
23:20:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

23:20:52 - cmdstanpy - INFO - Chain [1] start processing
23:20:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

23:20:52 - cmdstanpy - INFO - Chain [1] start processing
23:20:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

23:20:53 - cmdstanpy - INFO - Chain [1] start processing
23:20:53 - cmdstanpy - INFO - Chain [1] done processing
23:20:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  55  out of  100

23:20:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:20:54 - cmdstanpy - INFO - Chain [1] start processing
23:20:54 - cmdstanpy - INFO - Chain [1] done processing
23:20:54 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  57  out of  100

23:20:54 - cmdstanpy - INFO - Chain [1] done processing
23:20:54 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  58  out of  100

23:20:54 - cmdstanpy - INFO - Chain [1] done processing
23:20:55 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  59  out of  100

23:20:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

23:20:55 - cmdstanpy - INFO - Chain [1] start processing
23:20:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

23:20:56 - cmdstanpy - INFO - Chain [1] start processing
23:20:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

23:20:56 - cmdstanpy - INFO - Chain [1] start processing
23:20:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

23:20:56 - cmdstanpy - INFO - Chain [1] start processing
23:20:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

23:20:57 - cmdstanpy - INFO - Chain [1] start processing
23:20:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

23:20:57 - cmdstanpy - INFO - Chain [1] start processing
23:20:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

23:20:58 - cmdstanpy - INFO - Chain [1] start processing
23:20:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

23:20:58 - cmdstanpy - INFO - Chain [1] start processing
23:20:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

23:20:58 - cmdstanpy - INFO - Chain [1] start processing
23:20:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

23:20:59 - cmdstanpy - INFO - Chain [1] start processing
23:20:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

23:20:59 - cmdstanpy - INFO - Chain [1] start processing
23:20:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

23:21:00 - cmdstanpy - INFO - Chain [1] start processing
23:21:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

23:21:00 - cmdstanpy - INFO - Chain [1] start processing
23:21:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

23:21:01 - cmdstanpy - INFO - Chain [1] start processing
23:21:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

23:21:01 - cmdstanpy - INFO - Chain [1] start processing
23:21:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

23:21:02 - cmdstanpy - INFO - Chain [1] start processing
23:21:02 - cmdstanpy - INFO - Chain [1] done processing
23:21:02 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  76  out of  100

23:21:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:21:02 - cmdstanpy - INFO - Chain [1] start processing
23:21:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

23:21:03 - cmdstanpy - INFO - Chain [1] start processing
23:21:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:21:03 - cmdstanpy - INFO - Chain [1] start processing
23:21:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

23:21:04 - cmdstanpy - INFO - Chain [1] start processing
23:21:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

23:21:04 - cmdstanpy - INFO - Chain [1] start processing
23:21:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:21:04 - cmdstanpy - INFO - Chain [1] start processing
23:21:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

23:21:05 - cmdstanpy - INFO - Chain [1] start processing
23:21:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

23:21:05 - cmdstanpy - INFO - Chain [1] start processing
23:21:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:21:06 - cmdstanpy - INFO - Chain [1] start processing
23:21:06 - cmdstanpy - INFO - Chain [1] done processing
23:21:06 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  86  out of  100

23:21:06 - cmdstanpy - INFO - Chain [1] done processing
23:21:06 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  87  out of  100

23:21:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

23:21:07 - cmdstanpy - INFO - Chain [1] start processing
23:21:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:21:07 - cmdstanpy - INFO - Chain [1] start processing
23:21:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

23:21:08 - cmdstanpy - INFO - Chain [1] start processing
23:21:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:21:08 - cmdstanpy - INFO - Chain [1] start processing
23:21:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

23:21:09 - cmdstanpy - INFO - Chain [1] start processing
23:21:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

23:21:09 - cmdstanpy - INFO - Chain [1] start processing
23:21:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

23:21:09 - cmdstanpy - INFO - Chain [1] start processing
23:21:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

23:21:10 - cmdstanpy - INFO - Chain [1] start processing
23:21:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

23:21:10 - cmdstanpy - INFO - Chain [1] start processing
23:21:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:21:11 - cmdstanpy - INFO - Chain [1] start processing
23:21:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:21:11 - cmdstanpy - INFO - Chain [1] start processing
23:21:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

23:21:11 - cmdstanpy - INFO - Chain [1] start processing
23:21:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

23:21:12 - cmdstanpy - INFO - Chain [1] start processing
23:21:12 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 9 / 10....

23:21:12 - cmdstanpy - INFO - Chain [1] start processing
23:21:13 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)
23:21:13 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  1  out of  100
Processing i =  2  out of  100

23:21:13 - cmdstanpy - INFO - Chain [1] done processing
23:21:13 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  3  out of  100

23:21:13 - cmdstanpy - INFO - Chain [1] done processing
23:21:14 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  4  out of  100

23:21:14 - cmdstanpy - INFO - Chain [1] done processing
23:21:14 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  5  out of  100

23:21:14 - cmdstanpy - INFO - Chain [1] done processing
23:21:14 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  6  out of  100

23:21:14 - cmdstanpy - INFO - Chain [1] done processing
23:21:14 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  7  out of  100

23:21:15 - cmdstanpy - INFO - Chain [1] done processing
23:21:15 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  8  out of  100

23:21:15 - cmdstanpy - INFO - Chain [1] done processing
23:21:15 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  9  out of  100

23:21:15 - cmdstanpy - INFO - Chain [1] done processing
23:21:15 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  10  out of  100

23:21:15 - cmdstanpy - INFO - Chain [1] done processing
23:21:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  11  out of  100

23:21:16 - cmdstanpy - INFO - Chain [1] done processing
23:21:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  12  out of  100

23:21:16 - cmdstanpy - INFO - Chain [1] done processing
23:21:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  13  out of  100

23:21:16 - cmdstanpy - INFO - Chain [1] done processing
23:21:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  14  out of  100

23:21:17 - cmdstanpy - INFO - Chain [1] done processing
23:21:17 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  15  out of  100

23:21:17 - cmdstanpy - INFO - Chain [1] done processing
23:21:17 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  16  out of  100

23:21:17 - cmdstanpy - INFO - Chain [1] done processing
23:21:17 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  17  out of  100

23:21:17 - cmdstanpy - INFO - Chain [1] done processing
23:21:18 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  18  out of  100

23:21:18 - cmdstanpy - INFO - Chain [1] done processing
23:21:18 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  19  out of  100

23:21:18 - cmdstanpy - INFO - Chain [1] done processing
23:21:18 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  20  out of  100

23:21:18 - cmdstanpy - INFO - Chain [1] done processing
23:21:19 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  21  out of  100

23:21:19 - cmdstanpy - INFO - Chain [1] done processing
23:21:19 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  22  out of  100

23:21:19 - cmdstanpy - INFO - Chain [1] done processing
23:21:19 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  23  out of  100

23:21:19 - cmdstanpy - INFO - Chain [1] done processing
23:21:19 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  24  out of  100

23:21:20 - cmdstanpy - INFO - Chain [1] done processing
23:21:20 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  25  out of  100

23:21:20 - cmdstanpy - INFO - Chain [1] done processing
23:21:20 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  26  out of  100

23:21:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

23:21:20 - cmdstanpy - INFO - Chain [1] start processing
23:21:21 - cmdstanpy - INFO - Chain [1] done processing
23:21:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  28  out of  100

23:21:21 - cmdstanpy - INFO - Chain [1] done processing
23:21:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  29  out of  100

23:21:21 - cmdstanpy - INFO - Chain [1] done processing
23:21:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  30  out of  100

23:21:22 - cmdstanpy - INFO - Chain [1] done processing
23:21:22 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  31  out of  100

23:21:22 - cmdstanpy - INFO - Chain [1] done processing
23:21:22 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  32  out of  100

23:21:22 - cmdstanpy - INFO - Chain [1] done processing
23:21:22 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  33  out of  100

23:21:22 - cmdstanpy - INFO - Chain [1] done processing
23:21:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  34  out of  100

23:21:23 - cmdstanpy - INFO - Chain [1] done processing
23:21:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  35  out of  100

23:21:23 - cmdstanpy - INFO - Chain [1] done processing
23:21:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  36  out of  100

23:21:23 - cmdstanpy - INFO - Chain [1] done processing
23:21:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  37  out of  100

23:21:24 - cmdstanpy - INFO - Chain [1] done processing
23:21:24 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  38  out of  100

23:21:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

23:21:24 - cmdstanpy - INFO - Chain [1] start processing
23:21:24 - cmdstanpy - INFO - Chain [1] done processing
23:21:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  40  out of  100

23:21:25 - cmdstanpy - INFO - Chain [1] done processing
23:21:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  41  out of  100

23:21:25 - cmdstanpy - INFO - Chain [1] done processing
23:21:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  42  out of  100

23:21:25 - cmdstanpy - INFO - Chain [1] done processing
23:21:26 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  43  out of  100

23:21:26 - cmdstanpy - INFO - Chain [1] done processing
23:21:26 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  44  out of  100

23:21:26 - cmdstanpy - INFO - Chain [1] done processing
23:21:26 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  45  out of  100

23:21:26 - cmdstanpy - INFO - Chain [1] done processing
23:21:26 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  46  out of  100

23:21:27 - cmdstanpy - INFO - Chain [1] done processing
23:21:27 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  47  out of  100

23:21:27 - cmdstanpy - INFO - Chain [1] done processing
23:21:27 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  48  out of  100

23:21:27 - cmdstanpy - INFO - Chain [1] done processing
23:21:27 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  49  out of  100

23:21:28 - cmdstanpy - INFO - Chain [1] done processing
23:21:28 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  50  out of  100

23:21:28 - cmdstanpy - INFO - Chain [1] done processing
23:21:28 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  51  out of  100

23:21:28 - cmdstanpy - INFO - Chain [1] done processing
23:21:28 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  52  out of  100

23:21:28 - cmdstanpy - INFO - Chain [1] done processing
23:21:29 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  53  out of  100

23:21:29 - cmdstanpy - INFO - Chain [1] done processing
23:21:29 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  54  out of  100

23:21:29 - cmdstanpy - INFO - Chain [1] done processing
23:21:29 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  55  out of  100

23:21:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

23:21:30 - cmdstanpy - INFO - Chain [1] start processing
23:21:30 - cmdstanpy - INFO - Chain [1] done processing
23:21:30 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  57  out of  100

23:21:30 - cmdstanpy - INFO - Chain [1] done processing
23:21:30 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  58  out of  100

23:21:31 - cmdstanpy - INFO - Chain [1] done processing
23:21:31 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  59  out of  100

23:21:31 - cmdstanpy - INFO - Chain [1] done processing
23:21:31 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  60  out of  100

23:21:31 - cmdstanpy - INFO - Chain [1] done processing
23:21:31 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  61  out of  100

23:21:32 - cmdstanpy - INFO - Chain [1] done processing
23:21:32 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  62  out of  100

23:21:32 - cmdstanpy - INFO - Chain [1] done processing
23:21:32 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  63  out of  100

23:21:32 - cmdstanpy - INFO - Chain [1] done processing
23:21:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  64  out of  100

23:21:33 - cmdstanpy - INFO - Chain [1] done processing
23:21:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  65  out of  100

23:21:33 - cmdstanpy - INFO - Chain [1] done processing
23:21:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  66  out of  100

23:21:33 - cmdstanpy - INFO - Chain [1] done processing
23:21:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  67  out of  100

23:21:34 - cmdstanpy - INFO - Chain [1] done processing
23:21:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  68  out of  100

23:21:34 - cmdstanpy - INFO - Chain [1] done processing
23:21:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  69  out of  100

23:21:34 - cmdstanpy - INFO - Chain [1] done processing
23:21:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  70  out of  100

23:21:35 - cmdstanpy - INFO - Chain [1] done processing
23:21:35 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  71  out of  100

23:21:35 - cmdstanpy - INFO - Chain [1] done processing
23:21:35 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  72  out of  100

23:21:35 - cmdstanpy - INFO - Chain [1] done processing
23:21:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  73  out of  100

23:21:36 - cmdstanpy - INFO - Chain [1] done processing
23:21:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  74  out of  100

23:21:36 - cmdstanpy - INFO - Chain [1] done processing
23:21:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  75  out of  100

23:21:36 - cmdstanpy - INFO - Chain [1] done processing
23:21:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  76  out of  100

23:21:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

23:21:37 - cmdstanpy - INFO - Chain [1] start processing
23:21:37 - cmdstanpy - INFO - Chain [1] done processing
23:21:37 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  78  out of  100

23:21:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

23:21:38 - cmdstanpy - INFO - Chain [1] start processing
23:21:38 - cmdstanpy - INFO - Chain [1] done processing
23:21:38 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  80  out of  100

23:21:38 - cmdstanpy - INFO - Chain [1] done processing
23:21:38 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  81  out of  100

23:21:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

23:21:39 - cmdstanpy - INFO - Chain [1] start processing
23:21:39 - cmdstanpy - INFO - Chain [1] done processing
23:21:39 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  83  out of  100

23:21:39 - cmdstanpy - INFO - Chain [1] done processing
23:21:39 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  84  out of  100

23:21:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

23:21:40 - cmdstanpy - INFO - Chain [1] start processing
23:21:40 - cmdstanpy - INFO - Chain [1] done processing
23:21:40 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  86  out of  100

23:21:40 - cmdstanpy - INFO - Chain [1] done processing
23:21:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  87  out of  100

23:21:41 - cmdstanpy - INFO - Chain [1] done processing
23:21:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  88  out of  100

23:21:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

23:21:41 - cmdstanpy - INFO - Chain [1] start processing
23:21:41 - cmdstanpy - INFO - Chain [1] done processing
23:21:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  90  out of  100

23:21:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

23:21:42 - cmdstanpy - INFO - Chain [1] start processing
23:21:42 - cmdstanpy - INFO - Chain [1] done processing
23:21:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  92  out of  100

23:21:43 - cmdstanpy - INFO - Chain [1] done processing
23:21:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  93  out of  100

23:21:43 - cmdstanpy - INFO - Chain [1] done processing
23:21:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  94  out of  100

23:21:43 - cmdstanpy - INFO - Chain [1] done processing
23:21:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  95  out of  100

23:21:44 - cmdstanpy - INFO - Chain [1] done processing
23:21:44 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  96  out of  100

23:21:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

23:21:44 - cmdstanpy - INFO - Chain [1] start processing
23:21:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

23:21:45 - cmdstanpy - INFO - Chain [1] start processing
23:21:45 - cmdstanpy - INFO - Chain [1] done processing
23:21:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  99  out of  100

23:21:45 - cmdstanpy - INFO - Chain [1] done processing
23:21:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  100  out of  100

23:21:46 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 10 / 10....

23:21:47 - cmdstanpy - INFO - Chain [1] start processing
23:21:47 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)

Test set is before train set / CV 10, no test forecast can be made

[run 24/36] ds17 m4 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Processing i =  1  out of  1344
Processing i =  2  out of  1344
Processing i =  3  out of  1344
Processing i =  4  out of  1344
Processing i =  5  out of  1344
Processing i =  6  out of  1344
Processing i =  7  out of  1344
Processing i =  8  out of  1344
Processing i =  9  out of  1344
Processing i =  10  out of  1344
Processing i =  11  out of  1344
Processing i =  12  out of  1344
Processing i =  13  out of  1344
Processing i =  14  out of  1344
Processing i =  15  out of  1344
Processing i =  16  out of  1344
Processing i =  17  out of  1344
Processing i =  18  out of  1344
Processing i =  19  out of  1344
Processing i =  20  out of  1344
Processing i =  21  out of  1344
Processing i =  22  out of  1344
Processing i =  23  out of  1344
Processing i =  24  out of  1344
Processing i =  25  out of  1344
Processing i =  26  out of  1344
Processing i =  27  out of  1344
Processing i =  28  out of  1344
Processing i =  29  out of  1344
Processing i =  30  out of  1344
Processing i =  31  out of  1344
Processing i =  32  out of  1344
Processing i =  33  out of  1344
Processing i =  34  out of  1344
Processing i =  35  out of  1344
Processing i =  36  out of  1344
Processing i =  37  out of  1344
Processing i =  38  out of  1344
Processing i =  39  out of  1344
Processing i =  40  out of  1344
Processing i =  41  out of  1344
Processing i =  42  out of  1344
Processing i =  43  out of  1344
Processing i =  44  out of  1344
Processing i =  45  out of  1344
Processing i =  46  out of  1344
Processing i =  47  out of  1344
Processing i =  48  out of  1344
Processing i =  49  out of  1344
Processing i =  50  out of  1344
Processing i =  51  out of  1344
Processing i =  52  out of  1344
Processing i =  53  out of  1344
Processing i =  54  out of  1344
Processing i =  55  out of  1344
Processing i =  56  out of  1344
Processing i =  57  out of  1344
Processing i =  58  out of  1344
Processing i =  59  out of  1344
Processing i =  60  out of  1344
Processing i =  61  out of  1344
Processing i =  62  out of  1344
Processing i =  63  out of  1344
Processing i =  64  out of  1344
Processing i =  65  out of  1344
Processing i =  66  out of  1344
Processing i =  67  out of  1344
Processing i =  68  out of  1344
Processing i =  69  out of  1344
Processing i =  70  out of  1344
Processing i =  71  out of  1344
Processing i =  72  out of  1344
Processing i =  73  out of  1344
Processing i =  74  out of  1344
Processing i =  75  out of  1344
Processing i =  76  out of  1344
Processing i =  77  out of  1344
Processing i =  78  out of  1344
Processing i =  79  out of  1344
Processing i =  80  out of  1344
Processing i =  81  out of  1344
Processing i =  82  out of  1344
Processing i =  83  out of  1344
Processing i =  84  out of  1344
Processing i =  85  out of  1344
Processing i =  86  out of  1344
Processing i =  87  out of  1344
Processing i =  88  out of  1344
Processing i =  89  out of  1344
Processing i =  90  out of  1344
Processing i =  91  out of  1344
Processing i =  92  out of  1344
Processing i =  93  out of  1344
Processing i =  94  out of  1344
Processing i =  95  out of  1344
Processing i =  96  out of  1344
Processing i =  97  out of  1344
Processing i =  98  out of  1344
Processing i =  99  out of  1344
Processing i =  100  out of  1344
Processing i =  101  out of  1344
Processing i =  102  out of  1344
Processing i =  103  out of  1344
Processing i =  104  out of  1344
Processing i =  105  out of  1344
Processing i =  106  out of  1344
Processing i =  107  out of  1344
Processing i =  108  out of  1344
Processing i =  109  out of  1344
Processing i =  110  out of  1344
Processing i =  111  out of  1344
Processing i =  112  out of  1344
Processing i =  113  out of  1344
Processing i =  114  out of  1344
Processing i =  115  out of  1344
Processing i =  116  out of  1344
Processing i =  117  out of  1344
Processing i =  118  out of  1344
Processing i =  119  out of  1344
Processing i =  120  out of  1344
Processing i =  121  out of  1344
Processing i =  122  out of  1344
Processing i =  123  out of  1344
Processing i =  124  out of  1344
Processing i =  125  out of  1344
Processing i =  126  out of  1344
Processing i =  127  out of  1344
Processing i =  128  out of  1344
Processing i =  129  out of  1344
Processing i =  130  out of  1344
Processing i =  131  out of  1344
Processing i =  132  out of  1344
Processing i =  133  out of  1344
Processing i =  134  out of  1344
Processing i =  135  out of  1344
Processing i =  136  out of  1344
Processing i =  137  out of  1344
Processing i =  138  out of  1344
Processing i =  139  out of  1344
Processing i =  140  out of  1344
Processing i =  141  out of  1344
Processing i =  142  out of  1344
Processing i =  143  out of  1344
Processing i =  144  out of  1344
Processing i =  145  out of  1344
Processing i =  146  out of  1344
Processing i =  147  out of  1344
Processing i =  148  out of  1344
Processing i =  149  out of  1344
Processing i =  150  out of  1344
Processing i =  151  out of  1344
Processing i =  152  out of  1344
Processing i =  153  out of  1344
Processing i =  154  out of  1344
Processing i =  155  out of  1344
Processing i =  156  out of  1344
Processing i =  157  out of  1344
Processing i =  158  out of  1344
Processing i =  159  out of  1344
Processing i =  160  out of  1344
Processing i =  161  out of  1344
Processing i =  162  out of  1344
Processing i =  163  out of  1344
Processing i =  164  out of  1344
Processing i =  165  out of  1344
Processing i =  166  out of  1344
Processing i =  167  out of  1344
Processing i =  168  out of  1344
Processing i =  169  out of  1344
Processing i =  170  out of  1344
Processing i =  171  out of  1344
Processing i =  172  out of  1344
Processing i =  173  out of  1344
Processing i =  174  out of  1344
Processing i =  175  out of  1344
Processing i =  176  out of  1344
Processing i =  177  out of  1344
Processing i =  178  out of  1344
Processing i =  179  out of  1344
Processing i =  180  out of  1344
Processing i =  181  out of  1344
Processing i =  182  out of  1344
Processing i =  183  out of  1344
Processing i =  184  out of  1344
Processing i =  185  out of  1344
Processing i =  186  out of  1344
Processing i =  187  out of  1344
Processing i =  188  out of  1344
Processing i =  189  out of  1344
Processing i =  190  out of  1344
Processing i =  191  out of  1344
Processing i =  192  out of  1344
Processing i =  193  out of  1344
Processing i =  194  out of  1344
Processing i =  195  out of  1344
Processing i =  196  out of  1344
Processing i =  197  out of  1344
Processing i =  198  out of  1344
Processing i =  199  out of  1344
Processing i =  200  out of  1344
Processing i =  201  out of  1344
Processing i =  202  out of  1344
Processing i =  203  out of  1344
Processing i =  204  out of  1344
Processing i =  205  out of  1344
Processing i =  206  out of  1344
Processing i =  207  out of  1344
Processing i =  208  out of  1344
Processing i =  209  out of  1344
Processing i =  210  out of  1344
Processing i =  211  out of  1344
Processing i =  212  out of  1344
Processing i =  213  out of  1344
Processing i =  214  out of  1344
Processing i =  215  out of  1344
Processing i =  216  out of  1344
Processing i =  217  out of  1344
Processing i =  218  out of  1344
Processing i =  219  out of  1344
Processing i =  220  out of  1344
Processing i =  221  out of  1344
Processing i =  222  out of  1344
Processing i =  223  out of  1344
Processing i =  224  out of  1344
Processing i =  225  out of  1344
Processing i =  226  out of  1344
Processing i =  227  out of  1344
Processing i =  228  out of  1344
Processing i =  229  out of  1344
Processing i =  230  out of  1344
Processing i =  231  out of  1344
Processing i =  232  out of  1344
Processing i =  233  out of  1344
Processing i =  234  out of  1344
Processing i =  235  out of  1344
Processing i =  236  out of  1344
Processing i =  237  out of  1344
Processing i =  238  out of  1344
Processing i =  239  out of  1344
Processing i =  240  out of  1344
Processing i =  241  out of  1344
Processing i =  242  out of  1344
Processing i =  243  out of  1344
Processing i =  244  out of  1344
Processing i =  245  out of  1344
Processing i =  246  out of  1344
Processing i =  247  out of  1344
Processing i =  248  out of  1344
Processing i =  249  out of  1344
Processing i =  250  out of  1344
Processing i =  251  out of  1344
Processing i =  252  out of  1344
Processing i =  253  out of  1344
Processing i =  254  out of  1344
Processing i =  255  out of  1344
Processing i =  256  out of  1344
Processing i =  257  out of  1344
Processing i =  258  out of  1344
Processing i =  259  out of  1344
Processing i =  260  out of  1344
Processing i =  261  out of  1344
Processing i =  262  out of  1344
Processing i =  263  out of  1344
Processing i =  264  out of  1344
Processing i =  265  out of  1344
Processing i =  266  out of  1344
Processing i =  267  out of  1344
Processing i =  268  out of  1344
Processing i =  269  out of  1344
Processing i =  270  out of  1344
Processing i =  271  out of  1344
Processing i =  272  out of  1344
Processing i =  273  out of  1344
Processing i =  274  out of  1344
Processing i =  275  out of  1344
Processing i =  276  out of  1344
Processing i =  277  out of  1344
Processing i =  278  out of  1344
Processing i =  279  out of  1344
Processing i =  280  out of  1344
Processing i =  281  out of  1344
Processing i =  282  out of  1344
Processing i =  283  out of  1344
Processing i =  284  out of  1344
Processing i =  285  out of  1344
Processing i =  286  out of  1344
Processing i =  287  out of  1344
Processing i =  288  out of  1344
Processing i =  289  out of  1344
Processing i =  290  out of  1344
Processing i =  291  out of  1344
Processing i =  292  out of  1344
Processing i =  293  out of  1344
Processing i =  294  out of  1344
Processing i =  295  out of  1344
Processing i =  296  out of  1344
Processing i =  297  out of  1344
Processing i =  298  out of  1344
Processing i =  299  out of  1344
Processing i =  300  out of  1344
Processing i =  301  out of  1344
Processing i =  302  out of  1344
Processing i =  303  out of  1344
Processing i =  304  out of  1344
Processing i =  305  out of  1344
Processing i =  306  out of  1344
Processing i =  307  out of  1344
Processing i =  308  out of  1344
Processing i =  309  out of  1344
Processing i =  310  out of  1344
Processing i =  311  out of  1344
Processing i =  312  out of  1344
Processing i =  313  out of  1344
Processing i =  314  out of  1344
Processing i =  315  out of  1344
Processing i =  316  out of  1344
Processing i =  317  out of  1344
Processing i =  318  out of  1344
Processing i =  319  out of  1344
Processing i =  320  out of  1344
Processing i =  321  out of  1344
Processing i =  322  out of  1344
Processing i =  323  out of  1344
Processing i =  324  out of  1344
Processing i =  325  out of  1344
Processing i =  326  out of  1344
Processing i =  327  out of  1344
Processing i =  328  out of  1344
Processing i =  329  out of  1344
Processing i =  330  out of  1344
Processing i =  331  out of  1344
Processing i =  332  out of  1344
Processing i =  333  out of  1344
Processing i =  334  out of  1344
Processing i =  335  out of  1344
Processing i =  336  out of  1344
Processing i =  337  out of  1344
Processing i =  338  out of  1344
Processing i =  339  out of  1344
Processing i =  340  out of  1344
Processing i =  341  out of  1344
Processing i =  342  out of  1344
Processing i =  343  out of  1344
Processing i =  344  out of  1344
Processing i =  345  out of  1344
Processing i =  346  out of  1344
Processing i =  347  out of  1344
Processing i =  348  out of  1344
Processing i =  349  out of  1344
Processing i =  350  out of  1344
Processing i =  351  out of  1344
Processing i =  352  out of  1344
Processing i =  353  out of  1344
Processing i =  354  out of  1344
Processing i =  355  out of  1344
Processing i =  356  out of  1344
Processing i =  357  out of  1344
Processing i =  358  out of  1344
Processing i =  359  out of  1344
Processing i =  360  out of  1344
Processing i =  361  out of  1344
Processing i =  362  out of  1344
Processing i =  363  out of  1344
Processing i =  364  out of  1344
Processing i =  365  out of  1344
Processing i =  366  out of  1344
Processing i =  367  out of  1344
Processing i =  368  out of  1344
Processing i =  369  out of  1344
Processing i =  370  out of  1344
Processing i =  371  out of  1344
Processing i =  372  out of  1344
Processing i =  373  out of  1344
Processing i =  374  out of  1344
Processing i =  375  out of  1344
Processing i =  376  out of  1344
Processing i =  377  out of  1344
Processing i =  378  out of  1344
Processing i =  379  out of  1344
Processing i =  380  out of  1344
Processing i =  381  out of  1344
Processing i =  382  out of  1344
Processing i =  383  out of  1344
Processing i =  384  out of  1344
Processing i =  385  out of  1344
Processing i =  386  out of  1344
Processing i =  387  out of  1344
Processing i =  388  out of  1344
Processing i =  389  out of  1344
Processing i =  390  out of  1344
Processing i =  391  out of  1344
Processing i =  392  out of  1344
Processing i =  393  out of  1344
Processing i =  394  out of  1344
Processing i =  395  out of  1344
Processing i =  396  out of  1344
Processing i =  397  out of  1344
Processing i =  398  out of  1344
Processing i =  399  out of  1344
Processing i =  400  out of  1344
Processing i =  401  out of  1344
Processing i =  402  out of  1344
Processing i =  403  out of  1344
Processing i =  404  out of  1344
Processing i =  405  out of  1344
Processing i =  406  out of  1344
Processing i =  407  out of  1344
Processing i =  408  out of  1344
Processing i =  409  out of  1344
Processing i =  410  out of  1344
Processing i =  411  out of  1344
Processing i =  412  out of  1344
Processing i =  413  out of  1344
Processing i =  414  out of  1344
Processing i =  415  out of  1344
Processing i =  416  out of  1344
Processing i =  417  out of  1344
Processing i =  418  out of  1344
Processing i =  419  out of  1344
Processing i =  420  out of  1344
Processing i =  421  out of  1344
Processing i =  422  out of  1344
Processing i =  423  out of  1344
Processing i =  424  out of  1344
Processing i =  425  out of  1344
Processing i =  426  out of  1344
Processing i =  427  out of  1344
Processing i =  428  out of  1344
Processing i =  429  out of  1344
Processing i =  430  out of  1344
Processing i =  431  out of  1344
Processing i =  432  out of  1344
Processing i =  433  out of  1344
Processing i =  434  out of  1344
Processing i =  435  out of  1344
Processing i =  436  out of  1344
Processing i =  437  out of  1344
Processing i =  438  out of  1344
Processing i =  439  out of  1344
Processing i =  440  out of  1344
Processing i =  441  out of  1344
Processing i =  442  out of  1344
Processing i =  443  out of  1344
Processing i =  444  out of  1344
Processing i =  445  out of  1344
Processing i =  446  out of  1344
Processing i =  447  out of  1344
Processing i =  448  out of  1344
Processing i =  449  out of  1344
Processing i =  450  out of  1344
Processing i =  451  out of  1344
Processing i =  452  out of  1344
Processing i =  453  out of  1344
Processing i =  454  out of  1344
Processing i =  455  out of  1344
Processing i =  456  out of  1344
Processing i =  457  out of  1344
Processing i =  458  out of  1344
Processing i =  459  out of  1344
Processing i =  460  out of  1344
Processing i =  461  out of  1344
Processing i =  462  out of  1344
Processing i =  463  out of  1344
Processing i =  464  out of  1344
Processing i =  465  out of  1344
Processing i =  466  out of  1344
Processing i =  467  out of  1344
Processing i =  468  out of  1344
Processing i =  469  out of  1344
Processing i =  470  out of  1344
Processing i =  471  out of  1344
Processing i =  472  out of  1344
Processing i =  473  out of  1344
Processing i =  474  out of  1344
Processing i =  475  out of  1344
Processing i =  476  out of  1344
Processing i =  477  out of  1344
Processing i =  478  out of  1344
Processing i =  479  out of  1344
Processing i =  480  out of  1344
Processing i =  481  out of  1344
Processing i =  482  out of  1344
Processing i =  483  out of  1344
Processing i =  484  out of  1344
Processing i =  485  out of  1344
Processing i =  486  out of  1344
Processing i =  487  out of  1344
Processing i =  488  out of  1344
Processing i =  489  out of  1344
Processing i =  490  out of  1344
Processing i =  491  out of  1344
Processing i =  492  out of  1344
Processing i =  493  out of  1344
Processing i =  494  out of  1344
Processing i =  495  out of  1344
Processing i =  496  out of  1344
Processing i =  497  out of  1344
Processing i =  498  out of  1344
Processing i =  499  out of  1344
Processing i =  500  out of  1344
Processing i =  501  out of  1344
Processing i =  502  out of  1344
Processing i =  503  out of  1344
Processing i =  504  out of  1344
Processing i =  505  out of  1344
Processing i =  506  out of  1344
Processing i =  507  out of  1344
Processing i =  508  out of  1344
Processing i =  509  out of  1344
Processing i =  510  out of  1344
Processing i =  511  out of  1344
Processing i =  512  out of  1344
Processing i =  513  out of  1344
Processing i =  514  out of  1344
Processing i =  515  out of  1344
Processing i =  516  out of  1344
Processing i =  517  out of  1344
Processing i =  518  out of  1344
Processing i =  519  out of  1344
Processing i =  520  out of  1344
Processing i =  521  out of  1344
Processing i =  522  out of  1344
Processing i =  523  out of  1344
Processing i =  524  out of  1344
Processing i =  525  out of  1344
Processing i =  526  out of  1344
Processing i =  527  out of  1344
Processing i =  528  out of  1344
Processing i =  529  out of  1344
Processing i =  530  out of  1344
Processing i =  531  out of  1344
Processing i =  532  out of  1344
Processing i =  533  out of  1344
Processing i =  534  out of  1344
Processing i =  535  out of  1344
Processing i =  536  out of  1344
Processing i =  537  out of  1344
Processing i =  538  out of  1344
Processing i =  539  out of  1344
Processing i =  540  out of  1344
Processing i =  541  out of  1344
Processing i =  542  out of  1344
Processing i =  543  out of  1344
Processing i =  544  out of  1344
Processing i =  545  out of  1344
Processing i =  546  out of  1344
Processing i =  547  out of  1344
Processing i =  548  out of  1344
Processing i =  549  out of  1344
Processing i =  550  out of  1344
Processing i =  551  out of  1344
Processing i =  552  out of  1344
Processing i =  553  out of  1344
Processing i =  554  out of  1344
Processing i =  555  out of  1344
Processing i =  556  out of  1344
Processing i =  557  out of  1344
Processing i =  558  out of  1344
Processing i =  559  out of  1344
Processing i =  560  out of  1344
Processing i =  561  out of  1344
Processing i =  562  out of  1344
Processing i =  563  out of  1344
Processing i =  564  out of  1344
Processing i =  565  out of  1344
Processing i =  566  out of  1344
Processing i =  567  out of  1344
Processing i =  568  out of  1344
Processing i =  569  out of  1344
Processing i =  570  out of  1344
Processing i =  571  out of  1344
Processing i =  572  out of  1344
Processing i =  573  out of  1344
Processing i =  574  out of  1344
Processing i =  575  out of  1344
Processing i =  576  out of  1344
Processing i =  577  out of  1344
Processing i =  578  out of  1344
Processing i =  579  out of  1344
Processing i =  580  out of  1344
Processing i =  581  out of  1344
Processing i =  582  out of  1344
Processing i =  583  out of  1344
Processing i =  584  out of  1344

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 2 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 3 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 4 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 5 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 6 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 7 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 8 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 9 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Processing CV 10 / 10....

c:\Users\z5404477\Documents\PyNNLF\.venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[run 29/36] ds18 m7 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Epoch [1/500], Loss: 38993.3516
Epoch [11/500], Loss: 5939.1665
Epoch [21/500], Loss: 3090.7715
Epoch [31/500], Loss: 2608.6638
Epoch [41/500], Loss: 1602.6512
Epoch [51/500], Loss: 1389.5741
Epoch [61/500], Loss: 1275.0051
Epoch [71/500], Loss: 1187.7120
Epoch [81/500], Loss: 1151.8303
Epoch [91/500], Loss: 1116.7100
Epoch [101/500], Loss: 1085.6631
Epoch [111/500], Loss: 1056.0319
Epoch [121/500], Loss: 1028.3722
Epoch [131/500], Loss: 1001.7453
Epoch [141/500], Loss: 976.2574
Epoch [151/500], Loss: 951.6761
Epoch [161/500], Loss: 927.7132
Epoch [171/500], Loss: 904.2194
Epoch [181/500], Loss: 880.9894
Epoch [191/500], Loss: 857.7592
Epoch [201/500], Loss: 833.9934
Epoch [211/500], Loss: 809.1293
Epoch [221/500], Loss: 783.3314
Epoch [231/500], Loss: 755.9783
Epoch [241/500], Loss: 728.6875
Epoch [251/500], Loss: 702.0242
Epoch [261/500], Loss: 678.5214
Epoch [271/500], Loss: 658.2220
Epoch [281/500], Loss: 639.7543
Epoch [291/500], Loss: 622.2131
Epoch [301/500], Loss: 605.3149
Epoch [311/500], Loss: 589.0602
Epoch [321/500], Loss: 573.4395
Epoch [331/500], Loss: 558.4174
Epoch [341/500], Loss: 543.9395
Epoch [351/500], Loss: 530.0820
Epoch [361/500], Loss: 516.8914
Epoch [371/500], Loss: 504.2690
Epoch [381/500], Loss: 492.2241
Epoch [391/500], Loss: 480.7067
Epoch [401/500], Loss: 469.6902
Epoch [411/500], Loss: 459.1502
Epoch [421/500], Loss: 449.1068
Epoch [431/500], Loss: 439.5209
Epoch [441/500], Loss: 430.3499
Epoch [451/500], Loss: 421.5784
Epoch [461/500], Loss: 413.2010
Epoch [471/500], Loss: 405.2059
Epoch [481/500], Loss: 397.5749
Epoch [491/500], Loss: 390.2554

Processing CV 2 / 10....
Epoch [1/500], Loss: 38476.0117
Epoch [11/500], Loss: 5644.2261
Epoch [21/500], Loss: 3154.3618
Epoch [31/500], Loss: 2592.1023
Epoch [41/500], Loss: 1638.7375
Epoch [51/500], Loss: 1423.7620
Epoch [61/500], Loss: 1300.6570
Epoch [71/500], Loss: 1213.2667
Epoch [81/500], Loss: 1175.4938
Epoch [91/500], Loss: 1138.2627
Epoch [101/500], Loss: 1105.1001
Epoch [111/500], Loss: 1073.7113
Epoch [121/500], Loss: 1044.4917
Epoch [131/500], Loss: 1016.5099
Epoch [141/500], Loss: 989.6751
Epoch [151/500], Loss: 963.8495
Epoch [161/500], Loss: 939.0060
Epoch [171/500], Loss: 914.7244
Epoch [181/500], Loss: 891.0326
Epoch [191/500], Loss: 867.3601
Epoch [201/500], Loss: 843.4864
Epoch [211/500], Loss: 819.3719
Epoch [221/500], Loss: 794.1885
Epoch [231/500], Loss: 766.5472
Epoch [241/500], Loss: 739.0613
Epoch [251/500], Loss: 713.9788
Epoch [261/500], Loss: 690.0715
Epoch [271/500], Loss: 667.1941
Epoch [281/500], Loss: 646.2938
Epoch [291/500], Loss: 627.8370
Epoch [301/500], Loss: 610.9933
Epoch [311/500], Loss: 594.9717
Epoch [321/500], Loss: 579.5059
Epoch [331/500], Loss: 564.6456
Epoch [341/500], Loss: 550.4376
Epoch [351/500], Loss: 536.8665
Epoch [361/500], Loss: 523.9122
Epoch [371/500], Loss: 511.5618
Epoch [381/500], Loss: 499.7559
Epoch [391/500], Loss: 488.4594
Epoch [401/500], Loss: 477.6152
Epoch [411/500], Loss: 467.1745
Epoch [421/500], Loss: 457.1699
Epoch [431/500], Loss: 447.5789
Epoch [441/500], Loss: 438.3645
Epoch [451/500], Loss: 429.5402
Epoch [461/500], Loss: 421.0998
Epoch [471/500], Loss: 413.0074
Epoch [481/500], Loss: 405.2380
Epoch [491/500], Loss: 397.7726

Processing CV 3 / 10....
Epoch [1/500], Loss: 38696.9102
Epoch [11/500], Loss: 5817.9272
Epoch [21/500], Loss: 3038.8901
Epoch [31/500], Loss: 2632.4517
Epoch [41/500], Loss: 1667.9329
Epoch [51/500], Loss: 1452.1869
Epoch [61/500], Loss: 1333.7257
Epoch [71/500], Loss: 1240.6261
Epoch [81/500], Loss: 1201.8806
Epoch [91/500], Loss: 1165.6049
Epoch [101/500], Loss: 1133.7260
Epoch [111/500], Loss: 1103.1871
Epoch [121/500], Loss: 1074.5146
Epoch [131/500], Loss: 1046.8578
Epoch [141/500], Loss: 1020.3112
Epoch [151/500], Loss: 994.6771
Epoch [161/500], Loss: 969.6173
Epoch [171/500], Loss: 945.0443
Epoch [181/500], Loss: 920.7129
Epoch [191/500], Loss: 896.3080
Epoch [201/500], Loss: 870.7463
Epoch [211/500], Loss: 844.0503
Epoch [221/500], Loss: 815.4615
Epoch [231/500], Loss: 785.5355
Epoch [241/500], Loss: 755.6133
Epoch [251/500], Loss: 727.4889
Epoch [261/500], Loss: 702.1372
Epoch [271/500], Loss: 680.3683
Epoch [281/500], Loss: 661.0151
Epoch [291/500], Loss: 642.7700
Epoch [301/500], Loss: 625.2849
Epoch [311/500], Loss: 608.4222
Epoch [321/500], Loss: 592.1942
Epoch [331/500], Loss: 576.4454
Epoch [341/500], Loss: 561.2304
Epoch [351/500], Loss: 546.7013
Epoch [361/500], Loss: 532.7725
Epoch [371/500], Loss: 519.5136
Epoch [381/500], Loss: 506.8737
Epoch [391/500], Loss: 494.7879
Epoch [401/500], Loss: 483.2347
Epoch [411/500], Loss: 472.2488
Epoch [421/500], Loss: 461.8059
Epoch [431/500], Loss: 451.8469
Epoch [441/500], Loss: 442.3615
Epoch [451/500], Loss: 433.3104
Epoch [461/500], Loss: 424.6710
Epoch [471/500], Loss: 416.3916
Epoch [481/500], Loss: 408.5075
Epoch [491/500], Loss: 401.0108

Processing CV 4 / 10....
Epoch [1/500], Loss: 38985.8672
Epoch [11/500], Loss: 6155.4248
Epoch [21/500], Loss: 2947.0374
Epoch [31/500], Loss: 2647.3794
Epoch [41/500], Loss: 1761.3386
Epoch [51/500], Loss: 1506.9640
Epoch [61/500], Loss: 1387.0513
Epoch [71/500], Loss: 1287.5781
Epoch [81/500], Loss: 1242.4292
Epoch [91/500], Loss: 1201.6260
Epoch [101/500], Loss: 1166.3810
Epoch [111/500], Loss: 1133.2119
Epoch [121/500], Loss: 1102.1364
Epoch [131/500], Loss: 1072.3652
Epoch [141/500], Loss: 1043.5656
Epoch [151/500], Loss: 1015.8777
Epoch [161/500], Loss: 988.9347
Epoch [171/500], Loss: 962.4865
Epoch [181/500], Loss: 935.9591
Epoch [191/500], Loss: 909.0507
Epoch [201/500], Loss: 880.3608
Epoch [211/500], Loss: 849.7802
Epoch [221/500], Loss: 817.0192
Epoch [231/500], Loss: 783.8018
Epoch [241/500], Loss: 753.2009
Epoch [251/500], Loss: 725.2794
Epoch [261/500], Loss: 701.3282
Epoch [271/500], Loss: 680.5122
Epoch [281/500], Loss: 661.1667
Epoch [291/500], Loss: 642.7045
Epoch [301/500], Loss: 625.0153
Epoch [311/500], Loss: 607.9116
Epoch [321/500], Loss: 591.3868
Epoch [331/500], Loss: 575.3555
Epoch [341/500], Loss: 559.9264
Epoch [351/500], Loss: 545.1878
Epoch [361/500], Loss: 531.0490
Epoch [371/500], Loss: 517.5652
Epoch [381/500], Loss: 504.8022
Epoch [391/500], Loss: 492.6050
Epoch [401/500], Loss: 480.9990
Epoch [411/500], Loss: 469.9339
Epoch [421/500], Loss: 459.3950
Epoch [431/500], Loss: 449.3528
Epoch [441/500], Loss: 439.8090
Epoch [451/500], Loss: 430.7250
Epoch [461/500], Loss: 422.0577
Epoch [471/500], Loss: 413.8160
Epoch [481/500], Loss: 405.9459
Epoch [491/500], Loss: 398.4461

Processing CV 5 / 10....
Epoch [1/500], Loss: 38074.3555
Epoch [11/500], Loss: 6572.6182
Epoch [21/500], Loss: 2860.8389
Epoch [31/500], Loss: 2500.4844
Epoch [41/500], Loss: 1806.7839
Epoch [51/500], Loss: 1510.3988
Epoch [61/500], Loss: 1387.1208
Epoch [71/500], Loss: 1289.9491
Epoch [81/500], Loss: 1239.3116
Epoch [91/500], Loss: 1197.5126
Epoch [101/500], Loss: 1160.3301
Epoch [111/500], Loss: 1126.8367
Epoch [121/500], Loss: 1095.5601
Epoch [131/500], Loss: 1065.9723
Epoch [141/500], Loss: 1037.6021
Epoch [151/500], Loss: 1010.1486
Epoch [161/500], Loss: 983.3771
Epoch [171/500], Loss: 956.9547
Epoch [181/500], Loss: 929.9785
Epoch [191/500], Loss: 901.7024
Epoch [201/500], Loss: 870.5769
Epoch [211/500], Loss: 836.0184
Epoch [221/500], Loss: 800.9793
Epoch [231/500], Loss: 768.6049
Epoch [241/500], Loss: 739.3298
Epoch [251/500], Loss: 714.0709
Epoch [261/500], Loss: 692.1028
Epoch [271/500], Loss: 671.5732
Epoch [281/500], Loss: 651.9600
Epoch [291/500], Loss: 633.1620
Epoch [301/500], Loss: 615.0319
Epoch [311/500], Loss: 597.6047
Epoch [321/500], Loss: 580.7516
Epoch [331/500], Loss: 564.6158
Epoch [341/500], Loss: 549.2541
Epoch [351/500], Loss: 534.6396
Epoch [361/500], Loss: 520.7166
Epoch [371/500], Loss: 507.4995
Epoch [381/500], Loss: 494.9959
Epoch [391/500], Loss: 483.0907
Epoch [401/500], Loss: 471.8037
Epoch [411/500], Loss: 461.0842
Epoch [421/500], Loss: 450.8817
Epoch [431/500], Loss: 441.1871
Epoch [441/500], Loss: 431.9870
Epoch [451/500], Loss: 423.2472
Epoch [461/500], Loss: 414.9311
Epoch [471/500], Loss: 407.0596
Epoch [481/500], Loss: 399.5947
Epoch [491/500], Loss: 392.4952

Processing CV 6 / 10....
Epoch [1/500], Loss: 37489.1094
Epoch [11/500], Loss: 6671.8789
Epoch [21/500], Loss: 2974.6858
Epoch [31/500], Loss: 2430.7849
Epoch [41/500], Loss: 1859.2510
Epoch [51/500], Loss: 1556.6282
Epoch [61/500], Loss: 1415.4198
Epoch [71/500], Loss: 1323.5956
Epoch [81/500], Loss: 1266.3083
Epoch [91/500], Loss: 1224.1564
Epoch [101/500], Loss: 1185.3636
Epoch [111/500], Loss: 1151.1400
Epoch [121/500], Loss: 1119.0657
Epoch [131/500], Loss: 1088.8672
Epoch [141/500], Loss: 1059.8707
Epoch [151/500], Loss: 1031.7109
Epoch [161/500], Loss: 1004.0807
Epoch [171/500], Loss: 976.8347
Epoch [181/500], Loss: 948.8135
Epoch [191/500], Loss: 919.0335
Epoch [201/500], Loss: 886.9774
Epoch [211/500], Loss: 851.8239
Epoch [221/500], Loss: 816.2679
Epoch [231/500], Loss: 782.5670
Epoch [241/500], Loss: 753.1636
Epoch [251/500], Loss: 728.5566
Epoch [261/500], Loss: 706.5156
Epoch [271/500], Loss: 685.4687
Epoch [281/500], Loss: 665.2906
Epoch [291/500], Loss: 645.9975
Epoch [301/500], Loss: 627.3522
Epoch [311/500], Loss: 609.4674
Epoch [321/500], Loss: 592.3305
Epoch [331/500], Loss: 575.6756
Epoch [341/500], Loss: 559.4893
Epoch [351/500], Loss: 543.8900
Epoch [361/500], Loss: 528.9459
Epoch [371/500], Loss: 514.7289
Epoch [381/500], Loss: 501.1821
Epoch [391/500], Loss: 488.3165
Epoch [401/500], Loss: 476.1551
Epoch [411/500], Loss: 464.6658
Epoch [421/500], Loss: 453.8391
Epoch [431/500], Loss: 443.6395
Epoch [441/500], Loss: 434.0460
Epoch [451/500], Loss: 424.9827
Epoch [461/500], Loss: 416.4477
Epoch [471/500], Loss: 408.4190
Epoch [481/500], Loss: 400.8292
Epoch [491/500], Loss: 393.6383

Processing CV 7 / 10....
Epoch [1/500], Loss: 37505.6172
Epoch [11/500], Loss: 6582.9351
Epoch [21/500], Loss: 2896.4656
Epoch [31/500], Loss: 2417.2693
Epoch [41/500], Loss: 1822.5145
Epoch [51/500], Loss: 1524.3469
Epoch [61/500], Loss: 1391.6036
Epoch [71/500], Loss: 1299.1149
Epoch [81/500], Loss: 1244.6423
Epoch [91/500], Loss: 1203.5261
Epoch [101/500], Loss: 1165.8721
Epoch [111/500], Loss: 1132.6543
Epoch [121/500], Loss: 1101.6178
Epoch [131/500], Loss: 1072.5382
Epoch [141/500], Loss: 1044.9469
Epoch [151/500], Loss: 1018.4749
Epoch [161/500], Loss: 992.7246
Epoch [171/500], Loss: 967.2798
Epoch [181/500], Loss: 941.9259
Epoch [191/500], Loss: 916.1637
Epoch [201/500], Loss: 889.1490
Epoch [211/500], Loss: 859.7160
Epoch [221/500], Loss: 827.4542
Epoch [231/500], Loss: 793.1357
Epoch [241/500], Loss: 759.3975
Epoch [251/500], Loss: 730.3816
Epoch [261/500], Loss: 706.6884
Epoch [271/500], Loss: 685.5710
Epoch [281/500], Loss: 665.4567
Epoch [291/500], Loss: 646.2950
Epoch [301/500], Loss: 627.9290
Epoch [311/500], Loss: 610.2443
Epoch [321/500], Loss: 593.1991
Epoch [331/500], Loss: 576.5756
Epoch [341/500], Loss: 560.6539
Epoch [351/500], Loss: 545.4077
Epoch [361/500], Loss: 530.6627
Epoch [371/500], Loss: 516.4692
Epoch [381/500], Loss: 502.8907
Epoch [391/500], Loss: 490.0302
Epoch [401/500], Loss: 477.7399
Epoch [411/500], Loss: 466.1292
Epoch [421/500], Loss: 455.1612
Epoch [431/500], Loss: 444.7921
Epoch [441/500], Loss: 435.0188
Epoch [451/500], Loss: 425.7735
Epoch [461/500], Loss: 417.0770
Epoch [471/500], Loss: 408.9157
Epoch [481/500], Loss: 401.2223
Epoch [491/500], Loss: 393.9501

Processing CV 8 / 10....
Epoch [1/500], Loss: 38575.1992
Epoch [11/500], Loss: 6579.5171
Epoch [21/500], Loss: 2919.7817
Epoch [31/500], Loss: 2599.9685
Epoch [41/500], Loss: 1842.8250
Epoch [51/500], Loss: 1551.8350
Epoch [61/500], Loss: 1428.6880
Epoch [71/500], Loss: 1326.9167
Epoch [81/500], Loss: 1276.0803
Epoch [91/500], Loss: 1231.9875
Epoch [101/500], Loss: 1193.5732
Epoch [111/500], Loss: 1158.3457
Epoch [121/500], Loss: 1125.2590
Epoch [131/500], Loss: 1093.6960
Epoch [141/500], Loss: 1063.2000
Epoch [151/500], Loss: 1033.2798
Epoch [161/500], Loss: 1003.3312
Epoch [171/500], Loss: 972.8670
Epoch [181/500], Loss: 939.6900
Epoch [191/500], Loss: 904.1028
Epoch [201/500], Loss: 868.9018
Epoch [211/500], Loss: 835.9872
Epoch [221/500], Loss: 804.4067
Epoch [231/500], Loss: 774.8323
Epoch [241/500], Loss: 749.1338
Epoch [251/500], Loss: 726.0572
Epoch [261/500], Loss: 704.1793
Epoch [271/500], Loss: 683.3738
Epoch [281/500], Loss: 663.4700
Epoch [291/500], Loss: 644.2727
Epoch [301/500], Loss: 625.8118
Epoch [311/500], Loss: 608.0326
Epoch [321/500], Loss: 590.9321
Epoch [331/500], Loss: 574.5405
Epoch [341/500], Loss: 558.7628
Epoch [351/500], Loss: 543.7249
Epoch [361/500], Loss: 529.4614
Epoch [371/500], Loss: 515.8359
Epoch [381/500], Loss: 502.9521
Epoch [391/500], Loss: 490.7518
Epoch [401/500], Loss: 479.1829
Epoch [411/500], Loss: 468.1796
Epoch [421/500], Loss: 457.7672
Epoch [431/500], Loss: 447.8669
Epoch [441/500], Loss: 438.4926
Epoch [451/500], Loss: 429.6017
Epoch [461/500], Loss: 421.2261
Epoch [471/500], Loss: 413.3116
Epoch [481/500], Loss: 405.8154
Epoch [491/500], Loss: 398.7108

Processing CV 9 / 10....
Epoch [1/500], Loss: 39275.0391
Epoch [11/500], Loss: 6325.1704
Epoch [21/500], Loss: 2994.4551
Epoch [31/500], Loss: 2666.1672
Epoch [41/500], Loss: 1786.3763
Epoch [51/500], Loss: 1516.2250
Epoch [61/500], Loss: 1396.7324
Epoch [71/500], Loss: 1297.3302
Epoch [81/500], Loss: 1252.2112
Epoch [91/500], Loss: 1212.1069
Epoch [101/500], Loss: 1177.5204
Epoch [111/500], Loss: 1145.2283
Epoch [121/500], Loss: 1114.7805
Epoch [131/500], Loss: 1085.4528
Epoch [141/500], Loss: 1057.3042
Epoch [151/500], Loss: 1029.8511
Epoch [161/500], Loss: 1002.9091
Epoch [171/500], Loss: 975.6638
Epoch [181/500], Loss: 947.8151
Epoch [191/500], Loss: 917.9591
Epoch [201/500], Loss: 886.0645
Epoch [211/500], Loss: 852.4119
Epoch [221/500], Loss: 819.2057
Epoch [231/500], Loss: 788.1678
Epoch [241/500], Loss: 759.1964
Epoch [251/500], Loss: 733.6674
Epoch [261/500], Loss: 711.3507
Epoch [271/500], Loss: 690.4716
Epoch [281/500], Loss: 670.6394
Epoch [291/500], Loss: 651.6330
Epoch [301/500], Loss: 633.2784
Epoch [311/500], Loss: 615.5151
Epoch [321/500], Loss: 598.3188
Epoch [331/500], Loss: 581.6940
Epoch [341/500], Loss: 565.7090
Epoch [351/500], Loss: 550.4410
Epoch [361/500], Loss: 535.9144
Epoch [371/500], Loss: 522.1234
Epoch [381/500], Loss: 509.0254
Epoch [391/500], Loss: 496.5933
Epoch [401/500], Loss: 484.7830
Epoch [411/500], Loss: 473.5319
Epoch [421/500], Loss: 462.7862
Epoch [431/500], Loss: 452.6069
Epoch [441/500], Loss: 442.9390
Epoch [451/500], Loss: 433.7754
Epoch [461/500], Loss: 425.0869
Epoch [471/500], Loss: 416.8286
Epoch [481/500], Loss: 408.9728
Epoch [491/500], Loss: 401.5076

Processing CV 10 / 10....
Epoch [1/500], Loss: 39068.9805
Epoch [11/500], Loss: 6013.8276
Epoch [21/500], Loss: 3111.5823
Epoch [31/500], Loss: 2698.0510
Epoch [41/500], Loss: 1772.6448
Epoch [51/500], Loss: 1536.7134
Epoch [61/500], Loss: 1412.7358
Epoch [71/500], Loss: 1312.7719
Epoch [81/500], Loss: 1267.8472
Epoch [91/500], Loss: 1226.7717
Epoch [101/500], Loss: 1190.6075
Epoch [111/500], Loss: 1156.3928
Epoch [121/500], Loss: 1124.2906
Epoch [131/500], Loss: 1093.5417
Epoch [141/500], Loss: 1064.1179
Epoch [151/500], Loss: 1035.6958
Epoch [161/500], Loss: 1007.9599
Epoch [171/500], Loss: 980.6732
Epoch [181/500], Loss: 953.6372
Epoch [191/500], Loss: 926.1901
Epoch [201/500], Loss: 897.7388
Epoch [211/500], Loss: 867.3810
Epoch [221/500], Loss: 833.7031
Epoch [231/500], Loss: 798.1850
Epoch [241/500], Loss: 766.0099
Epoch [251/500], Loss: 736.9105
Epoch [261/500], Loss: 711.9880
Epoch [271/500], Loss: 690.3726
Epoch [281/500], Loss: 670.0605
Epoch [291/500], Loss: 650.6044
Epoch [301/500], Loss: 631.8224
Epoch [311/500], Loss: 613.7679
Epoch [321/500], Loss: 596.2997
Epoch [331/500], Loss: 579.4905
Epoch [341/500], Loss: 563.3998
Epoch [351/500], Loss: 547.9838
Epoch [361/500], Loss: 533.3885
Epoch [371/500], Loss: 519.5095
Epoch [381/500], Loss: 506.2917
Epoch [391/500], Loss: 493.7323
Epoch [401/500], Loss: 481.7881
Epoch [411/500], Loss: 470.3941
Epoch [421/500], Loss: 459.5680
Epoch [431/500], Loss: 449.2575
Epoch [441/500], Loss: 439.3979
Epoch [451/500], Loss: 429.9993
Epoch [461/500], Loss: 421.0927
Epoch [471/500], Loss: 412.6235
Epoch [481/500], Loss: 404.5525
Epoch [491/500], Loss: 396.8759

[run 30/36] ds18 m1 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....

Processing CV 2 / 10....

Processing CV 3 / 10....

Processing CV 4 / 10....

Processing CV 5 / 10....

Processing CV 6 / 10....

Processing CV 7 / 10....

Processing CV 8 / 10....

Processing CV 9 / 10....

Processing CV 10 / 10....

[run 31/36] ds18 m3 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Processing i =  1  out of  1344
Processing i =  2  out of  1344
Processing i =  3  out of  1344
Processing i =  4  out of  1344
Processing i =  5  out of  1344
Processing i =  6  out of  1344
Processing i =  7  out of  1344
Processing i =  8  out of  1344
Processing i =  9  out of  1344
Processing i =  10  out of  1344
Processing i =  11  out of  1344
Processing i =  12  out of  1344
Processing i =  13  out of  1344
Processing i =  14  out of  1344
Processing i =  15  out of  1344
Processing i =  16  out of  1344
Processing i =  17  out of  1344
Processing i =  18  out of  1344
Processing i =  19  out of  1344
Processing i =  20  out of  1344
Processing i =  21  out of  1344
Processing i =  22  out of  1344
Processing i =  23  out of  1344
Processing i =  24  out of  1344
Processing i =  25  out of  1344
Processing i =  26  out of  1344
Processing i =  27  out of  1344
Processing i =  28  out of  1344
Processing i =  29  out of  1344
Processing i =  30  out of  1344
Processing i =  31  out of  1344
Processing i =  32  out of  1344
Processing i =  33  out of  1344
Processing i =  34  out of  1344
Processing i =  35  out of  1344
Processing i =  36  out of  1344
Processing i =  37  out of  1344
Processing i =  38  out of  1344
Processing i =  39  out of  1344
Processing i =  40  out of  1344
Processing i =  41  out of  1344
Processing i =  42  out of  1344
Processing i =  43  out of  1344
Processing i =  44  out of  1344
Processing i =  45  out of  1344
Processing i =  46  out of  1344
Processing i =  47  out of  1344
Processing i =  48  out of  1344
Processing i =  49  out of  1344
Processing i =  50  out of  1344
Processing i =  51  out of  1344
Processing i =  52  out of  1344
Processing i =  53  out of  1344
Processing i =  54  out of  1344
Processing i =  55  out of  1344
Processing i =  56  out of  1344
Processing i =  57  out of  1344
Processing i =  58  out of  1344
Processing i =  59  out of  1344
Processing i =  60  out of  1344
Processing i =  61  out of  1344
Processing i =  62  out of  1344
Processing i =  63  out of  1344
Processing i =  64  out of  1344
Processing i =  65  out of  1344
Processing i =  66  out of  1344
Processing i =  67  out of  1344
Processing i =  68  out of  1344
Processing i =  69  out of  1344
Processing i =  70  out of  1344
Processing i =  71  out of  1344
Processing i =  72  out of  1344
Processing i =  73  out of  1344
Processing i =  74  out of  1344
Processing i =  75  out of  1344
Processing i =  76  out of  1344
Processing i =  77  out of  1344
Processing i =  78  out of  1344
Processing i =  79  out of  1344
Processing i =  80  out of  1344
Processing i =  81  out of  1344
Processing i =  82  out of  1344
Processing i =  83  out of  1344
Processing i =  84  out of  1344
Processing i =  85  out of  1344
Processing i =  86  out of  1344
Processing i =  87  out of  1344
Processing i =  88  out of  1344
Processing i =  89  out of  1344

02:59:00 - cmdstanpy - INFO - Chain [1] start processing
02:59:01 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

02:59:02 - cmdstanpy - INFO - Chain [1] start processing
02:59:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

02:59:04 - cmdstanpy - INFO - Chain [1] start processing
02:59:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

02:59:05 - cmdstanpy - INFO - Chain [1] start processing
02:59:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

02:59:06 - cmdstanpy - INFO - Chain [1] start processing
02:59:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

02:59:07 - cmdstanpy - INFO - Chain [1] start processing
02:59:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

02:59:07 - cmdstanpy - INFO - Chain [1] start processing
02:59:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

02:59:08 - cmdstanpy - INFO - Chain [1] start processing
02:59:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

02:59:09 - cmdstanpy - INFO - Chain [1] start processing
02:59:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

02:59:10 - cmdstanpy - INFO - Chain [1] start processing
02:59:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

02:59:10 - cmdstanpy - INFO - Chain [1] start processing
02:59:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

02:59:11 - cmdstanpy - INFO - Chain [1] start processing
02:59:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

02:59:12 - cmdstanpy - INFO - Chain [1] start processing
02:59:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

02:59:13 - cmdstanpy - INFO - Chain [1] start processing
02:59:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

02:59:14 - cmdstanpy - INFO - Chain [1] start processing
02:59:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

02:59:15 - cmdstanpy - INFO - Chain [1] start processing
02:59:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

02:59:16 - cmdstanpy - INFO - Chain [1] start processing
02:59:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

02:59:16 - cmdstanpy - INFO - Chain [1] start processing
02:59:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

02:59:17 - cmdstanpy - INFO - Chain [1] start processing
02:59:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

02:59:19 - cmdstanpy - INFO - Chain [1] start processing
02:59:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

02:59:20 - cmdstanpy - INFO - Chain [1] start processing
02:59:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

02:59:20 - cmdstanpy - INFO - Chain [1] start processing
02:59:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

02:59:21 - cmdstanpy - INFO - Chain [1] start processing
02:59:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

02:59:22 - cmdstanpy - INFO - Chain [1] start processing
02:59:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

02:59:23 - cmdstanpy - INFO - Chain [1] start processing
02:59:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

02:59:24 - cmdstanpy - INFO - Chain [1] start processing
02:59:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

02:59:24 - cmdstanpy - INFO - Chain [1] start processing
02:59:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

02:59:25 - cmdstanpy - INFO - Chain [1] start processing
02:59:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

02:59:26 - cmdstanpy - INFO - Chain [1] start processing
02:59:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

02:59:27 - cmdstanpy - INFO - Chain [1] start processing
02:59:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

02:59:28 - cmdstanpy - INFO - Chain [1] start processing
02:59:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

02:59:29 - cmdstanpy - INFO - Chain [1] start processing
02:59:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

02:59:30 - cmdstanpy - INFO - Chain [1] start processing
02:59:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

02:59:31 - cmdstanpy - INFO - Chain [1] start processing
02:59:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

02:59:31 - cmdstanpy - INFO - Chain [1] start processing
02:59:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

02:59:32 - cmdstanpy - INFO - Chain [1] start processing
02:59:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

02:59:34 - cmdstanpy - INFO - Chain [1] start processing
02:59:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

02:59:35 - cmdstanpy - INFO - Chain [1] start processing
02:59:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

02:59:36 - cmdstanpy - INFO - Chain [1] start processing
02:59:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

02:59:36 - cmdstanpy - INFO - Chain [1] start processing
02:59:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

02:59:37 - cmdstanpy - INFO - Chain [1] start processing
02:59:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

02:59:39 - cmdstanpy - INFO - Chain [1] start processing
02:59:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

02:59:40 - cmdstanpy - INFO - Chain [1] start processing
02:59:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

02:59:41 - cmdstanpy - INFO - Chain [1] start processing
02:59:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

02:59:42 - cmdstanpy - INFO - Chain [1] start processing
02:59:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

02:59:43 - cmdstanpy - INFO - Chain [1] start processing
02:59:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

02:59:45 - cmdstanpy - INFO - Chain [1] start processing
02:59:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

02:59:45 - cmdstanpy - INFO - Chain [1] start processing
02:59:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

02:59:46 - cmdstanpy - INFO - Chain [1] start processing
02:59:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

02:59:47 - cmdstanpy - INFO - Chain [1] start processing
02:59:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

02:59:49 - cmdstanpy - INFO - Chain [1] start processing
02:59:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

02:59:50 - cmdstanpy - INFO - Chain [1] start processing
02:59:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

02:59:50 - cmdstanpy - INFO - Chain [1] start processing
02:59:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

02:59:51 - cmdstanpy - INFO - Chain [1] start processing
02:59:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

02:59:53 - cmdstanpy - INFO - Chain [1] start processing
02:59:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

02:59:54 - cmdstanpy - INFO - Chain [1] start processing
02:59:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

02:59:55 - cmdstanpy - INFO - Chain [1] start processing
02:59:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

02:59:56 - cmdstanpy - INFO - Chain [1] start processing
02:59:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

02:59:56 - cmdstanpy - INFO - Chain [1] start processing
02:59:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

02:59:57 - cmdstanpy - INFO - Chain [1] start processing
02:59:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

02:59:58 - cmdstanpy - INFO - Chain [1] start processing
02:59:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

02:59:59 - cmdstanpy - INFO - Chain [1] start processing
02:59:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:00:00 - cmdstanpy - INFO - Chain [1] start processing
03:00:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:00:01 - cmdstanpy - INFO - Chain [1] start processing
03:00:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:00:02 - cmdstanpy - INFO - Chain [1] start processing
03:00:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:00:03 - cmdstanpy - INFO - Chain [1] start processing
03:00:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

03:00:04 - cmdstanpy - INFO - Chain [1] start processing
03:00:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:00:05 - cmdstanpy - INFO - Chain [1] start processing
03:00:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:00:05 - cmdstanpy - INFO - Chain [1] start processing
03:00:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:00:06 - cmdstanpy - INFO - Chain [1] start processing
03:00:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:00:07 - cmdstanpy - INFO - Chain [1] start processing
03:00:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:00:08 - cmdstanpy - INFO - Chain [1] start processing
03:00:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

03:00:09 - cmdstanpy - INFO - Chain [1] start processing
03:00:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:00:10 - cmdstanpy - INFO - Chain [1] start processing
03:00:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

03:00:12 - cmdstanpy - INFO - Chain [1] start processing
03:00:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:00:12 - cmdstanpy - INFO - Chain [1] start processing
03:00:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:00:13 - cmdstanpy - INFO - Chain [1] start processing
03:00:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

03:00:14 - cmdstanpy - INFO - Chain [1] start processing
03:00:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:00:15 - cmdstanpy - INFO - Chain [1] start processing
03:00:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:00:16 - cmdstanpy - INFO - Chain [1] start processing
03:00:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:00:17 - cmdstanpy - INFO - Chain [1] start processing
03:00:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:00:17 - cmdstanpy - INFO - Chain [1] start processing
03:00:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:00:18 - cmdstanpy - INFO - Chain [1] start processing
03:00:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:00:19 - cmdstanpy - INFO - Chain [1] start processing
03:00:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:00:20 - cmdstanpy - INFO - Chain [1] start processing
03:00:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:00:21 - cmdstanpy - INFO - Chain [1] start processing
03:00:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:00:22 - cmdstanpy - INFO - Chain [1] start processing
03:00:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:00:23 - cmdstanpy - INFO - Chain [1] start processing
03:00:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

03:00:25 - cmdstanpy - INFO - Chain [1] start processing
03:00:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:00:26 - cmdstanpy - INFO - Chain [1] start processing
03:00:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:00:26 - cmdstanpy - INFO - Chain [1] start processing
03:00:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

03:00:27 - cmdstanpy - INFO - Chain [1] start processing
03:00:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:00:28 - cmdstanpy - INFO - Chain [1] start processing
03:00:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:00:29 - cmdstanpy - INFO - Chain [1] start processing
03:00:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:00:30 - cmdstanpy - INFO - Chain [1] start processing
03:00:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:00:31 - cmdstanpy - INFO - Chain [1] start processing
03:00:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:00:32 - cmdstanpy - INFO - Chain [1] start processing
03:00:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:00:33 - cmdstanpy - INFO - Chain [1] start processing
03:00:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:00:35 - cmdstanpy - INFO - Chain [1] start processing
03:00:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:00:36 - cmdstanpy - INFO - Chain [1] start processing
03:00:36 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 2 / 10....

03:00:37 - cmdstanpy - INFO - Chain [1] start processing
03:00:38 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:00:40 - cmdstanpy - INFO - Chain [1] start processing
03:00:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

03:00:42 - cmdstanpy - INFO - Chain [1] start processing
03:00:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

03:00:43 - cmdstanpy - INFO - Chain [1] start processing
03:00:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

03:00:44 - cmdstanpy - INFO - Chain [1] start processing
03:00:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

03:00:44 - cmdstanpy - INFO - Chain [1] start processing
03:00:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

03:00:45 - cmdstanpy - INFO - Chain [1] start processing
03:00:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

03:00:46 - cmdstanpy - INFO - Chain [1] start processing
03:00:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

03:00:46 - cmdstanpy - INFO - Chain [1] start processing
03:00:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

03:00:48 - cmdstanpy - INFO - Chain [1] start processing
03:00:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

03:00:48 - cmdstanpy - INFO - Chain [1] start processing
03:00:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

03:00:49 - cmdstanpy - INFO - Chain [1] start processing
03:00:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

03:00:50 - cmdstanpy - INFO - Chain [1] start processing
03:00:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

03:00:51 - cmdstanpy - INFO - Chain [1] start processing
03:00:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

03:00:51 - cmdstanpy - INFO - Chain [1] start processing
03:00:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

03:00:53 - cmdstanpy - INFO - Chain [1] start processing
03:00:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

03:00:53 - cmdstanpy - INFO - Chain [1] start processing
03:00:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

03:00:54 - cmdstanpy - INFO - Chain [1] start processing
03:00:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

03:00:55 - cmdstanpy - INFO - Chain [1] start processing
03:00:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

03:00:56 - cmdstanpy - INFO - Chain [1] start processing
03:00:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

03:00:57 - cmdstanpy - INFO - Chain [1] start processing
03:00:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

03:00:57 - cmdstanpy - INFO - Chain [1] start processing
03:00:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

03:00:58 - cmdstanpy - INFO - Chain [1] start processing
03:00:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

03:00:59 - cmdstanpy - INFO - Chain [1] start processing
03:01:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

03:01:00 - cmdstanpy - INFO - Chain [1] start processing
03:01:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

03:01:01 - cmdstanpy - INFO - Chain [1] start processing
03:01:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

03:01:02 - cmdstanpy - INFO - Chain [1] start processing
03:01:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

03:01:03 - cmdstanpy - INFO - Chain [1] start processing
03:01:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

03:01:04 - cmdstanpy - INFO - Chain [1] start processing
03:01:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

03:01:05 - cmdstanpy - INFO - Chain [1] start processing
03:01:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

03:01:06 - cmdstanpy - INFO - Chain [1] start processing
03:01:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

03:01:07 - cmdstanpy - INFO - Chain [1] start processing
03:01:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

03:01:08 - cmdstanpy - INFO - Chain [1] start processing
03:01:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

03:01:09 - cmdstanpy - INFO - Chain [1] start processing
03:01:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

03:01:10 - cmdstanpy - INFO - Chain [1] start processing
03:01:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

03:01:10 - cmdstanpy - INFO - Chain [1] start processing
03:01:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

03:01:11 - cmdstanpy - INFO - Chain [1] start processing
03:01:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

03:01:13 - cmdstanpy - INFO - Chain [1] start processing
03:01:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

03:01:13 - cmdstanpy - INFO - Chain [1] start processing
03:01:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

03:01:14 - cmdstanpy - INFO - Chain [1] start processing
03:01:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

03:01:15 - cmdstanpy - INFO - Chain [1] start processing
03:01:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

03:01:16 - cmdstanpy - INFO - Chain [1] start processing
03:01:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

03:01:17 - cmdstanpy - INFO - Chain [1] start processing
03:01:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

03:01:18 - cmdstanpy - INFO - Chain [1] start processing
03:01:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

03:01:19 - cmdstanpy - INFO - Chain [1] start processing
03:01:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

03:01:20 - cmdstanpy - INFO - Chain [1] start processing
03:01:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

03:01:20 - cmdstanpy - INFO - Chain [1] start processing
03:01:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

03:01:21 - cmdstanpy - INFO - Chain [1] start processing
03:01:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

03:01:22 - cmdstanpy - INFO - Chain [1] start processing
03:01:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

03:01:23 - cmdstanpy - INFO - Chain [1] start processing
03:01:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

03:01:24 - cmdstanpy - INFO - Chain [1] start processing
03:01:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

03:01:25 - cmdstanpy - INFO - Chain [1] start processing
03:01:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

03:01:26 - cmdstanpy - INFO - Chain [1] start processing
03:01:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

03:01:27 - cmdstanpy - INFO - Chain [1] start processing
03:01:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

03:01:28 - cmdstanpy - INFO - Chain [1] start processing
03:01:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

03:01:29 - cmdstanpy - INFO - Chain [1] start processing
03:01:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

03:01:30 - cmdstanpy - INFO - Chain [1] start processing
03:01:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

03:01:30 - cmdstanpy - INFO - Chain [1] start processing
03:01:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

03:01:31 - cmdstanpy - INFO - Chain [1] start processing
03:01:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

03:01:33 - cmdstanpy - INFO - Chain [1] start processing
03:01:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

03:01:34 - cmdstanpy - INFO - Chain [1] start processing
03:01:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:01:34 - cmdstanpy - INFO - Chain [1] start processing
03:01:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:01:36 - cmdstanpy - INFO - Chain [1] start processing
03:01:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:01:37 - cmdstanpy - INFO - Chain [1] start processing
03:01:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:01:38 - cmdstanpy - INFO - Chain [1] start processing
03:01:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:01:38 - cmdstanpy - INFO - Chain [1] start processing
03:01:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

03:01:39 - cmdstanpy - INFO - Chain [1] start processing
03:01:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:01:40 - cmdstanpy - INFO - Chain [1] start processing
03:01:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:01:41 - cmdstanpy - INFO - Chain [1] start processing
03:01:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:01:42 - cmdstanpy - INFO - Chain [1] start processing
03:01:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:01:43 - cmdstanpy - INFO - Chain [1] start processing
03:01:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:01:44 - cmdstanpy - INFO - Chain [1] start processing
03:01:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

03:01:44 - cmdstanpy - INFO - Chain [1] start processing
03:01:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:01:45 - cmdstanpy - INFO - Chain [1] start processing
03:01:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

03:01:46 - cmdstanpy - INFO - Chain [1] start processing
03:01:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:01:47 - cmdstanpy - INFO - Chain [1] start processing
03:01:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:01:48 - cmdstanpy - INFO - Chain [1] start processing
03:01:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

03:01:48 - cmdstanpy - INFO - Chain [1] start processing
03:01:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:01:49 - cmdstanpy - INFO - Chain [1] start processing
03:01:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:01:50 - cmdstanpy - INFO - Chain [1] start processing
03:01:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:01:51 - cmdstanpy - INFO - Chain [1] start processing
03:01:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:01:52 - cmdstanpy - INFO - Chain [1] start processing
03:01:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:01:52 - cmdstanpy - INFO - Chain [1] start processing
03:01:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:01:53 - cmdstanpy - INFO - Chain [1] start processing
03:01:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:01:54 - cmdstanpy - INFO - Chain [1] start processing
03:01:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:01:55 - cmdstanpy - INFO - Chain [1] start processing
03:01:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:01:56 - cmdstanpy - INFO - Chain [1] start processing
03:01:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:01:57 - cmdstanpy - INFO - Chain [1] start processing
03:01:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

03:01:58 - cmdstanpy - INFO - Chain [1] start processing
03:02:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:02:00 - cmdstanpy - INFO - Chain [1] start processing
03:02:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:02:01 - cmdstanpy - INFO - Chain [1] start processing
03:02:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

03:02:02 - cmdstanpy - INFO - Chain [1] start processing
03:02:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:02:03 - cmdstanpy - INFO - Chain [1] start processing
03:02:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:02:03 - cmdstanpy - INFO - Chain [1] start processing
03:02:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:02:04 - cmdstanpy - INFO - Chain [1] start processing
03:02:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:02:05 - cmdstanpy - INFO - Chain [1] start processing
03:02:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:02:06 - cmdstanpy - INFO - Chain [1] start processing
03:02:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:02:07 - cmdstanpy - INFO - Chain [1] start processing
03:02:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:02:07 - cmdstanpy - INFO - Chain [1] start processing
03:02:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:02:08 - cmdstanpy - INFO - Chain [1] start processing
03:02:09 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 3 / 10....

03:02:10 - cmdstanpy - INFO - Chain [1] start processing
03:02:10 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:02:12 - cmdstanpy - INFO - Chain [1] start processing
03:02:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

03:02:13 - cmdstanpy - INFO - Chain [1] start processing
03:02:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

03:02:14 - cmdstanpy - INFO - Chain [1] start processing
03:02:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

03:02:15 - cmdstanpy - INFO - Chain [1] start processing
03:02:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

03:02:16 - cmdstanpy - INFO - Chain [1] start processing
03:02:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

03:02:16 - cmdstanpy - INFO - Chain [1] start processing
03:02:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

03:02:17 - cmdstanpy - INFO - Chain [1] start processing
03:02:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

03:02:18 - cmdstanpy - INFO - Chain [1] start processing
03:02:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

03:02:18 - cmdstanpy - INFO - Chain [1] start processing
03:02:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

03:02:19 - cmdstanpy - INFO - Chain [1] start processing
03:02:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

03:02:20 - cmdstanpy - INFO - Chain [1] start processing
03:02:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

03:02:21 - cmdstanpy - INFO - Chain [1] start processing
03:02:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

03:02:22 - cmdstanpy - INFO - Chain [1] start processing
03:02:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

03:02:22 - cmdstanpy - INFO - Chain [1] start processing
03:02:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

03:02:23 - cmdstanpy - INFO - Chain [1] start processing
03:02:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

03:02:24 - cmdstanpy - INFO - Chain [1] start processing
03:02:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

03:02:25 - cmdstanpy - INFO - Chain [1] start processing
03:02:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

03:02:26 - cmdstanpy - INFO - Chain [1] start processing
03:02:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

03:02:27 - cmdstanpy - INFO - Chain [1] start processing
03:02:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

03:02:27 - cmdstanpy - INFO - Chain [1] start processing
03:02:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

03:02:28 - cmdstanpy - INFO - Chain [1] start processing
03:02:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

03:02:29 - cmdstanpy - INFO - Chain [1] start processing
03:02:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

03:02:29 - cmdstanpy - INFO - Chain [1] start processing
03:02:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

03:02:30 - cmdstanpy - INFO - Chain [1] start processing
03:02:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

03:02:31 - cmdstanpy - INFO - Chain [1] start processing
03:02:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

03:02:32 - cmdstanpy - INFO - Chain [1] start processing
03:02:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

03:02:33 - cmdstanpy - INFO - Chain [1] start processing
03:02:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

03:02:33 - cmdstanpy - INFO - Chain [1] start processing
03:02:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

03:02:34 - cmdstanpy - INFO - Chain [1] start processing
03:02:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

03:02:35 - cmdstanpy - INFO - Chain [1] start processing
03:02:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

03:02:35 - cmdstanpy - INFO - Chain [1] start processing
03:02:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

03:02:36 - cmdstanpy - INFO - Chain [1] start processing
03:02:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

03:02:37 - cmdstanpy - INFO - Chain [1] start processing
03:02:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

03:02:38 - cmdstanpy - INFO - Chain [1] start processing
03:02:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

03:02:38 - cmdstanpy - INFO - Chain [1] start processing
03:02:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

03:02:39 - cmdstanpy - INFO - Chain [1] start processing
03:02:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

03:02:40 - cmdstanpy - INFO - Chain [1] start processing
03:02:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

03:02:41 - cmdstanpy - INFO - Chain [1] start processing
03:02:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

03:02:42 - cmdstanpy - INFO - Chain [1] start processing
03:02:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

03:02:43 - cmdstanpy - INFO - Chain [1] start processing
03:02:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

03:02:44 - cmdstanpy - INFO - Chain [1] start processing
03:02:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

03:02:45 - cmdstanpy - INFO - Chain [1] start processing
03:02:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

03:02:46 - cmdstanpy - INFO - Chain [1] start processing
03:02:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

03:02:46 - cmdstanpy - INFO - Chain [1] start processing
03:02:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

03:02:47 - cmdstanpy - INFO - Chain [1] start processing
03:02:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

03:02:48 - cmdstanpy - INFO - Chain [1] start processing
03:02:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

03:02:49 - cmdstanpy - INFO - Chain [1] start processing
03:02:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

03:02:49 - cmdstanpy - INFO - Chain [1] start processing
03:02:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

03:02:50 - cmdstanpy - INFO - Chain [1] start processing
03:02:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

03:02:51 - cmdstanpy - INFO - Chain [1] start processing
03:02:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

03:02:52 - cmdstanpy - INFO - Chain [1] start processing
03:02:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

03:02:53 - cmdstanpy - INFO - Chain [1] start processing
03:02:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

03:02:54 - cmdstanpy - INFO - Chain [1] start processing
03:02:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

03:02:55 - cmdstanpy - INFO - Chain [1] start processing
03:02:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

03:02:56 - cmdstanpy - INFO - Chain [1] start processing
03:02:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

03:02:57 - cmdstanpy - INFO - Chain [1] start processing
03:02:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

03:02:57 - cmdstanpy - INFO - Chain [1] start processing
03:02:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

03:02:58 - cmdstanpy - INFO - Chain [1] start processing
03:02:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

03:02:59 - cmdstanpy - INFO - Chain [1] start processing
03:02:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

03:03:00 - cmdstanpy - INFO - Chain [1] start processing
03:03:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:03:00 - cmdstanpy - INFO - Chain [1] start processing
03:03:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:03:01 - cmdstanpy - INFO - Chain [1] start processing
03:03:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:03:02 - cmdstanpy - INFO - Chain [1] start processing
03:03:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:03:02 - cmdstanpy - INFO - Chain [1] start processing
03:03:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:03:03 - cmdstanpy - INFO - Chain [1] start processing
03:03:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

03:03:04 - cmdstanpy - INFO - Chain [1] start processing
03:03:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:03:05 - cmdstanpy - INFO - Chain [1] start processing
03:03:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:03:06 - cmdstanpy - INFO - Chain [1] start processing
03:03:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:03:07 - cmdstanpy - INFO - Chain [1] start processing
03:03:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:03:08 - cmdstanpy - INFO - Chain [1] start processing
03:03:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:03:08 - cmdstanpy - INFO - Chain [1] start processing
03:03:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

03:03:09 - cmdstanpy - INFO - Chain [1] start processing
03:03:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:03:10 - cmdstanpy - INFO - Chain [1] start processing
03:03:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

03:03:11 - cmdstanpy - INFO - Chain [1] start processing
03:03:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:03:12 - cmdstanpy - INFO - Chain [1] start processing
03:03:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:03:12 - cmdstanpy - INFO - Chain [1] start processing
03:03:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

03:03:13 - cmdstanpy - INFO - Chain [1] start processing
03:03:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:03:14 - cmdstanpy - INFO - Chain [1] start processing
03:03:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:03:14 - cmdstanpy - INFO - Chain [1] start processing
03:03:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:03:16 - cmdstanpy - INFO - Chain [1] start processing
03:03:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:03:16 - cmdstanpy - INFO - Chain [1] start processing
03:03:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:03:17 - cmdstanpy - INFO - Chain [1] start processing
03:03:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:03:18 - cmdstanpy - INFO - Chain [1] start processing
03:03:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:03:19 - cmdstanpy - INFO - Chain [1] start processing
03:03:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:03:20 - cmdstanpy - INFO - Chain [1] start processing
03:03:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:03:21 - cmdstanpy - INFO - Chain [1] start processing
03:03:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:03:22 - cmdstanpy - INFO - Chain [1] start processing
03:03:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

03:03:23 - cmdstanpy - INFO - Chain [1] start processing
03:03:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:03:24 - cmdstanpy - INFO - Chain [1] start processing
03:03:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:03:24 - cmdstanpy - INFO - Chain [1] start processing
03:03:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

03:03:26 - cmdstanpy - INFO - Chain [1] start processing
03:03:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:03:27 - cmdstanpy - INFO - Chain [1] start processing
03:03:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:03:28 - cmdstanpy - INFO - Chain [1] start processing
03:03:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:03:29 - cmdstanpy - INFO - Chain [1] start processing
03:03:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:03:30 - cmdstanpy - INFO - Chain [1] start processing
03:03:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:03:30 - cmdstanpy - INFO - Chain [1] start processing
03:03:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:03:31 - cmdstanpy - INFO - Chain [1] start processing
03:03:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:03:32 - cmdstanpy - INFO - Chain [1] start processing
03:03:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:03:33 - cmdstanpy - INFO - Chain [1] start processing
03:03:33 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 4 / 10....

03:03:34 - cmdstanpy - INFO - Chain [1] start processing
03:03:35 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:03:36 - cmdstanpy - INFO - Chain [1] start processing
03:03:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

03:03:38 - cmdstanpy - INFO - Chain [1] start processing
03:03:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

03:03:38 - cmdstanpy - INFO - Chain [1] start processing
03:03:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

03:03:39 - cmdstanpy - INFO - Chain [1] start processing
03:03:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

03:03:39 - cmdstanpy - INFO - Chain [1] start processing
03:03:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

03:03:40 - cmdstanpy - INFO - Chain [1] start processing
03:03:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

03:03:41 - cmdstanpy - INFO - Chain [1] start processing
03:03:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

03:03:42 - cmdstanpy - INFO - Chain [1] start processing
03:03:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

03:03:42 - cmdstanpy - INFO - Chain [1] start processing
03:03:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

03:03:43 - cmdstanpy - INFO - Chain [1] start processing
03:03:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

03:03:43 - cmdstanpy - INFO - Chain [1] start processing
03:03:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

03:03:44 - cmdstanpy - INFO - Chain [1] start processing
03:03:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

03:03:45 - cmdstanpy - INFO - Chain [1] start processing
03:03:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

03:03:45 - cmdstanpy - INFO - Chain [1] start processing
03:03:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

03:03:46 - cmdstanpy - INFO - Chain [1] start processing
03:03:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

03:03:47 - cmdstanpy - INFO - Chain [1] start processing
03:03:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

03:03:47 - cmdstanpy - INFO - Chain [1] start processing
03:03:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

03:03:48 - cmdstanpy - INFO - Chain [1] start processing
03:03:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

03:03:49 - cmdstanpy - INFO - Chain [1] start processing
03:03:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

03:03:49 - cmdstanpy - INFO - Chain [1] start processing
03:03:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

03:03:50 - cmdstanpy - INFO - Chain [1] start processing
03:03:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

03:03:51 - cmdstanpy - INFO - Chain [1] start processing
03:03:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

03:03:51 - cmdstanpy - INFO - Chain [1] start processing
03:03:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

03:03:52 - cmdstanpy - INFO - Chain [1] start processing
03:03:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

03:03:53 - cmdstanpy - INFO - Chain [1] start processing
03:03:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

03:03:54 - cmdstanpy - INFO - Chain [1] start processing
03:03:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

03:03:54 - cmdstanpy - INFO - Chain [1] start processing
03:03:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

03:03:55 - cmdstanpy - INFO - Chain [1] start processing
03:03:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

03:03:56 - cmdstanpy - INFO - Chain [1] start processing
03:03:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

03:03:56 - cmdstanpy - INFO - Chain [1] start processing
03:03:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

03:03:57 - cmdstanpy - INFO - Chain [1] start processing
03:03:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

03:03:58 - cmdstanpy - INFO - Chain [1] start processing
03:03:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

03:03:59 - cmdstanpy - INFO - Chain [1] start processing
03:03:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

03:03:59 - cmdstanpy - INFO - Chain [1] start processing
03:03:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

03:04:00 - cmdstanpy - INFO - Chain [1] start processing
03:04:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

03:04:00 - cmdstanpy - INFO - Chain [1] start processing
03:04:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

03:04:01 - cmdstanpy - INFO - Chain [1] start processing
03:04:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

03:04:02 - cmdstanpy - INFO - Chain [1] start processing
03:04:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

03:04:02 - cmdstanpy - INFO - Chain [1] start processing
03:04:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

03:04:03 - cmdstanpy - INFO - Chain [1] start processing
03:04:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

03:04:04 - cmdstanpy - INFO - Chain [1] start processing
03:04:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

03:04:04 - cmdstanpy - INFO - Chain [1] start processing
03:04:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

03:04:05 - cmdstanpy - INFO - Chain [1] start processing
03:04:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

03:04:06 - cmdstanpy - INFO - Chain [1] start processing
03:04:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

03:04:06 - cmdstanpy - INFO - Chain [1] start processing
03:04:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

03:04:07 - cmdstanpy - INFO - Chain [1] start processing
03:04:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

03:04:08 - cmdstanpy - INFO - Chain [1] start processing
03:04:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

03:04:09 - cmdstanpy - INFO - Chain [1] start processing
03:04:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

03:04:09 - cmdstanpy - INFO - Chain [1] start processing
03:04:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

03:04:10 - cmdstanpy - INFO - Chain [1] start processing
03:04:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

03:04:11 - cmdstanpy - INFO - Chain [1] start processing
03:04:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

03:04:12 - cmdstanpy - INFO - Chain [1] start processing
03:04:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

03:04:12 - cmdstanpy - INFO - Chain [1] start processing
03:04:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

03:04:13 - cmdstanpy - INFO - Chain [1] start processing
03:04:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

03:04:14 - cmdstanpy - INFO - Chain [1] start processing
03:04:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

03:04:14 - cmdstanpy - INFO - Chain [1] start processing
03:04:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

03:04:15 - cmdstanpy - INFO - Chain [1] start processing
03:04:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

03:04:16 - cmdstanpy - INFO - Chain [1] start processing
03:04:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

03:04:17 - cmdstanpy - INFO - Chain [1] start processing
03:04:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

03:04:18 - cmdstanpy - INFO - Chain [1] start processing
03:04:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:04:19 - cmdstanpy - INFO - Chain [1] start processing
03:04:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:04:19 - cmdstanpy - INFO - Chain [1] start processing
03:04:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:04:20 - cmdstanpy - INFO - Chain [1] start processing
03:04:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:04:20 - cmdstanpy - INFO - Chain [1] start processing
03:04:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:04:21 - cmdstanpy - INFO - Chain [1] start processing
03:04:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

03:04:22 - cmdstanpy - INFO - Chain [1] start processing
03:04:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:04:23 - cmdstanpy - INFO - Chain [1] start processing
03:04:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:04:24 - cmdstanpy - INFO - Chain [1] start processing
03:04:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:04:24 - cmdstanpy - INFO - Chain [1] start processing
03:04:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:04:25 - cmdstanpy - INFO - Chain [1] start processing
03:04:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:04:26 - cmdstanpy - INFO - Chain [1] start processing
03:04:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

03:04:27 - cmdstanpy - INFO - Chain [1] start processing
03:04:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:04:27 - cmdstanpy - INFO - Chain [1] start processing
03:04:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

03:04:28 - cmdstanpy - INFO - Chain [1] start processing
03:04:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:04:29 - cmdstanpy - INFO - Chain [1] start processing
03:04:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:04:30 - cmdstanpy - INFO - Chain [1] start processing
03:04:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

03:04:31 - cmdstanpy - INFO - Chain [1] start processing
03:04:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:04:31 - cmdstanpy - INFO - Chain [1] start processing
03:04:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:04:32 - cmdstanpy - INFO - Chain [1] start processing
03:04:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:04:33 - cmdstanpy - INFO - Chain [1] start processing
03:04:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:04:33 - cmdstanpy - INFO - Chain [1] start processing
03:04:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:04:34 - cmdstanpy - INFO - Chain [1] start processing
03:04:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:04:35 - cmdstanpy - INFO - Chain [1] start processing
03:04:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:04:36 - cmdstanpy - INFO - Chain [1] start processing
03:04:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:04:37 - cmdstanpy - INFO - Chain [1] start processing
03:04:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:04:37 - cmdstanpy - INFO - Chain [1] start processing
03:04:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:04:38 - cmdstanpy - INFO - Chain [1] start processing
03:04:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

03:04:39 - cmdstanpy - INFO - Chain [1] start processing
03:04:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:04:40 - cmdstanpy - INFO - Chain [1] start processing
03:04:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:04:41 - cmdstanpy - INFO - Chain [1] start processing
03:04:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

03:04:42 - cmdstanpy - INFO - Chain [1] start processing
03:04:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:04:42 - cmdstanpy - INFO - Chain [1] start processing
03:04:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:04:43 - cmdstanpy - INFO - Chain [1] start processing
03:04:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:04:44 - cmdstanpy - INFO - Chain [1] start processing
03:04:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:04:45 - cmdstanpy - INFO - Chain [1] start processing
03:04:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:04:45 - cmdstanpy - INFO - Chain [1] start processing
03:04:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:04:46 - cmdstanpy - INFO - Chain [1] start processing
03:04:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:04:47 - cmdstanpy - INFO - Chain [1] start processing
03:04:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:04:48 - cmdstanpy - INFO - Chain [1] start processing
03:04:48 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 5 / 10....

03:04:49 - cmdstanpy - INFO - Chain [1] start processing
03:04:49 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:04:50 - cmdstanpy - INFO - Chain [1] start processing
03:04:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

03:04:51 - cmdstanpy - INFO - Chain [1] start processing
03:04:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

03:04:52 - cmdstanpy - INFO - Chain [1] start processing
03:04:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

03:04:52 - cmdstanpy - INFO - Chain [1] start processing
03:04:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

03:04:53 - cmdstanpy - INFO - Chain [1] start processing
03:04:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

03:04:54 - cmdstanpy - INFO - Chain [1] start processing
03:04:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

03:04:54 - cmdstanpy - INFO - Chain [1] start processing
03:04:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

03:04:55 - cmdstanpy - INFO - Chain [1] start processing
03:04:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

03:04:55 - cmdstanpy - INFO - Chain [1] start processing
03:04:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

03:04:56 - cmdstanpy - INFO - Chain [1] start processing
03:04:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

03:04:56 - cmdstanpy - INFO - Chain [1] start processing
03:04:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

03:04:57 - cmdstanpy - INFO - Chain [1] start processing
03:04:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

03:04:58 - cmdstanpy - INFO - Chain [1] start processing
03:04:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

03:04:58 - cmdstanpy - INFO - Chain [1] start processing
03:04:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

03:04:59 - cmdstanpy - INFO - Chain [1] start processing
03:04:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

03:04:59 - cmdstanpy - INFO - Chain [1] start processing
03:04:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

03:05:00 - cmdstanpy - INFO - Chain [1] start processing
03:05:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

03:05:00 - cmdstanpy - INFO - Chain [1] start processing
03:05:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

03:05:01 - cmdstanpy - INFO - Chain [1] start processing
03:05:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

03:05:02 - cmdstanpy - INFO - Chain [1] start processing
03:05:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

03:05:02 - cmdstanpy - INFO - Chain [1] start processing
03:05:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

03:05:03 - cmdstanpy - INFO - Chain [1] start processing
03:05:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

03:05:03 - cmdstanpy - INFO - Chain [1] start processing
03:05:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

03:05:04 - cmdstanpy - INFO - Chain [1] start processing
03:05:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

03:05:05 - cmdstanpy - INFO - Chain [1] start processing
03:05:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

03:05:05 - cmdstanpy - INFO - Chain [1] start processing
03:05:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

03:05:06 - cmdstanpy - INFO - Chain [1] start processing
03:05:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

03:05:06 - cmdstanpy - INFO - Chain [1] start processing
03:05:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

03:05:07 - cmdstanpy - INFO - Chain [1] start processing
03:05:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

03:05:07 - cmdstanpy - INFO - Chain [1] start processing
03:05:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

03:05:08 - cmdstanpy - INFO - Chain [1] start processing
03:05:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

03:05:09 - cmdstanpy - INFO - Chain [1] start processing
03:05:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

03:05:09 - cmdstanpy - INFO - Chain [1] start processing
03:05:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

03:05:10 - cmdstanpy - INFO - Chain [1] start processing
03:05:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

03:05:10 - cmdstanpy - INFO - Chain [1] start processing
03:05:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

03:05:11 - cmdstanpy - INFO - Chain [1] start processing
03:05:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

03:05:12 - cmdstanpy - INFO - Chain [1] start processing
03:05:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

03:05:12 - cmdstanpy - INFO - Chain [1] start processing
03:05:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

03:05:13 - cmdstanpy - INFO - Chain [1] start processing
03:05:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

03:05:13 - cmdstanpy - INFO - Chain [1] start processing
03:05:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

03:05:14 - cmdstanpy - INFO - Chain [1] start processing
03:05:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

03:05:15 - cmdstanpy - INFO - Chain [1] start processing
03:05:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

03:05:16 - cmdstanpy - INFO - Chain [1] start processing
03:05:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

03:05:16 - cmdstanpy - INFO - Chain [1] start processing
03:05:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

03:05:17 - cmdstanpy - INFO - Chain [1] start processing
03:05:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

03:05:17 - cmdstanpy - INFO - Chain [1] start processing
03:05:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

03:05:18 - cmdstanpy - INFO - Chain [1] start processing
03:05:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

03:05:19 - cmdstanpy - INFO - Chain [1] start processing
03:05:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

03:05:19 - cmdstanpy - INFO - Chain [1] start processing
03:05:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

03:05:20 - cmdstanpy - INFO - Chain [1] start processing
03:05:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

03:05:20 - cmdstanpy - INFO - Chain [1] start processing
03:05:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

03:05:21 - cmdstanpy - INFO - Chain [1] start processing
03:05:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

03:05:21 - cmdstanpy - INFO - Chain [1] start processing
03:05:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

03:05:22 - cmdstanpy - INFO - Chain [1] start processing
03:05:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

03:05:23 - cmdstanpy - INFO - Chain [1] start processing
03:05:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

03:05:23 - cmdstanpy - INFO - Chain [1] start processing
03:05:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

03:05:24 - cmdstanpy - INFO - Chain [1] start processing
03:05:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

03:05:24 - cmdstanpy - INFO - Chain [1] start processing
03:05:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

03:05:25 - cmdstanpy - INFO - Chain [1] start processing
03:05:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

03:05:26 - cmdstanpy - INFO - Chain [1] start processing
03:05:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:05:26 - cmdstanpy - INFO - Chain [1] start processing
03:05:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:05:27 - cmdstanpy - INFO - Chain [1] start processing
03:05:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:05:28 - cmdstanpy - INFO - Chain [1] start processing
03:05:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:05:28 - cmdstanpy - INFO - Chain [1] start processing
03:05:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:05:29 - cmdstanpy - INFO - Chain [1] start processing
03:05:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

03:05:29 - cmdstanpy - INFO - Chain [1] start processing
03:05:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:05:30 - cmdstanpy - INFO - Chain [1] start processing
03:05:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:05:31 - cmdstanpy - INFO - Chain [1] start processing
03:05:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:05:32 - cmdstanpy - INFO - Chain [1] start processing
03:05:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:05:32 - cmdstanpy - INFO - Chain [1] start processing
03:05:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:05:33 - cmdstanpy - INFO - Chain [1] start processing
03:05:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

03:05:34 - cmdstanpy - INFO - Chain [1] start processing
03:05:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:05:34 - cmdstanpy - INFO - Chain [1] start processing
03:05:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

03:05:35 - cmdstanpy - INFO - Chain [1] start processing
03:05:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:05:36 - cmdstanpy - INFO - Chain [1] start processing
03:05:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:05:36 - cmdstanpy - INFO - Chain [1] start processing
03:05:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

03:05:37 - cmdstanpy - INFO - Chain [1] start processing
03:05:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:05:38 - cmdstanpy - INFO - Chain [1] start processing
03:05:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:05:38 - cmdstanpy - INFO - Chain [1] start processing
03:05:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:05:39 - cmdstanpy - INFO - Chain [1] start processing
03:05:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:05:39 - cmdstanpy - INFO - Chain [1] start processing
03:05:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:05:40 - cmdstanpy - INFO - Chain [1] start processing
03:05:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:05:40 - cmdstanpy - INFO - Chain [1] start processing
03:05:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:05:41 - cmdstanpy - INFO - Chain [1] start processing
03:05:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:05:42 - cmdstanpy - INFO - Chain [1] start processing
03:05:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:05:42 - cmdstanpy - INFO - Chain [1] start processing
03:05:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:05:43 - cmdstanpy - INFO - Chain [1] start processing
03:05:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

03:05:43 - cmdstanpy - INFO - Chain [1] start processing
03:05:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:05:44 - cmdstanpy - INFO - Chain [1] start processing
03:05:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:05:44 - cmdstanpy - INFO - Chain [1] start processing
03:05:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

03:05:45 - cmdstanpy - INFO - Chain [1] start processing
03:05:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:05:46 - cmdstanpy - INFO - Chain [1] start processing
03:05:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:05:47 - cmdstanpy - INFO - Chain [1] start processing
03:05:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:05:48 - cmdstanpy - INFO - Chain [1] start processing
03:05:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:05:48 - cmdstanpy - INFO - Chain [1] start processing
03:05:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:05:49 - cmdstanpy - INFO - Chain [1] start processing
03:05:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:05:49 - cmdstanpy - INFO - Chain [1] start processing
03:05:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:05:50 - cmdstanpy - INFO - Chain [1] start processing
03:05:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:05:51 - cmdstanpy - INFO - Chain [1] start processing
03:05:51 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 6 / 10....

03:05:52 - cmdstanpy - INFO - Chain [1] start processing
03:05:53 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:05:54 - cmdstanpy - INFO - Chain [1] start processing
03:05:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

03:05:55 - cmdstanpy - INFO - Chain [1] start processing
03:05:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

03:05:55 - cmdstanpy - INFO - Chain [1] start processing
03:05:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

03:05:56 - cmdstanpy - INFO - Chain [1] start processing
03:05:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

03:05:56 - cmdstanpy - INFO - Chain [1] start processing
03:05:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

03:05:57 - cmdstanpy - INFO - Chain [1] start processing
03:05:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

03:05:57 - cmdstanpy - INFO - Chain [1] start processing
03:05:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

03:05:58 - cmdstanpy - INFO - Chain [1] start processing
03:05:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

03:05:58 - cmdstanpy - INFO - Chain [1] start processing
03:05:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

03:05:59 - cmdstanpy - INFO - Chain [1] start processing
03:05:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  12  out of  100

03:05:59 - cmdstanpy - INFO - Chain [1] start processing
03:05:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

03:06:00 - cmdstanpy - INFO - Chain [1] start processing
03:06:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

03:06:00 - cmdstanpy - INFO - Chain [1] start processing
03:06:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

03:06:01 - cmdstanpy - INFO - Chain [1] start processing
03:06:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

03:06:01 - cmdstanpy - INFO - Chain [1] start processing
03:06:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

03:06:02 - cmdstanpy - INFO - Chain [1] start processing
03:06:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

03:06:02 - cmdstanpy - INFO - Chain [1] start processing
03:06:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

03:06:03 - cmdstanpy - INFO - Chain [1] start processing
03:06:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

03:06:03 - cmdstanpy - INFO - Chain [1] start processing
03:06:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

03:06:04 - cmdstanpy - INFO - Chain [1] start processing
03:06:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

03:06:05 - cmdstanpy - INFO - Chain [1] start processing
03:06:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

03:06:05 - cmdstanpy - INFO - Chain [1] start processing
03:06:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

03:06:06 - cmdstanpy - INFO - Chain [1] start processing
03:06:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

03:06:06 - cmdstanpy - INFO - Chain [1] start processing
03:06:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

03:06:07 - cmdstanpy - INFO - Chain [1] start processing
03:06:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

03:06:07 - cmdstanpy - INFO - Chain [1] start processing
03:06:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

03:06:08 - cmdstanpy - INFO - Chain [1] start processing
03:06:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

03:06:09 - cmdstanpy - INFO - Chain [1] start processing
03:06:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

03:06:09 - cmdstanpy - INFO - Chain [1] start processing
03:06:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

03:06:09 - cmdstanpy - INFO - Chain [1] start processing
03:06:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

03:06:10 - cmdstanpy - INFO - Chain [1] start processing
03:06:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

03:06:10 - cmdstanpy - INFO - Chain [1] start processing
03:06:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

03:06:11 - cmdstanpy - INFO - Chain [1] start processing
03:06:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

03:06:12 - cmdstanpy - INFO - Chain [1] start processing
03:06:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

03:06:12 - cmdstanpy - INFO - Chain [1] start processing
03:06:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

03:06:13 - cmdstanpy - INFO - Chain [1] start processing
03:06:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

03:06:13 - cmdstanpy - INFO - Chain [1] start processing
03:06:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

03:06:14 - cmdstanpy - INFO - Chain [1] start processing
03:06:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

03:06:14 - cmdstanpy - INFO - Chain [1] start processing
03:06:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

03:06:15 - cmdstanpy - INFO - Chain [1] start processing
03:06:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

03:06:15 - cmdstanpy - INFO - Chain [1] start processing
03:06:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

03:06:16 - cmdstanpy - INFO - Chain [1] start processing
03:06:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

03:06:17 - cmdstanpy - INFO - Chain [1] start processing
03:06:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

03:06:17 - cmdstanpy - INFO - Chain [1] start processing
03:06:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

03:06:18 - cmdstanpy - INFO - Chain [1] start processing
03:06:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

03:06:18 - cmdstanpy - INFO - Chain [1] start processing
03:06:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

03:06:19 - cmdstanpy - INFO - Chain [1] start processing
03:06:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

03:06:19 - cmdstanpy - INFO - Chain [1] start processing
03:06:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

03:06:20 - cmdstanpy - INFO - Chain [1] start processing
03:06:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

03:06:20 - cmdstanpy - INFO - Chain [1] start processing
03:06:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

03:06:21 - cmdstanpy - INFO - Chain [1] start processing
03:06:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

03:06:22 - cmdstanpy - INFO - Chain [1] start processing
03:06:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

03:06:22 - cmdstanpy - INFO - Chain [1] start processing
03:06:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

03:06:23 - cmdstanpy - INFO - Chain [1] start processing
03:06:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

03:06:23 - cmdstanpy - INFO - Chain [1] start processing
03:06:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

03:06:24 - cmdstanpy - INFO - Chain [1] start processing
03:06:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

03:06:24 - cmdstanpy - INFO - Chain [1] start processing
03:06:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

03:06:25 - cmdstanpy - INFO - Chain [1] start processing
03:06:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

03:06:25 - cmdstanpy - INFO - Chain [1] start processing
03:06:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

03:06:26 - cmdstanpy - INFO - Chain [1] start processing
03:06:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:06:27 - cmdstanpy - INFO - Chain [1] start processing
03:06:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:06:27 - cmdstanpy - INFO - Chain [1] start processing
03:06:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:06:28 - cmdstanpy - INFO - Chain [1] start processing
03:06:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:06:28 - cmdstanpy - INFO - Chain [1] start processing
03:06:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:06:29 - cmdstanpy - INFO - Chain [1] start processing
03:06:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

03:06:29 - cmdstanpy - INFO - Chain [1] start processing
03:06:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:06:30 - cmdstanpy - INFO - Chain [1] start processing
03:06:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:06:30 - cmdstanpy - INFO - Chain [1] start processing
03:06:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:06:31 - cmdstanpy - INFO - Chain [1] start processing
03:06:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:06:31 - cmdstanpy - INFO - Chain [1] start processing
03:06:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:06:32 - cmdstanpy - INFO - Chain [1] start processing
03:06:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

03:06:32 - cmdstanpy - INFO - Chain [1] start processing
03:06:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:06:33 - cmdstanpy - INFO - Chain [1] start processing
03:06:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

03:06:34 - cmdstanpy - INFO - Chain [1] start processing
03:06:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:06:34 - cmdstanpy - INFO - Chain [1] start processing
03:06:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:06:35 - cmdstanpy - INFO - Chain [1] start processing
03:06:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

03:06:35 - cmdstanpy - INFO - Chain [1] start processing
03:06:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:06:36 - cmdstanpy - INFO - Chain [1] start processing
03:06:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:06:36 - cmdstanpy - INFO - Chain [1] start processing
03:06:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:06:37 - cmdstanpy - INFO - Chain [1] start processing
03:06:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:06:38 - cmdstanpy - INFO - Chain [1] start processing
03:06:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:06:38 - cmdstanpy - INFO - Chain [1] start processing
03:06:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:06:38 - cmdstanpy - INFO - Chain [1] start processing
03:06:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:06:39 - cmdstanpy - INFO - Chain [1] start processing
03:06:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:06:40 - cmdstanpy - INFO - Chain [1] start processing
03:06:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:06:40 - cmdstanpy - INFO - Chain [1] start processing
03:06:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:06:41 - cmdstanpy - INFO - Chain [1] start processing
03:06:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

03:06:41 - cmdstanpy - INFO - Chain [1] start processing
03:06:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:06:42 - cmdstanpy - INFO - Chain [1] start processing
03:06:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:06:43 - cmdstanpy - INFO - Chain [1] start processing
03:06:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

03:06:43 - cmdstanpy - INFO - Chain [1] start processing
03:06:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:06:44 - cmdstanpy - INFO - Chain [1] start processing
03:06:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:06:45 - cmdstanpy - INFO - Chain [1] start processing
03:06:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:06:45 - cmdstanpy - INFO - Chain [1] start processing
03:06:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:06:46 - cmdstanpy - INFO - Chain [1] start processing
03:06:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:06:47 - cmdstanpy - INFO - Chain [1] start processing
03:06:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:06:47 - cmdstanpy - INFO - Chain [1] start processing
03:06:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:06:47 - cmdstanpy - INFO - Chain [1] start processing
03:06:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:06:48 - cmdstanpy - INFO - Chain [1] start processing
03:06:48 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 7 / 10....

03:06:49 - cmdstanpy - INFO - Chain [1] start processing
03:06:49 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:06:50 - cmdstanpy - INFO - Chain [1] start processing
03:06:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  3  out of  100

03:06:51 - cmdstanpy - INFO - Chain [1] start processing
03:06:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

03:06:51 - cmdstanpy - INFO - Chain [1] start processing
03:06:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  5  out of  100

03:06:52 - cmdstanpy - INFO - Chain [1] start processing
03:06:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

03:06:52 - cmdstanpy - INFO - Chain [1] start processing
03:06:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

03:06:53 - cmdstanpy - INFO - Chain [1] start processing
03:06:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

03:06:53 - cmdstanpy - INFO - Chain [1] start processing
03:06:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  9  out of  100

03:06:53 - cmdstanpy - INFO - Chain [1] start processing
03:06:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  10  out of  100

03:06:54 - cmdstanpy - INFO - Chain [1] start processing
03:06:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

03:06:54 - cmdstanpy - INFO - Chain [1] start processing
03:06:55 - cmdstanpy - INFO - Chain [1] done processing
03:06:55 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  12  out of  100

03:06:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

03:06:55 - cmdstanpy - INFO - Chain [1] start processing
03:06:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

03:06:56 - cmdstanpy - INFO - Chain [1] start processing
03:06:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

03:06:56 - cmdstanpy - INFO - Chain [1] start processing
03:06:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

03:06:57 - cmdstanpy - INFO - Chain [1] start processing
03:06:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  17  out of  100

03:06:57 - cmdstanpy - INFO - Chain [1] start processing
03:06:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  18  out of  100

03:06:58 - cmdstanpy - INFO - Chain [1] start processing
03:06:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

03:06:58 - cmdstanpy - INFO - Chain [1] start processing
03:06:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

03:06:59 - cmdstanpy - INFO - Chain [1] start processing
03:06:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

03:06:59 - cmdstanpy - INFO - Chain [1] start processing
03:06:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

03:07:00 - cmdstanpy - INFO - Chain [1] start processing
03:07:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

03:07:00 - cmdstanpy - INFO - Chain [1] start processing
03:07:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

03:07:00 - cmdstanpy - INFO - Chain [1] start processing
03:07:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

03:07:01 - cmdstanpy - INFO - Chain [1] start processing
03:07:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

03:07:01 - cmdstanpy - INFO - Chain [1] start processing
03:07:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

03:07:02 - cmdstanpy - INFO - Chain [1] start processing
03:07:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  28  out of  100

03:07:02 - cmdstanpy - INFO - Chain [1] start processing
03:07:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

03:07:03 - cmdstanpy - INFO - Chain [1] start processing
03:07:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  30  out of  100

03:07:04 - cmdstanpy - INFO - Chain [1] start processing
03:07:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  31  out of  100

03:07:04 - cmdstanpy - INFO - Chain [1] start processing
03:07:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

03:07:05 - cmdstanpy - INFO - Chain [1] start processing
03:07:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  33  out of  100

03:07:05 - cmdstanpy - INFO - Chain [1] start processing
03:07:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

03:07:06 - cmdstanpy - INFO - Chain [1] start processing
03:07:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

03:07:06 - cmdstanpy - INFO - Chain [1] start processing
03:07:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

03:07:07 - cmdstanpy - INFO - Chain [1] start processing
03:07:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

03:07:07 - cmdstanpy - INFO - Chain [1] start processing
03:07:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  38  out of  100

03:07:08 - cmdstanpy - INFO - Chain [1] start processing
03:07:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

03:07:08 - cmdstanpy - INFO - Chain [1] start processing
03:07:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

03:07:09 - cmdstanpy - INFO - Chain [1] start processing
03:07:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

03:07:09 - cmdstanpy - INFO - Chain [1] start processing
03:07:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

03:07:10 - cmdstanpy - INFO - Chain [1] start processing
03:07:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

03:07:10 - cmdstanpy - INFO - Chain [1] start processing
03:07:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

03:07:10 - cmdstanpy - INFO - Chain [1] start processing
03:07:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

03:07:11 - cmdstanpy - INFO - Chain [1] start processing
03:07:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

03:07:11 - cmdstanpy - INFO - Chain [1] start processing
03:07:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

03:07:12 - cmdstanpy - INFO - Chain [1] start processing
03:07:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  48  out of  100

03:07:12 - cmdstanpy - INFO - Chain [1] start processing
03:07:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

03:07:13 - cmdstanpy - INFO - Chain [1] start processing
03:07:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

03:07:13 - cmdstanpy - INFO - Chain [1] start processing
03:07:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  51  out of  100

03:07:14 - cmdstanpy - INFO - Chain [1] start processing
03:07:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

03:07:14 - cmdstanpy - INFO - Chain [1] start processing
03:07:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

03:07:15 - cmdstanpy - INFO - Chain [1] start processing
03:07:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  54  out of  100

03:07:15 - cmdstanpy - INFO - Chain [1] start processing
03:07:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

03:07:16 - cmdstanpy - INFO - Chain [1] start processing
03:07:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

03:07:16 - cmdstanpy - INFO - Chain [1] start processing
03:07:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  57  out of  100

03:07:16 - cmdstanpy - INFO - Chain [1] start processing
03:07:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

03:07:17 - cmdstanpy - INFO - Chain [1] start processing
03:07:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

03:07:17 - cmdstanpy - INFO - Chain [1] start processing
03:07:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  60  out of  100

03:07:18 - cmdstanpy - INFO - Chain [1] start processing
03:07:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

03:07:18 - cmdstanpy - INFO - Chain [1] start processing
03:07:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:07:19 - cmdstanpy - INFO - Chain [1] start processing
03:07:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:07:19 - cmdstanpy - INFO - Chain [1] start processing
03:07:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:07:20 - cmdstanpy - INFO - Chain [1] start processing
03:07:20 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:07:20 - cmdstanpy - INFO - Chain [1] start processing
03:07:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:07:21 - cmdstanpy - INFO - Chain [1] start processing
03:07:21 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  67  out of  100

03:07:22 - cmdstanpy - INFO - Chain [1] start processing
03:07:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:07:22 - cmdstanpy - INFO - Chain [1] start processing
03:07:22 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:07:23 - cmdstanpy - INFO - Chain [1] start processing
03:07:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:07:23 - cmdstanpy - INFO - Chain [1] start processing
03:07:23 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:07:23 - cmdstanpy - INFO - Chain [1] start processing
03:07:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:07:24 - cmdstanpy - INFO - Chain [1] start processing
03:07:24 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  73  out of  100

03:07:25 - cmdstanpy - INFO - Chain [1] start processing
03:07:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:07:25 - cmdstanpy - INFO - Chain [1] start processing
03:07:25 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  75  out of  100

03:07:25 - cmdstanpy - INFO - Chain [1] start processing
03:07:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:07:26 - cmdstanpy - INFO - Chain [1] start processing
03:07:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:07:26 - cmdstanpy - INFO - Chain [1] start processing
03:07:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  78  out of  100

03:07:27 - cmdstanpy - INFO - Chain [1] start processing
03:07:27 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:07:27 - cmdstanpy - INFO - Chain [1] start processing
03:07:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:07:28 - cmdstanpy - INFO - Chain [1] start processing
03:07:28 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:07:29 - cmdstanpy - INFO - Chain [1] start processing
03:07:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:07:29 - cmdstanpy - INFO - Chain [1] start processing
03:07:29 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:07:30 - cmdstanpy - INFO - Chain [1] start processing
03:07:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:07:30 - cmdstanpy - INFO - Chain [1] start processing
03:07:30 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:07:30 - cmdstanpy - INFO - Chain [1] start processing
03:07:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:07:31 - cmdstanpy - INFO - Chain [1] start processing
03:07:31 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:07:31 - cmdstanpy - INFO - Chain [1] start processing
03:07:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:07:32 - cmdstanpy - INFO - Chain [1] start processing
03:07:32 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  89  out of  100

03:07:33 - cmdstanpy - INFO - Chain [1] start processing
03:07:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:07:33 - cmdstanpy - INFO - Chain [1] start processing
03:07:33 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:07:34 - cmdstanpy - INFO - Chain [1] start processing
03:07:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  92  out of  100

03:07:34 - cmdstanpy - INFO - Chain [1] start processing
03:07:34 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:07:35 - cmdstanpy - INFO - Chain [1] start processing
03:07:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:07:35 - cmdstanpy - INFO - Chain [1] start processing
03:07:35 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:07:35 - cmdstanpy - INFO - Chain [1] start processing
03:07:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:07:36 - cmdstanpy - INFO - Chain [1] start processing
03:07:36 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:07:36 - cmdstanpy - INFO - Chain [1] start processing
03:07:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:07:37 - cmdstanpy - INFO - Chain [1] start processing
03:07:37 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:07:37 - cmdstanpy - INFO - Chain [1] start processing
03:07:38 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:07:38 - cmdstanpy - INFO - Chain [1] start processing
03:07:38 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 8 / 10....

03:07:39 - cmdstanpy - INFO - Chain [1] start processing
03:07:39 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:07:39 - cmdstanpy - INFO - Chain [1] start processing
03:07:40 - cmdstanpy - INFO - Chain [1] done processing
03:07:40 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  3  out of  100

03:07:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  4  out of  100

03:07:40 - cmdstanpy - INFO - Chain [1] start processing
03:07:40 - cmdstanpy - INFO - Chain [1] done processing
03:07:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  5  out of  100

03:07:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  6  out of  100

03:07:41 - cmdstanpy - INFO - Chain [1] start processing
03:07:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  7  out of  100

03:07:41 - cmdstanpy - INFO - Chain [1] start processing
03:07:42 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  8  out of  100

03:07:42 - cmdstanpy - INFO - Chain [1] start processing
03:07:42 - cmdstanpy - INFO - Chain [1] done processing
03:07:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  9  out of  100

03:07:42 - cmdstanpy - INFO - Chain [1] done processing
03:07:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  10  out of  100

03:07:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  11  out of  100

03:07:43 - cmdstanpy - INFO - Chain [1] start processing
03:07:43 - cmdstanpy - INFO - Chain [1] done processing
03:07:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  12  out of  100

03:07:43 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  13  out of  100

03:07:44 - cmdstanpy - INFO - Chain [1] start processing
03:07:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  14  out of  100

03:07:44 - cmdstanpy - INFO - Chain [1] start processing
03:07:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  15  out of  100

03:07:45 - cmdstanpy - INFO - Chain [1] start processing
03:07:45 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  16  out of  100

03:07:45 - cmdstanpy - INFO - Chain [1] start processing
03:07:45 - cmdstanpy - INFO - Chain [1] done processing
03:07:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  17  out of  100

03:07:46 - cmdstanpy - INFO - Chain [1] done processing
03:07:46 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  18  out of  100

03:07:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  19  out of  100

03:07:46 - cmdstanpy - INFO - Chain [1] start processing
03:07:46 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  20  out of  100

03:07:46 - cmdstanpy - INFO - Chain [1] start processing
03:07:47 - cmdstanpy - INFO - Chain [1] done processing
03:07:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  21  out of  100

03:07:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  22  out of  100

03:07:47 - cmdstanpy - INFO - Chain [1] start processing
03:07:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  23  out of  100

03:07:48 - cmdstanpy - INFO - Chain [1] start processing
03:07:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  24  out of  100

03:07:48 - cmdstanpy - INFO - Chain [1] start processing
03:07:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  25  out of  100

03:07:48 - cmdstanpy - INFO - Chain [1] start processing
03:07:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  26  out of  100

03:07:49 - cmdstanpy - INFO - Chain [1] start processing
03:07:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  27  out of  100

03:07:49 - cmdstanpy - INFO - Chain [1] start processing
03:07:49 - cmdstanpy - INFO - Chain [1] done processing
03:07:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  28  out of  100

03:07:50 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  29  out of  100

03:07:50 - cmdstanpy - INFO - Chain [1] start processing
03:07:50 - cmdstanpy - INFO - Chain [1] done processing
03:07:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  30  out of  100

03:07:50 - cmdstanpy - INFO - Chain [1] done processing
03:07:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  31  out of  100

03:07:51 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  32  out of  100

03:07:51 - cmdstanpy - INFO - Chain [1] start processing
03:07:51 - cmdstanpy - INFO - Chain [1] done processing
03:07:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  33  out of  100

03:07:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  34  out of  100

03:07:52 - cmdstanpy - INFO - Chain [1] start processing
03:07:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  35  out of  100

03:07:52 - cmdstanpy - INFO - Chain [1] start processing
03:07:52 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  36  out of  100

03:07:53 - cmdstanpy - INFO - Chain [1] start processing
03:07:53 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  37  out of  100

03:07:53 - cmdstanpy - INFO - Chain [1] start processing
03:07:53 - cmdstanpy - INFO - Chain [1] done processing
03:07:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  38  out of  100

03:07:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  39  out of  100

03:07:54 - cmdstanpy - INFO - Chain [1] start processing
03:07:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  40  out of  100

03:07:54 - cmdstanpy - INFO - Chain [1] start processing
03:07:54 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  41  out of  100

03:07:55 - cmdstanpy - INFO - Chain [1] start processing
03:07:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  42  out of  100

03:07:55 - cmdstanpy - INFO - Chain [1] start processing
03:07:55 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  43  out of  100

03:07:55 - cmdstanpy - INFO - Chain [1] start processing
03:07:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  44  out of  100

03:07:56 - cmdstanpy - INFO - Chain [1] start processing
03:07:56 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  45  out of  100

03:07:56 - cmdstanpy - INFO - Chain [1] start processing
03:07:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  46  out of  100

03:07:57 - cmdstanpy - INFO - Chain [1] start processing
03:07:57 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  47  out of  100

03:07:57 - cmdstanpy - INFO - Chain [1] start processing
03:07:57 - cmdstanpy - INFO - Chain [1] done processing
03:07:58 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  48  out of  100

03:07:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  49  out of  100

03:07:58 - cmdstanpy - INFO - Chain [1] start processing
03:07:58 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  50  out of  100

03:07:59 - cmdstanpy - INFO - Chain [1] start processing
03:07:59 - cmdstanpy - INFO - Chain [1] done processing
03:07:59 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  51  out of  100

03:07:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  52  out of  100

03:07:59 - cmdstanpy - INFO - Chain [1] start processing
03:07:59 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  53  out of  100

03:08:00 - cmdstanpy - INFO - Chain [1] start processing
03:08:00 - cmdstanpy - INFO - Chain [1] done processing
03:08:00 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  54  out of  100

03:08:00 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  55  out of  100

03:08:00 - cmdstanpy - INFO - Chain [1] start processing
03:08:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  56  out of  100

03:08:01 - cmdstanpy - INFO - Chain [1] start processing
03:08:01 - cmdstanpy - INFO - Chain [1] done processing
03:08:01 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  57  out of  100

03:08:01 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  58  out of  100

03:08:02 - cmdstanpy - INFO - Chain [1] start processing
03:08:02 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  59  out of  100

03:08:02 - cmdstanpy - INFO - Chain [1] start processing
03:08:02 - cmdstanpy - INFO - Chain [1] done processing
03:08:03 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  60  out of  100

03:08:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  61  out of  100

03:08:03 - cmdstanpy - INFO - Chain [1] start processing
03:08:03 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:08:03 - cmdstanpy - INFO - Chain [1] start processing
03:08:03 - cmdstanpy - INFO - Chain [1] done processing
03:08:04 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  63  out of  100

03:08:04 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  64  out of  100

03:08:04 - cmdstanpy - INFO - Chain [1] start processing
03:08:04 - cmdstanpy - INFO - Chain [1] done processing
03:08:05 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  65  out of  100

03:08:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  66  out of  100

03:08:05 - cmdstanpy - INFO - Chain [1] start processing
03:08:05 - cmdstanpy - INFO - Chain [1] done processing
03:08:05 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  67  out of  100

03:08:05 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  68  out of  100

03:08:06 - cmdstanpy - INFO - Chain [1] start processing
03:08:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  69  out of  100

03:08:06 - cmdstanpy - INFO - Chain [1] start processing
03:08:06 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  70  out of  100

03:08:06 - cmdstanpy - INFO - Chain [1] start processing
03:08:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  71  out of  100

03:08:07 - cmdstanpy - INFO - Chain [1] start processing
03:08:07 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  72  out of  100

03:08:07 - cmdstanpy - INFO - Chain [1] start processing
03:08:08 - cmdstanpy - INFO - Chain [1] done processing
03:08:08 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  73  out of  100

03:08:08 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:08:08 - cmdstanpy - INFO - Chain [1] start processing
03:08:08 - cmdstanpy - INFO - Chain [1] done processing
03:08:09 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  75  out of  100

03:08:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  76  out of  100

03:08:09 - cmdstanpy - INFO - Chain [1] start processing
03:08:09 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  77  out of  100

03:08:09 - cmdstanpy - INFO - Chain [1] start processing
03:08:10 - cmdstanpy - INFO - Chain [1] done processing
03:08:10 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  78  out of  100

03:08:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  79  out of  100

03:08:10 - cmdstanpy - INFO - Chain [1] start processing
03:08:10 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  80  out of  100

03:08:11 - cmdstanpy - INFO - Chain [1] start processing
03:08:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  81  out of  100

03:08:11 - cmdstanpy - INFO - Chain [1] start processing
03:08:11 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  82  out of  100

03:08:12 - cmdstanpy - INFO - Chain [1] start processing
03:08:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  83  out of  100

03:08:12 - cmdstanpy - INFO - Chain [1] start processing
03:08:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  84  out of  100

03:08:12 - cmdstanpy - INFO - Chain [1] start processing
03:08:12 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:08:13 - cmdstanpy - INFO - Chain [1] start processing
03:08:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  86  out of  100

03:08:13 - cmdstanpy - INFO - Chain [1] start processing
03:08:13 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:08:14 - cmdstanpy - INFO - Chain [1] start processing
03:08:14 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  88  out of  100

03:08:14 - cmdstanpy - INFO - Chain [1] start processing
03:08:14 - cmdstanpy - INFO - Chain [1] done processing
03:08:15 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  89  out of  100

03:08:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:08:15 - cmdstanpy - INFO - Chain [1] start processing
03:08:15 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  91  out of  100

03:08:15 - cmdstanpy - INFO - Chain [1] start processing
03:08:16 - cmdstanpy - INFO - Chain [1] done processing
03:08:16 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  92  out of  100

03:08:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  93  out of  100

03:08:16 - cmdstanpy - INFO - Chain [1] start processing
03:08:16 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  94  out of  100

03:08:17 - cmdstanpy - INFO - Chain [1] start processing
03:08:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  95  out of  100

03:08:17 - cmdstanpy - INFO - Chain [1] start processing
03:08:17 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  96  out of  100

03:08:18 - cmdstanpy - INFO - Chain [1] start processing
03:08:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  97  out of  100

03:08:18 - cmdstanpy - INFO - Chain [1] start processing
03:08:18 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  98  out of  100

03:08:18 - cmdstanpy - INFO - Chain [1] start processing
03:08:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  99  out of  100

03:08:19 - cmdstanpy - INFO - Chain [1] start processing
03:08:19 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  100  out of  100

03:08:19 - cmdstanpy - INFO - Chain [1] start processing
03:08:20 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 9 / 10....

03:08:20 - cmdstanpy - INFO - Chain [1] start processing
03:08:20 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:171: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.rename(columns={'datetime': 'ds'}, inplace=True)

Processing i =  1  out of  100
Processing i =  2  out of  100

03:08:21 - cmdstanpy - INFO - Chain [1] start processing
03:08:21 - cmdstanpy - INFO - Chain [1] done processing
03:08:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  3  out of  100

03:08:21 - cmdstanpy - INFO - Chain [1] done processing
03:08:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  4  out of  100

03:08:21 - cmdstanpy - INFO - Chain [1] done processing
03:08:21 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  5  out of  100

03:08:22 - cmdstanpy - INFO - Chain [1] done processing
03:08:22 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  6  out of  100

03:08:22 - cmdstanpy - INFO - Chain [1] done processing
03:08:22 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  7  out of  100

03:08:22 - cmdstanpy - INFO - Chain [1] done processing
03:08:22 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  8  out of  100

03:08:22 - cmdstanpy - INFO - Chain [1] done processing
03:08:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  9  out of  100

03:08:23 - cmdstanpy - INFO - Chain [1] done processing
03:08:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  10  out of  100

03:08:23 - cmdstanpy - INFO - Chain [1] done processing
03:08:23 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  11  out of  100

03:08:23 - cmdstanpy - INFO - Chain [1] done processing
03:08:24 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  12  out of  100

03:08:24 - cmdstanpy - INFO - Chain [1] done processing
03:08:24 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  13  out of  100

03:08:24 - cmdstanpy - INFO - Chain [1] done processing
03:08:24 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  14  out of  100

03:08:24 - cmdstanpy - INFO - Chain [1] done processing
03:08:24 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  15  out of  100

03:08:25 - cmdstanpy - INFO - Chain [1] done processing
03:08:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  16  out of  100

03:08:25 - cmdstanpy - INFO - Chain [1] done processing
03:08:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  17  out of  100

03:08:25 - cmdstanpy - INFO - Chain [1] done processing
03:08:25 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  18  out of  100

03:08:26 - cmdstanpy - INFO - Chain [1] done processing
03:08:26 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  19  out of  100

03:08:26 - cmdstanpy - INFO - Chain [1] done processing
03:08:26 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  20  out of  100

03:08:26 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  21  out of  100

03:08:26 - cmdstanpy - INFO - Chain [1] start processing
03:08:26 - cmdstanpy - INFO - Chain [1] done processing
03:08:27 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  22  out of  100

03:08:27 - cmdstanpy - INFO - Chain [1] done processing
03:08:27 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  23  out of  100

03:08:27 - cmdstanpy - INFO - Chain [1] done processing
03:08:27 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  24  out of  100

03:08:27 - cmdstanpy - INFO - Chain [1] done processing
03:08:27 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  25  out of  100

03:08:28 - cmdstanpy - INFO - Chain [1] done processing
03:08:28 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  26  out of  100

03:08:28 - cmdstanpy - INFO - Chain [1] done processing
03:08:28 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  27  out of  100

03:08:28 - cmdstanpy - INFO - Chain [1] done processing
03:08:28 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  28  out of  100

03:08:29 - cmdstanpy - INFO - Chain [1] done processing
03:08:29 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  29  out of  100

03:08:29 - cmdstanpy - INFO - Chain [1] done processing
03:08:29 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  30  out of  100

03:08:29 - cmdstanpy - INFO - Chain [1] done processing
03:08:29 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  31  out of  100

03:08:30 - cmdstanpy - INFO - Chain [1] done processing
03:08:30 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  32  out of  100

03:08:30 - cmdstanpy - INFO - Chain [1] done processing
03:08:30 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  33  out of  100

03:08:30 - cmdstanpy - INFO - Chain [1] done processing
03:08:30 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  34  out of  100

03:08:30 - cmdstanpy - INFO - Chain [1] done processing
03:08:31 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  35  out of  100

03:08:31 - cmdstanpy - INFO - Chain [1] done processing
03:08:31 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  36  out of  100

03:08:31 - cmdstanpy - INFO - Chain [1] done processing
03:08:31 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  37  out of  100

03:08:31 - cmdstanpy - INFO - Chain [1] done processing
03:08:32 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  38  out of  100

03:08:32 - cmdstanpy - INFO - Chain [1] done processing
03:08:32 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  39  out of  100

03:08:32 - cmdstanpy - INFO - Chain [1] done processing
03:08:32 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  40  out of  100

03:08:32 - cmdstanpy - INFO - Chain [1] done processing
03:08:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  41  out of  100

03:08:33 - cmdstanpy - INFO - Chain [1] done processing
03:08:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  42  out of  100

03:08:33 - cmdstanpy - INFO - Chain [1] done processing
03:08:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  43  out of  100

03:08:33 - cmdstanpy - INFO - Chain [1] done processing
03:08:33 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  44  out of  100

03:08:34 - cmdstanpy - INFO - Chain [1] done processing
03:08:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  45  out of  100

03:08:34 - cmdstanpy - INFO - Chain [1] done processing
03:08:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  46  out of  100

03:08:34 - cmdstanpy - INFO - Chain [1] done processing
03:08:34 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  47  out of  100

03:08:35 - cmdstanpy - INFO - Chain [1] done processing
03:08:35 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  48  out of  100

03:08:35 - cmdstanpy - INFO - Chain [1] done processing
03:08:35 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  49  out of  100

03:08:35 - cmdstanpy - INFO - Chain [1] done processing
03:08:35 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  50  out of  100

03:08:36 - cmdstanpy - INFO - Chain [1] done processing
03:08:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  51  out of  100

03:08:36 - cmdstanpy - INFO - Chain [1] done processing
03:08:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  52  out of  100

03:08:36 - cmdstanpy - INFO - Chain [1] done processing
03:08:36 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  53  out of  100

03:08:37 - cmdstanpy - INFO - Chain [1] done processing
03:08:37 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  54  out of  100

03:08:37 - cmdstanpy - INFO - Chain [1] done processing
03:08:37 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  55  out of  100

03:08:37 - cmdstanpy - INFO - Chain [1] done processing
03:08:38 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  56  out of  100

03:08:38 - cmdstanpy - INFO - Chain [1] done processing
03:08:38 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  57  out of  100

03:08:38 - cmdstanpy - INFO - Chain [1] done processing
03:08:38 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  58  out of  100

03:08:38 - cmdstanpy - INFO - Chain [1] done processing
03:08:39 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  59  out of  100

03:08:39 - cmdstanpy - INFO - Chain [1] done processing
03:08:39 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  60  out of  100

03:08:39 - cmdstanpy - INFO - Chain [1] done processing
03:08:39 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  61  out of  100

03:08:39 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  62  out of  100

03:08:40 - cmdstanpy - INFO - Chain [1] start processing
03:08:40 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  63  out of  100

03:08:40 - cmdstanpy - INFO - Chain [1] start processing
03:08:40 - cmdstanpy - INFO - Chain [1] done processing
03:08:40 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  64  out of  100

03:08:41 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  65  out of  100

03:08:41 - cmdstanpy - INFO - Chain [1] start processing
03:08:41 - cmdstanpy - INFO - Chain [1] done processing
03:08:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  66  out of  100

03:08:41 - cmdstanpy - INFO - Chain [1] done processing
03:08:41 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  67  out of  100

03:08:42 - cmdstanpy - INFO - Chain [1] done processing
03:08:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  68  out of  100

03:08:42 - cmdstanpy - INFO - Chain [1] done processing
03:08:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  69  out of  100

03:08:42 - cmdstanpy - INFO - Chain [1] done processing
03:08:42 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  70  out of  100

03:08:43 - cmdstanpy - INFO - Chain [1] done processing
03:08:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  71  out of  100

03:08:43 - cmdstanpy - INFO - Chain [1] done processing
03:08:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  72  out of  100

03:08:43 - cmdstanpy - INFO - Chain [1] done processing
03:08:43 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  73  out of  100

03:08:44 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  74  out of  100

03:08:44 - cmdstanpy - INFO - Chain [1] start processing
03:08:44 - cmdstanpy - INFO - Chain [1] done processing
03:08:44 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  75  out of  100

03:08:44 - cmdstanpy - INFO - Chain [1] done processing
03:08:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  76  out of  100

03:08:45 - cmdstanpy - INFO - Chain [1] done processing
03:08:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  77  out of  100

03:08:45 - cmdstanpy - INFO - Chain [1] done processing
03:08:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  78  out of  100

03:08:45 - cmdstanpy - INFO - Chain [1] done processing
03:08:45 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  79  out of  100

03:08:46 - cmdstanpy - INFO - Chain [1] done processing
03:08:46 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  80  out of  100

03:08:46 - cmdstanpy - INFO - Chain [1] done processing
03:08:46 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  81  out of  100

03:08:46 - cmdstanpy - INFO - Chain [1] done processing
03:08:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  82  out of  100

03:08:47 - cmdstanpy - INFO - Chain [1] done processing
03:08:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  83  out of  100

03:08:47 - cmdstanpy - INFO - Chain [1] done processing
03:08:47 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  84  out of  100

03:08:47 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  85  out of  100

03:08:48 - cmdstanpy - INFO - Chain [1] start processing
03:08:48 - cmdstanpy - INFO - Chain [1] done processing
03:08:48 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  86  out of  100

03:08:48 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  87  out of  100

03:08:48 - cmdstanpy - INFO - Chain [1] start processing
03:08:49 - cmdstanpy - INFO - Chain [1] done processing
03:08:49 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  88  out of  100

03:08:49 - cmdstanpy - INFO - Chain [1] done processing
03:08:49 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  89  out of  100

03:08:49 - cmdstanpy - INFO - Chain [1] done processing

Processing i =  90  out of  100

03:08:49 - cmdstanpy - INFO - Chain [1] start processing
03:08:50 - cmdstanpy - INFO - Chain [1] done processing
03:08:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  91  out of  100

03:08:50 - cmdstanpy - INFO - Chain [1] done processing
03:08:50 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  92  out of  100

03:08:50 - cmdstanpy - INFO - Chain [1] done processing
03:08:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  93  out of  100

03:08:51 - cmdstanpy - INFO - Chain [1] done processing
03:08:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  94  out of  100

03:08:51 - cmdstanpy - INFO - Chain [1] done processing
03:08:51 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  95  out of  100

03:08:51 - cmdstanpy - INFO - Chain [1] done processing
03:08:52 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  96  out of  100

03:08:52 - cmdstanpy - INFO - Chain [1] done processing
03:08:52 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  97  out of  100

03:08:52 - cmdstanpy - INFO - Chain [1] done processing
03:08:52 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  98  out of  100

03:08:53 - cmdstanpy - INFO - Chain [1] done processing
03:08:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  99  out of  100

03:08:53 - cmdstanpy - INFO - Chain [1] done processing
03:08:53 - cmdstanpy - INFO - Chain [1] start processing

Processing i =  100  out of  100

03:08:53 - cmdstanpy - INFO - Chain [1] done processing

Processing CV 10 / 10....

03:08:54 - cmdstanpy - INFO - Chain [1] start processing
03:08:55 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\models\m16_prophet.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_exog.rename(columns={'datetime': 'ds'}, inplace=True)

Test set is before train set / CV 10, no test forecast can be made

[run 36/36] ds18 m4 hp1
Pass Test 1 - Forecast horizon is >= dataset frequency
Pass Test 2 - Hyperparameter choice is possible given the forecast horizon
Processing CV 1 / 10....
Processing i =  1  out of  1344
Processing i =  2  out of  1344
Processing i =  3  out of  1344
Processing i =  4  out of  1344
Processing i =  5  out of  1344
Processing i =  6  out of  1344
Processing i =  7  out of  1344
Processing i =  8  out of  1344
Processing i =  9  out of  1344
Processing i =  10  out of  1344
Processing i =  11  out of  1344
Processing i =  12  out of  1344
Processing i =  13  out of  1344
Processing i =  14  out of  1344
Processing i =  15  out of  1344
Processing i =  16  out of  1344
Processing i =  17  out of  1344
Processing i =  18  out of  1344
Processing i =  19  out of  1344
Processing i =  20  out of  1344
Processing i =  21  out of  1344
Processing i =  22  out of  1344
Processing i =  23  out of  1344
Processing i =  24  out of  1344
Processing i =  25  out of  1344
Processing i =  26  out of  1344
Processing i =  27  out of  1344
Processing i =  28  out of  1344
Processing i =  29  out of  1344
Processing i =  30  out of  1344
Processing i =  31  out of  1344
Processing i =  32  out of  1344
Processing i =  33  out of  1344
Processing i =  34  out of  1344
Processing i =  35  out of  1344
Processing i =  36  out of  1344
Processing i =  37  out of  1344
Processing i =  38  out of  1344
Processing i =  39  out of  1344
Processing i =  40  out of  1344
Processing i =  41  out of  1344
Processing i =  42  out of  1344
Processing i =  43  out of  1344
Processing i =  44  out of  1344
Processing i =  45  out of  1344
Processing i =  46  out of  1344
Processing i =  47  out of  1344
Processing i =  48  out of  1344
Processing i =  49  out of  1344
Processing i =  50  out of  1344
Processing i =  51  out of  1344
Processing i =  52  out of  1344
Processing i =  53  out of  1344
Processing i =  54  out of  1344
Processing i =  55  out of  1344
Processing i =  56  out of  1344
Processing i =  57  out of  1344
Processing i =  58  out of  1344
Processing i =  59  out of  1344
Processing i =  60  out of  1344
Processing i =  61  out of  1344
Processing i =  62  out of  1344
Processing i =  63  out of  1344
Processing i =  64  out of  1344
Processing i =  65  out of  1344
Processing i =  66  out of  1344
Processing i =  67  out of  1344
Processing i =  68  out of  1344
Processing i =  69  out of  1344
Processing i =  70  out of  1344
Processing i =  71  out of  1344
Processing i =  72  out of  1344
Processing i =  73  out of  1344
Processing i =  74  out of  1344
Processing i =  75  out of  1344
Processing i =  76  out of  1344
Processing i =  77  out of  1344
Processing i =  78  out of  1344
Processing i =  79  out of  1344
Processing i =  80  out of  1344
Processing i =  81  out of  1344
Processing i =  82  out of  1344
Processing i =  83  out of  1344
Processing i =  84  out of  1344
Processing i =  85  out of  1344
Processing i =  86  out of  1344
Processing i =  87  out of  1344
Processing i =  88  out of  1344
Processing i =  89  out of  1344
Processing i =  90  out of  1344
Processing i =  91  out of  1344
Processing i =  92  out of  1344
Processing i =  93  out of  1344
Processing i =  94  out of  1344
Processing i =  95  out of  1344
Processing i =  96  out of  1344
Processing i =  97  out of  1344
Processing i =  98  out of  1344
Processing i =  99  out of  1344
Processing i =  100  out of  1344
Processing i =  101  out of  1344
Processing i =  102  out of  1344
Processing i =  103  out of  1344
Processing i =  104  out of  1344
Processing i =  105  out of  1344
Processing i =  106  out of  1344
Processing i =  107  out of  1344
Processing i =  108  out of  1344
Processing i =  109  out of  1344
Processing i =  110  out of  1344
Processing i =  111  out of  1344
Processing i =  112  out of  1344
Processing i =  113  out of  1344
Processing i =  114  out of  1344
Processing i =  115  out of  1344
Processing i =  116  out of  1344
Processing i =  117  out of  1344
Processing i =  118  out of  1344
Processing i =  119  out of  1344
Processing i =  120  out of  1344
Processing i =  121  out of  1344
Processing i =  122  out of  1344
Processing i =  123  out of  1344
Processing i =  124  out of  1344
Processing i =  125  out of  1344
Processing i =  126  out of  1344
Processing i =  127  out of  1344
Processing i =  128  out of  1344
Processing i =  129  out of  1344
Processing i =  130  out of  1344
Processing i =  131  out of  1344
Processing i =  132  out of  1344
Processing i =  133  out of  1344
Processing i =  134  out of  1344
Processing i =  135  out of  1344
Processing i =  136  out of  1344
Processing i =  137  out of  1344
Processing i =  138  out of  1344
Processing i =  139  out of  1344
Processing i =  140  out of  1344
Processing i =  141  out of  1344
Processing i =  142  out of  1344
Processing i =  143  out of  1344
Processing i =  144  out of  1344
Processing i =  145  out of  1344
Processing i =  146  out of  1344
Processing i =  147  out of  1344
Processing i =  148  out of  1344
Processing i =  149  out of  1344
Processing i =  150  out of  1344
Processing i =  151  out of  1344
Processing i =  152  out of  1344
Processing i =  153  out of  1344
Processing i =  154  out of  1344
Processing i =  155  out of  1344
Processing i =  156  out of  1344
Processing i =  157  out of  1344
Processing i =  158  out of  1344
Processing i =  159  out of  1344
Processing i =  160  out of  1344
Processing i =  161  out of  1344
Processing i =  162  out of  1344
Processing i =  163  out of  1344
Processing i =  164  out of  1344
Processing i =  165  out of  1344
Processing i =  166  out of  1344
Processing i =  167  out of  1344
Processing i =  168  out of  1344
Processing i =  169  out of  1344
Processing i =  170  out of  1344
Processing i =  171  out of  1344
Processing i =  172  out of  1344
Processing i =  173  out of  1344
Processing i =  174  out of  1344
Processing i =  175  out of  1344
Processing i =  176  out of  1344
Processing i =  177  out of  1344
Processing i =  178  out of  1344
Processing i =  179  out of  1344
Processing i =  180  out of  1344
Processing i =  181  out of  1344
Processing i =  182  out of  1344
Processing i =  183  out of  1344
Processing i =  184  out of  1344
Processing i =  185  out of  1344
Processing i =  186  out of  1344
Processing i =  187  out of  1344
Processing i =  188  out of  1344
Processing i =  189  out of  1344
Processing i =  190  out of  1344
Processing i =  191  out of  1344
Processing i =  192  out of  1344
Processing i =  193  out of  1344
Processing i =  194  out of  1344
Processing i =  195  out of  1344
Processing i =  196  out of  1344
Processing i =  197  out of  1344
Processing i =  198  out of  1344
Processing i =  199  out of  1344
Processing i =  200  out of  1344
Processing i =  201  out of  1344
Processing i =  202  out of  1344
Processing i =  203  out of  1344
Processing i =  204  out of  1344
Processing i =  205  out of  1344
Processing i =  206  out of  1344
Processing i =  207  out of  1344
Processing i =  208  out of  1344
Processing i =  209  out of  1344
Processing i =  210  out of  1344
Processing i =  211  out of  1344
Processing i =  212  out of  1344
Processing i =  213  out of  1344
Processing i =  214  out of  1344
Processing i =  215  out of  1344
Processing i =  216  out of  1344
Processing i =  217  out of  1344
Processing i =  218  out of  1344
Processing i =  219  out of  1344
Processing i =  220  out of  1344
Processing i =  221  out of  1344
Processing i =  222  out of  1344
Processing i =  223  out of  1344
Processing i =  224  out of  1344
Processing i =  225  out of  1344
Processing i =  226  out of  1344
Processing i =  227  out of  1344
Processing i =  228  out of  1344
Processing i =  229  out of  1344
Processing i =  230  out of  1344
Processing i =  231  out of  1344
Processing i =  232  out of  1344
Processing i =  233  out of  1344
Processing i =  234  out of  1344
Processing i =  235  out of  1344
Processing i =  236  out of  1344
Processing i =  237  out of  1344
Processing i =  238  out of  1344
Processing i =  239  out of  1344
Processing i =  240  out of  1344
Processing i =  241  out of  1344
Processing i =  242  out of  1344
Processing i =  243  out of  1344
Processing i =  244  out of  1344
Processing i =  245  out of  1344
Processing i =  246  out of  1344
Processing i =  247  out of  1344
Processing i =  248  out of  1344
Processing i =  249  out of  1344
Processing i =  250  out of  1344
Processing i =  251  out of  1344
Processing i =  252  out of  1344
Processing i =  253  out of  1344
Processing i =  254  out of  1344
Processing i =  255  out of  1344
Processing i =  256  out of  1344
Processing i =  257  out of  1344
Processing i =  258  out of  1344
Processing i =  259  out of  1344
Processing i =  260  out of  1344
Processing i =  261  out of  1344
Processing i =  262  out of  1344
Processing i =  263  out of  1344
Processing i =  264  out of  1344
Processing i =  265  out of  1344
Processing i =  266  out of  1344
Processing i =  267  out of  1344
Processing i =  268  out of  1344
Processing i =  269  out of  1344
Processing i =  270  out of  1344
Processing i =  271  out of  1344
Processing i =  272  out of  1344
Processing i =  273  out of  1344
Processing i =  274  out of  1344
Processing i =  275  out of  1344
Processing i =  276  out of  1344
Processing i =  277  out of  1344
Processing i =  278  out of  1344
Processing i =  279  out of  1344
Processing i =  280  out of  1344
Processing i =  281  out of  1344
Processing i =  282  out of  1344
Processing i =  283  out of  1344
Processing i =  284  out of  1344
Processing i =  285  out of  1344
Processing i =  286  out of  1344
Processing i =  287  out of  1344
Processing i =  288  out of  1344
Processing i =  289  out of  1344
Processing i =  290  out of  1344
Processing i =  291  out of  1344
Processing i =  292  out of  1344
Processing i =  293  out of  1344
Processing i =  294  out of  1344
Processing i =  295  out of  1344
Processing i =  296  out of  1344
Processing i =  297  out of  1344
Processing i =  298  out of  1344
Processing i =  299  out of  1344
Processing i =  300  out of  1344
Processing i =  301  out of  1344
Processing i =  302  out of  1344
Processing i =  303  out of  1344
Processing i =  304  out of  1344
Processing i =  305  out of  1344
Processing i =  306  out of  1344
Processing i =  307  out of  1344
Processing i =  308  out of  1344
Processing i =  309  out of  1344
Processing i =  310  out of  1344
Processing i =  311  out of  1344
Processing i =  312  out of  1344
Processing i =  313  out of  1344
Processing i =  314  out of  1344
Processing i =  315  out of  1344
Processing i =  316  out of  1344
Processing i =  317  out of  1344
Processing i =  318  out of  1344
Processing i =  319  out of  1344
Processing i =  320  out of  1344
Processing i =  321  out of  1344
Processing i =  322  out of  1344
Processing i =  323  out of  1344
Processing i =  324  out of  1344
Processing i =  325  out of  1344
Processing i =  326  out of  1344
Processing i =  327  out of  1344
Processing i =  328  out of  1344
Processing i =  329  out of  1344
Processing i =  330  out of  1344
Processing i =  331  out of  1344
Processing i =  332  out of  1344
Processing i =  333  out of  1344
Processing i =  334  out of  1344
Processing i =  335  out of  1344
Processing i =  336  out of  1344
Processing i =  337  out of  1344
Processing i =  338  out of  1344
Processing i =  339  out of  1344
Processing i =  340  out of  1344
Processing i =  341  out of  1344
Processing i =  342  out of  1344
Processing i =  343  out of  1344
Processing i =  344  out of  1344
Processing i =  345  out of  1344
Processing i =  346  out of  1344
Processing i =  347  out of  1344
Processing i =  348  out of  1344
Processing i =  349  out of  1344
Processing i =  350  out of  1344
Processing i =  351  out of  1344
Processing i =  352  out of  1344
Processing i =  353  out of  1344
Processing i =  354  out of  1344
Processing i =  355  out of  1344
Processing i =  356  out of  1344
Processing i =  357  out of  1344
Processing i =  358  out of  1344
Processing i =  359  out of  1344
Processing i =  360  out of  1344
Processing i =  361  out of  1344
Processing i =  362  out of  1344
Processing i =  363  out of  1344
Processing i =  364  out of  1344
Processing i =  365  out of  1344
Processing i =  366  out of  1344
Processing i =  367  out of  1344
Processing i =  368  out of  1344
Processing i =  369  out of  1344
Processing i =  370  out of  1344
Processing i =  371  out of  1344
Processing i =  372  out of  1344
Processing i =  373  out of  1344
Processing i =  374  out of  1344
Processing i =  375  out of  1344
Processing i =  376  out of  1344
Processing i =  377  out of  1344
Processing i =  378  out of  1344
Processing i =  379  out of  1344
Processing i =  380  out of  1344
Processing i =  381  out of  1344
Processing i =  382  out of  1344
Processing i =  383  out of  1344
Processing i =  384  out of  1344
Processing i =  385  out of  1344
Processing i =  386  out of  1344
Processing i =  387  out of  1344
Processing i =  388  out of  1344
Processing i =  389  out of  1344
Processing i =  390  out of  1344
Processing i =  391  out of  1344
Processing i =  392  out of  1344
Processing i =  393  out of  1344
Processing i =  394  out of  1344
Processing i =  395  out of  1344
Processing i =  396  out of  1344
Processing i =  397  out of  1344
Processing i =  398  out of  1344
Processing i =  399  out of  1344
Processing i =  400  out of  1344
Processing i =  401  out of  1344
Processing i =  402  out of  1344
Processing i =  403  out of  1344
Processing i =  404  out of  1344
Processing i =  405  out of  1344
Processing i =  406  out of  1344
Processing i =  407  out of  1344
Processing i =  408  out of  1344
Processing i =  409  out of  1344
Processing i =  410  out of  1344
Processing i =  411  out of  1344
Processing i =  412  out of  1344
Processing i =  413  out of  1344
Processing i =  414  out of  1344
Processing i =  415  out of  1344
Processing i =  416  out of  1344
Processing i =  417  out of  1344
Processing i =  418  out of  1344
Processing i =  419  out of  1344
Processing i =  420  out of  1344
Processing i =  421  out of  1344
Processing i =  422  out of  1344
Processing i =  423  out of  1344
Processing i =  424  out of  1344
Processing i =  425  out of  1344
Processing i =  426  out of  1344
Processing i =  427  out of  1344
Processing i =  428  out of  1344
Processing i =  429  out of  1344
Processing i =  430  out of  1344
Processing i =  431  out of  1344
Processing i =  432  out of  1344
Processing i =  433  out of  1344
Processing i =  434  out of  1344
Processing i =  435  out of  1344
Processing i =  436  out of  1344
Processing i =  437  out of  1344
Processing i =  438  out of  1344
Processing i =  439  out of  1344
Processing i =  440  out of  1344
Processing i =  441  out of  1344
Processing i =  442  out of  1344
Processing i =  443  out of  1344
Processing i =  444  out of  1344
Processing i =  445  out of  1344
Processing i =  446  out of  1344
Processing i =  447  out of  1344
Processing i =  448  out of  1344
Processing i =  449  out of  1344
Processing i =  450  out of  1344
Processing i =  451  out of  1344
Processing i =  452  out of  1344
Processing i =  453  out of  1344
Processing i =  454  out of  1344
Processing i =  455  out of  1344
Processing i =  456  out of  1344
Processing i =  457  out of  1344
Processing i =  458  out of  1344
Processing i =  459  out of  1344
Processing i =  460  out of  1344
Processing i =  461  out of  1344
Processing i =  462  out of  1344
Processing i =  463  out of  1344
Processing i =  464  out of  1344
Processing i =  465  out of  1344
Processing i =  466  out of  1344
Processing i =  467  out of  1344
Processing i =  468  out of  1344
Processing i =  469  out of  1344
Processing i =  470  out of  1344
Processing i =  471  out of  1344
Processing i =  472  out of  1344
Processing i =  473  out of  1344
Processing i =  474  out of  1344
Processing i =  475  out of  1344
Processing i =  476  out of  1344
Processing i =  477  out of  1344
Processing i =  478  out of  1344
Processing i =  479  out of  1344
Processing i =  480  out of  1344
Processing i =  481  out of  1344
Processing i =  482  out of  1344
Processing i =  483  out of  1344
Processing i =  484  out of  1344
Processing i =  485  out of  1344
Processing i =  486  out of  1344
Processing i =  487  out of  1344
Processing i =  488  out of  1344
Processing i =  489  out of  1344
Processing i =  490  out of  1344
Processing i =  491  out of  1344
Processing i =  492  out of  1344
Processing i =  493  out of  1344
Processing i =  494  out of  1344
Processing i =  495  out of  1344
Processing i =  496  out of  1344
Processing i =  497  out of  1344
Processing i =  498  out of  1344
Processing i =  499  out of  1344
Processing i =  500  out of  1344
Processing i =  501  out of  1344
Processing i =  502  out of  1344
Processing i =  503  out of  1344
Processing i =  504  out of  1344
Processing i =  505  out of  1344
Processing i =  506  out of  1344
Processing i =  507  out of  1344
Processing i =  508  out of  1344
Processing i =  509  out of  1344
Processing i =  510  out of  1344
Processing i =  511  out of  1344
Processing i =  512  out of  1344
Processing i =  513  out of  1344
Processing i =  514  out of  1344
Processing i =  515  out of  1344
Processing i =  516  out of  1344
Processing i =  517  out of  1344
Processing i =  518  out of  1344
Processing i =  519  out of  1344
Processing i =  520  out of  1344
Processing i =  521  out of  1344
Processing i =  522  out of  1344
Processing i =  523  out of  1344
Processing i =  524  out of  1344
Processing i =  525  out of  1344
Processing i =  526  out of  1344
Processing i =  527  out of  1344
Processing i =  528  out of  1344
Processing i =  529  out of  1344
Processing i =  530  out of  1344
Processing i =  531  out of  1344
Processing i =  532  out of  1344
Processing i =  533  out of  1344
Processing i =  534  out of  1344
Processing i =  535  out of  1344
Processing i =  536  out of  1344
Processing i =  537  out of  1344
Processing i =  538  out of  1344
Processing i =  539  out of  1344
Processing i =  540  out of  1344
Processing i =  541  out of  1344
Processing i =  542  out of  1344
Processing i =  543  out of  1344
Processing i =  544  out of  1344
Processing i =  545  out of  1344
Processing i =  546  out of  1344
Processing i =  547  out of  1344
Processing i =  548  out of  1344
Processing i =  549  out of  1344
Processing i =  550  out of  1344
Processing i =  551  out of  1344
Processing i =  552  out of  1344
Processing i =  553  out of  1344
Processing i =  554  out of  1344
Processing i =  555  out of  1344
Processing i =  556  out of  1344
Processing i =  557  out of  1344
Processing i =  558  out of  1344
Processing i =  559  out of  1344
Processing i =  560  out of  1344
Processing i =  561  out of  1344
Processing i =  562  out of  1344
Processing i =  563  out of  1344
Processing i =  564  out of  1344
Processing i =  565  out of  1344
Processing i =  566  out of  1344
Processing i =  567  out of  1344
Processing i =  568  out of  1344
Processing i =  569  out of  1344
Processing i =  570  out of  1344
Processing i =  571  out of  1344
Processing i =  572  out of  1344
Processing i =  573  out of  1344
Processing i =  574  out of  1344
Processing i =  575  out of  1344
Processing i =  576  out of  1344
Processing i =  577  out of  1344
Processing i =  578  out of  1344
Processing i =  579  out of  1344
Processing i =  580  out of  1344
Processing i =  581  out of  1344
Processing i =  582  out of  1344
Processing i =  583  out of  1344
Processing i =  584  out of  1344

## 4. Inspect Recap

After the batch finishes, inspect the PyNNLF recap. The complete SA BESS run should have 36 rows: 3 datasets by 12 model/hyperparameter choices.

In [4]:
recap_path = PROJECT_DIR / 'experiment_result' / 'a1_experiment_result.csv'
recap = pd.read_csv(recap_path)
print(f'Recap rows: {len(recap):,}')
display(recap[['dataset_no', 'model_name', 'test_nRMSE', 'test_nRMSE_stddev']])

Recap rows: 36

   dataset_no       model_name  test_nRMSE  test_nRMSE_stddev
0        ds16      m17_xgb_hp1    3.224934           0.293571
1        ds16       m8_dnn_hp1    5.986006           0.703674
2        ds16        m6_lr_hp1    3.082543           0.228790
3        ds16       m10_rf_hp1    4.376197           0.339607
4        ds16       m7_ann_hp1    5.460705           0.601846
5        ds16     m1_naive_hp1    4.270692           0.244157
6        ds16       m3_ets_hp1    4.212272           0.168914
7        ds16        m9_rt_hp3    6.725240           0.815398
8        ds16     m13_lstm_hp2   16.774768           1.706541
9        ds16    m2_snaive_hp2    7.516114           1.249377
10       ds16  m16_prophet_hp1    6.851643           1.309192
11       ds16     m4_arima_hp1    3.970578           0.168664
12       ds17      m17_xgb_hp1    6.305710           0.930540
13       ds17       m8_dnn_hp1    9.267245           1.713207
14       ds17        m6_lr_hp1    5.769087           0.470714
15       ds17       m10_rf_hp1   12.655225           1.610819
16       ds17       m7_ann_hp1    9.129553           1.129429
17       ds17     m1_naive_hp1   11.497058           1.347774
18       ds17       m3_ets_hp1   11.336787           1.323548
19       ds17        m9_rt_hp3   18.195774           2.432907
20       ds17     m13_lstm_hp2   59.803457          10.808015
21       ds17    m2_snaive_hp2   22.470394           3.666507
22       ds17  m16_prophet_hp1   21.574314           5.507452
23       ds17     m4_arima_hp1    9.177585           0.853422
24       ds18      m17_xgb_hp1    5.571771           0.983519
25       ds18       m8_dnn_hp1    8.746302           1.735866
26       ds18        m6_lr_hp1    5.092104           0.466129
27       ds18       m10_rf_hp1   11.326524           1.612574
28       ds18       m7_ann_hp1    7.938964           1.150363
29       ds18     m1_naive_hp1    9.818598           1.832779
30       ds18       m3_ets_hp1    9.618823           1.823998
31       ds18        m9_rt_hp3   16.532020           2.389269
32       ds18     m13_lstm_hp2   51.616593          11.327788
33       ds18    m2_snaive_hp2   21.341975           4.083446
34       ds18  m16_prophet_hp1   20.546177           5.409208
35       ds18     m4_arima_hp1    7.913740           1.062988

## 5. Build Publication Tables

Create the two wide CSV tables for the article: one for test nRMSE and one for test nRMSE standard deviation.

In [5]:
from process_pynnlf_output import build_publication_tables

nrmse_table, nrmse_stddev_table = build_publication_tables(PROJECT_DIR)
display(nrmse_table)
display(nrmse_stddev_table)
print(PROJECT_DIR / 'results' / 'sa_bess_nrmse_comparison.csv')
print(PROJECT_DIR / 'results' / 'sa_bess_nrmse_stddev_comparison.csv')

                 underlying_load  net_load_with_pv  net_load_with_pv_battery
model_hp
m17_xgb_hp1             3.224934          6.305710                  5.571771
m8_dnn_hp1              5.986006          9.267245                  8.746302
m6_lr_hp1               3.082543          5.769087                  5.092104
m10_rf_hp1              4.376197         12.655225                 11.326524
m7_ann_hp1              5.460705          9.129553                  7.938964
m1_naive_hp1            4.270692         11.497058                  9.818598
m3_ets_hp1              4.212272         11.336787                  9.618823
m9_rt_hp3               6.725240         18.195774                 16.532020
m13_lstm_hp2           16.774768         59.803457                 51.616593
m2_snaive_hp2           7.516114         22.470394                 21.341975
m16_prophet_hp1         6.851643         21.574314                 20.546177
m4_arima_hp1            3.970578          9.177585                  7.913740

                 underlying_load  net_load_with_pv  net_load_with_pv_battery
model_hp
m17_xgb_hp1             0.293571          0.930540                  0.983519
m8_dnn_hp1              0.703674          1.713207                  1.735866
m6_lr_hp1               0.228790          0.470714                  0.466129
m10_rf_hp1              0.339607          1.610819                  1.612574
m7_ann_hp1              0.601846          1.129429                  1.150363
m1_naive_hp1            0.244157          1.347774                  1.832779
m3_ets_hp1              0.168914          1.323548                  1.823998
m9_rt_hp3               0.815398          2.432907                  2.389269
m13_lstm_hp2            1.706541         10.808015                 11.327788
m2_snaive_hp2           1.249377          3.666507                  4.083446
m16_prophet_hp1         1.309192          5.507452                  5.409208
m4_arima_hp1            0.168664          0.853422                  1.062988

C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\results\sa_bess_nrmse_comparison.csv
C:\Users\z5404477\Documents\PyNNLF\publication\journal_article_1\results\sa_bess_nrmse_stddev_comparison.csv